v6d-io/v6d

.github/workflows/build-test.yml
Upload coverage to codecov.io.
=> Upload coverage to codecov.io.

modules/graph/fragment/arrow_fragment.h, modules/graph/fragment/graph_schema.cc, modules/graph/fragment/graph_schema.h, modules/graph/utils/context_protocols.h, modules/graph/utils/selector_utils.h
Add get graph schema interface for python traverse app.
Fixes
=> Add get schema interface for traverse app

modules/graph/utils/error.h
Minor enhancement to error handling macros.
=> Add a macro to check condition then return a GSError

.github/codecov.yml
Now the number should reach 75%.
=> Enhance the configuration for coverage data.

.github/workflows/build-test.yml, .github/workflows/build-vineyardd.yaml, .github/workflows/build-wheel.yml, CMakeLists.txt, docker/Dockerfile.vineyardd, docker/pypa/Dockerfile.manylinux1, docker/pypa/Dockerfile.manylinux1-wheel
+ build vineyardd's alpine container
+ build wheels for both linux and mac
+ upload necessary artifacts.
=> Build vineyardd image, and wheels.

modules/graph/fragment/graph_schema.cc, modules/graph/fragment/graph_schema.h, modules/graph/loader/arrow_fragment_loader.h, modules/graph/test/arrow_fragment_test.cc
=> Get maxgraph schema and dump to file.

modules/io/adaptors/parse_dataframe_to_orc.py, modules/io/adaptors/parse_orc_to_dataframe.py, modules/io/adaptors/read_hdfs_bytes.py, modules/io/adaptors/write_hdfs_bytes.py, modules/io/python/stream.py
=> hdfs bytes support

modules/graph/utils/selector_utils.h
Loosen validity check for selector of `r`, since value can be specified by user in app
=> Loosen checks for selector.

modules/io/adaptors/parse_dataframe_to_bytes.py, modules/io/adaptors/read_hdfs_bytes.py, modules/io/adaptors/read_hdfs_orc.py, modules/io/adaptors/read_local_orc.py, modules/io/adaptors/write_hdfs_orc.py, modules/io/adaptors/write_kafka_bytes.cc, modules/io/adaptors/write_kafka_dataframe.cc, modules/io/adaptors/write_local_dataframe.cc, modules/io/python/stream.py
=> fix orc/hdfs for large file

src/client/io.cc, src/server/async/ipc_server.cc, src/server/async/rpc_server.cc
=> Report permission error in a more friendly way.

modules/io/adaptors/parse_bytes_to_dataframe.cc, modules/io/adaptors/parse_dataframe_to_bytes.py, modules/io/adaptors/read_hdfs_bytes.py, modules/io/adaptors/read_hdfs_orc.py, modules/io/adaptors/read_hive_orc.py, modules/io/adaptors/read_local_orc.py, modules/io/adaptors/write_local_bytes.py, modules/io/python/stream.py
=> fix for test

.github/workflows/build-test.yml, .gitignore, CMakeLists.txt, docs/notes/troubleshooting.rst, modules/basic/ds/arrow.vineyard-mod, modules/io/adaptors/parse_dataframe_to_bytes.py, python/core.cc, python/stream.cc, python/vineyard/__init__.py, python/vineyard/data/tests/test_arrow.py, python/vineyard/data/tests/test_default.py, python/vineyard/version.py.in
=> Enable python tests

modules/graph/fragment/property_graph_utils.h, modules/graph/loader/arrow_fragment_loader.h, modules/io/io/local_io_adaptor.cc, modules/io/io/local_io_adaptor.h
* LocalIOAdaptor can now support specify data type for individual columns.
* LocalIOAdaptor can now accept number as column indices.
=> Enhance local io adaptor

CMakeLists.txt, modules/basic/ds/arrow_utils.h, modules/graph/fragment/property_graph_utils.h, modules/io/CMakeLists.txt, modules/io/adaptors/read_local_orc.py, modules/io/adaptors/read_oss_dataframe.cc, modules/io/adaptors/write_hdfs_orc.py, modules/io/adaptors/write_local_orc.py, modules/io/adaptors/write_vineyard_dataframe.py, modules/io/io/local_io_adaptor.cc, modules/io/io/oss_io_adaptor.cc, modules/io/io/oss_io_adaptor.h, modules/io/python/stream.py, modules/io/python/tests/conftest.py, modules/io/python/tests/test_open.py
=> add oss adaptor and read driver

modules/basic/ds/arrow.h, modules/basic/ds/arrow.vineyard-mod, test/arrow_data_structure_test.cc
`StringArray` was removed from #65, this PR adds it back.
=> Add string array back

modules/basic/ds/arrow_utils.cc, modules/basic/ds/arrow_utils.h, modules/graph/fragment/arrow_fragment.h, modules/graph/fragment/graph_schema.cc
=> Add some utf8 branch

modules/io/io/local_io_adaptor.cc, modules/io/io/local_io_adaptor.h, modules/io/io/oss_io_adaptor.cc, modules/io/io/oss_io_adaptor.h
If properties is not specified, we will load all columns.
=> Add include all option

modules/graph/CMakeLists.txt, modules/io/CMakeLists.txt, src/client/client_base.cc, src/server/util/meta_tree.cc
=> Fixes a bug in get and persist remote metadata (remote object).

setup.cfg.in
Then we can work with other versions of pyarrow.
=> Relax the version constraints of pyarrow.

modules/graph/loader/arrow_fragment_loader.h, python/vineyard/data/dataframe.py, setup.cfg.in, src/server/services/meta_service.cc, src/server/services/meta_service.h, src/server/util/meta_tree.cc, src/server/util/meta_tree.h
=> Merge subtrees when persist.

modules/basic/ds/dataframe.cc, modules/basic/ds/dataframe.h, modules/basic/ds/dataframe.vineyard-mod, python/vineyard/data/__init__.py, python/vineyard/data/dataframe.py, python/vineyard/data/index.py, python/vineyard/data/tests/test_dataframe.py
support the index of dataframe structrue.
Fixes #109
=> support index of dataframe

modules/basic/ds/dataframe.cc, modules/basic/ds/dataframe.h, modules/basic/ds/dataframe.vineyard-mod, modules/basic/stream/dataframe_stream.vineyard-mod, modules/graph/fragment/graph_schema.cc, modules/io/io/utils.h, modules/migrate/protocols.cc, python/core.cc, python/vineyard/data/dataframe.py, python/vineyard/data/tests/test_dataframe.py, src/client/ds/object_meta.cc, src/client/ds/object_meta.h, src/common/util/protocols.cc, src/server/vineyardd.cc, test/dataframe_test.cc
To match the behaviour of pandas's DataFrame better, see test cases added by this PR.
=> Allow DataFrame's columns names to be arbitary value that can be jsonified

CMakeLists.txt, python/client.cc, python/vineyard/_vineyard_docs.py, src/client/client.cc, src/client/client_base.h, src/client/rpc_client.cc, src/common/util/macros.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/common/util/status.h, src/common/util/version.h, src/server/async/socket_server.cc, src/server/services/meta_service.h, test/runner.py, test/version_test.cc
Add a version check when connected to vineyard server.
Fixes #128
=> Implement version validate: raise an warning if not compatible.

python/vineyard/deploy/tests/__init__.py, python/vineyard/deploy/tests/conftest.py, python/vineyard/deploy/tests/test_distributed.py, src/server/util/meta_tree.cc, test/persist_test.cc, test/runner.py
This bug happens when persist an object for multiple times.
=> Add distributed test cases, and fixes a bug in persist.

CONTRIBUTING.rst, charts/vineyard/.helmignore, charts/vineyard/Chart.yaml, charts/vineyard/README.rst, charts/vineyard/templates/NOTES.txt, charts/vineyard/templates/_helpers.tpl, charts/vineyard/templates/daemonset.yaml, charts/vineyard/templates/etcd.yaml, charts/vineyard/templates/service.yaml, charts/vineyard/templates/tests/test-ipc.yaml, charts/vineyard/values.yaml, docs/charts/.gitignore
=> Helm integration of vineyard.

python/vineyard/deploy/etcd.yaml, python/vineyard/deploy/etcd_service.yaml, python/vineyard/deploy/k8s.py, python/vineyard/deploy/utils.py, python/vineyard/deploy/vineyard_daemonset.yaml.tmpl, python/vineyard/deploy/vineyard_k8s.yaml.tmpl, python/vineyard/deploy/vineyard_service.yaml.tmpl, setup.cfg.in
=> Add k8s deploy in python

modules/io/adaptors/read_vineyard_dataframe.py
=> Support read_vineyard_dataframe with ObjectID.

README.rst
fix missing link of boost-leaf
Hyperlink of boost-leaf
Fixes #161.
=> fix missing link of boost-leaf

.github/workflows/build-compatibility.yml, .github/workflows/build-test.yml, .github/workflows/build-wheel.yml, CMakeLists.txt, docker/Dockerfile.vineyardd, modules/graph/utils/table_shuffler_beta.h, src/server/async/ipc_server.cc, src/server/async/ipc_server.h, src/server/async/rpc_server.cc, src/server/async/rpc_server.h, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h, src/server/services/etcd_meta_service.cc, src/server/services/meta_service.h
Make sure we pass the build process on Ubuntu 18.04 and MacOS at every run.
Fixes #180.
=> Enable compatibility build on Ubuntu 18.04 and MacOS.

.github/workflows/build-test.yml, docs/charts/.gitignore, docs/notes/getting-started.rst, modules/migrate/CMakeLists.txt, modules/migrate/object_migration.h, modules/migrate/vineyard_migrate.cc, python/client.cc, python/core.cc, python/vineyard/_vineyard_docs.py, python/vineyard/data/dataframe.py, python/vineyard/deploy/tests/conftest.py, python/vineyard/deploy/tests/test_migration.py, setup.py, src/client/client_base.cc, src/client/client_base.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h, src/server/services/meta_service.h, src/server/util/proc.cc, src/server/util/proc.h, test/runner.py
Backported from dev/kubernetes branch to main, from merged pull request #102.
Fixes #98.
=> Object migration, and add a test for that API.

modules/basic/ds/dataframe.cc, modules/basic/ds/dataframe.vineyard-mod, modules/graph/loader/arrow_fragment_loader.h, python/vineyard/data/tensor.py, python/vineyard/data/utils.py
Fixes dtype normalization for C++ to make tensors in python available for C++ as well.
N/A
=> Loading graph from global dataframe chunks.

src/common/util/env.cc, src/common/util/env.h, src/server/async/rpc_server.h, src/server/services/meta_service.h
=> Encapsulate platform/system related resolution into a env.h.

modules/migrate/vineyard_migrate.cc, modules/migrate/vineyard_migrate_stream.cc, python/vineyard/core/resolver.py, src/server/server/vineyard_server.cc
And throw an exception when getting an remote object.
=> Fixes signature marker and metadata reconstruct during migration.

docs/notes/troubleshooting.rst, python/vineyard/_vineyard_docs.py, python/vineyard/deploy/tests/test_distributed.py, setup.cfg.in, setup.py, src/client/client_base.h, src/server/server/vineyard_server.cc, src/server/services/meta_service.cc, src/server/services/meta_service.h, src/server/util/meta_tree.cc, src/server/util/meta_tree.h, test/delete_test.cc, test/rpc_delete_test.cc
See `Note [Deleting objects and blobs]`.
Fixes #199.
=> Revise the behaviour of deleting objects, especially deleting remote objects.

CMakeLists.txt, LICENSE, NOTICE.txt, cmake/FindGperftools.cmake, src/client/client.cc, src/client/client.h, src/client/rpc_client.cc, src/client/rpc_client.h, src/common/util/env.h, src/common/util/status.h, src/server/server/vineyard_server.cc, src/server/services/meta_service.h, src/server/util/meta_tree.cc, src/server/util/meta_tree.h, src/server/vineyardd.cc
Import use of gperftools, and avoid sync meta when deleting local objects.
Related to #127, but not fixes that.
=> Optimize the performance of delete: avoid sync meta when deleting local objects.

CMakeLists.txt, charts/vineyard/templates/daemonset.yaml, docker/Dockerfile.vineyardd, docker/vineyardd/Dockerfile.alpine-builder, docker/vineyardd/build_scripts/fixup-mirrors.sh
Add wait-for-it to docker image to wait for etcd services as well.
N/A
=> Add the Dockerfile for vineyardd alpine builder.

.github/workflows/build-test.yml, modules/io/adaptors/parse_dataframe_to_bytes.py, modules/io/adaptors/read_bytes.py, modules/io/adaptors/read_orc.py, modules/io/adaptors/read_vineyard_dataframe.py, modules/io/adaptors/write_orc.py, modules/io/adaptors/write_vineyard_dataframe.py, python/core.cc, python/stream.cc, python/vineyard/data/arrow.py, python/vineyard/data/default.py, python/vineyard/data/tensor.py, python/vineyard/data/utils.py, setup.py, src/common/util/status.h, src/server/util/meta_tree.cc
=> Use pickle, drop any ref about pa.serialize and pa.py_buffer.

docs/notes/cpp_api.rst, docs/notes/divein.rst, docs/notes/getting-started.rst, docs/notes/python_api.rst, docs/notes/roadmap.rst, python/vineyard/shared_memory/shared_memory.py
=> Improve the docs, add a section about how we distrbute datas.

modules/io/adaptors/deserializer.cc, src/client/ds/object_meta.cc, src/client/ds/object_meta.h
Otherwise there will be an error if the old object being deleted.
Related to #212.
=> Reset the signature in deserialization.

charts/vineyard/Chart.yaml, charts/vineyard/README.md, charts/vineyard/templates/daemonset.yaml, charts/vineyard/values.yaml
Add env to the vineyard pod as well.
=> Fixes a bug about the "image" argument in helm charts.

.github/workflows/build-compatibility.yml, CMakeLists.txt, LICENSE, cmake/FindJemalloc.cmake, src/server/memory/allocator.cc, src/server/memory/allocator.h, src/server/memory/dlmalloc.cc, src/server/memory/dlmalloc.h, src/server/memory/jemalloc.cc, src/server/memory/jemalloc.h, src/server/memory/malloc.cc, src/server/memory/malloc.h, src/server/memory/memory.cc, test/runner.py
=> Enable use of jemalloc.

README.rst, SECURITY.md, docs/notes/divein.rst, docs/notes/install.rst, docs/notes/troubleshooting.rst
=> Fixes several typos in docs.

modules/graph/fragment/property_graph_utils.h
Transform Date32 type to Int32 when reading CSV.
Related to #236 .
=> Fix unsupported date type when reading from csv

modules/io/adaptors/read_bytes.py
=> Glob files by prefix.

python/core.cc, python/vineyard/deploy/tests/test_distributed.py, src/client/client.cc, src/client/ds/blob.cc, src/client/ds/object_meta.cc, src/client/ds/object_meta.h, src/client/rpc_client.cc
Which makes vineyard HEAD unusable for graphscope...
=> Fixes a crucial bug about creating empty blobs.

src/common/backtrace/backtrace.hpp
See: https://gcc.gnu.org/onlinedocs/libstdc++/libstdc++-html-USERS-4.3/a01696.html.
`__cxa_demangle` will malloc when the parameter is NULL, and requires
parameter `length` to decide the _already available_ size of buffer, and
realloc it when not enough.
The previous implementation may lead to memory leak, and cause symbols
cannot be demangled successfully.
=> Fixes a bug in output_buffer management when print stacktrace.

modules/graph/loader/arrow_fragment_loader.h, modules/graph/loader/basic_arrow_fragment_loader.h, modules/graph/test/vertex_map_string_test.cc, modules/graph/test/vertex_map_test.cc, modules/io/adaptors/dump_dataframe.cc, modules/io/adaptors/parse_bytes_to_dataframe.cc, modules/io/adaptors/read_local_bytes.cc, modules/io/io/i_io_adaptor.h, modules/io/io/io_factory.cc, modules/io/io/io_factory.h, modules/io/io/kafka_io_adaptor.cc, modules/io/io/kafka_io_adaptor.h, modules/io/io/local_io_adaptor.cc, modules/io/io/local_io_adaptor.h
To make vineyard-io extensible for ODPS cupid, tunnel, etc.
=> Make io factory works in a register mode to make it extensible.

modules/graph/fragment/fragment_traits.h, modules/graph/utils/partitioner.h
rename EXPERIMENTAL_ON to NETWORKX
=> Rename EXPERIMENTAL_ON to NETWORKX

.github/workflows/build-test.yml, python/client.cc, python/vineyard/deploy/tests/test_distributed.py, test/runner.py
=> Add more concurrent tests on meta service.

docs/notes/roadmap.rst, python/client.cc, python/vineyard/_vineyard_docs.py, src/client/client.cc, src/client/client.h
=> Implements "client.AllocatedSize" API. 

modules/graph/fragment/graph_schema.cc
Signed-off-by: siyuan0322 <siyuan0322@gmail.com>
Fixes
=> Remove mapping generation when validate

modules/graph/fragment/arrow_fragment.h, modules/graph/fragment/arrow_fragment_group.h, modules/graph/fragment/property_graph_utils.h
Signed-off-by: siyuan0322 <siyuan0322@gmail.com>
Fixes
=> fix incorrect length of offset array

modules/basic/ds/dataframe.cc, modules/basic/ds/tensor.cc, modules/graph/fragment/arrow_fragment_group.h, python/client.cc, src/client/client_base.cc, src/client/client_base.h, src/common/util/protocols.cc, src/common/util/status.h, src/server/services/meta_service.h
And try if github action works ...
=> Add a "SyncMetaData" method.

python/core.cc, python/vineyard/_vineyard_docs.py, python/vineyard/core/builder.py, python/vineyard/data/base.py
=> Object builder for tuple and pair: accept an objectid as well.

docs/notes/divein.rst, docs/notes/getting-started.rst, python/vineyard/_vineyard_docs.py, python/vineyard/core/builder.py, python/vineyard/core/resolver.py
Fixes inconsistent examples in our documentation, reported by end users.
N/A
=> Fixes the inconsistent description in docs.

src/server/services/etcd_meta_service.cc, src/server/services/etcd_meta_service.h
Improve the persist efficiency by avoiding new watches in requestUpdates.
For benchmark, current main branch takes 195.63s for 9 related testcases. While this PR only takes 82.64s (<50%)
Fixes #304.
=> Improve the efficiency of vineyardd by avoid establishing new watches in requestUpdates

python/vineyard/deploy/tests/test_migration.py, test/runner.py
Record the time used for each CI runs.
None.
=> Adding timing information when running pytest.

docs/notes/divein.rst, docs/notes/faq.rst, docs/notes/getting-started.rst, docs/notes/install.rst, docs/notes/python_api.rst, docs/notes/roadmap.rst, docs/notes/troubleshooting.rst
* Minor Changes in documentation which makes the documentation more user-friendly and easier to understand.
* Fixed some minor issues.
* Added a patch in troubleshooting section which resolves the libgrape-lite error while installing vineyard.
Related to #296  but doesn't not fully fix it.
* Adding reference to api documentation for easy accessibility to a certain function
* Adding more patches to FAQ section to describe vineyard
=> Improved Documentation and Added Patch

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Revise the issue/pull request template on Github.
=> Revise the issue/pull-request template on Github.

python/core.cc, python/pybind11_utils.h, python/vineyard/core/tests/test_client.py
Extends the "iterator_state" to attach a custom globally available state to the iterator.
Fixes #341.
=> Fixes the state binding in metadata.items().

src/server/memory/memory.cc, src/server/memory/memory.h
Signed-off-by: Pei Li <peili@andrew.cmu.edu>
Free objects in BulkStore.
Fixes #333
=> Graceful clean-up on bulk store.(v6d-io#333)

src/common/backtrace/backtrace.hpp
The `abi::__cxa_demangle()` may fail, and returns a `NULL`, but there indeed a buffer that can be reused and the length is indeed a non-zero value.
Fixes alibaba/GraphScope#373
=> Fixes the buffer overflow error in get_demangled_name.

modules/io/io/io_factory.cc, modules/io/io/local_io_adaptor.cc
=> Support unicode path in io adaptor

src/server/memory/memory.cc
That will lead to unexpected crash, and fixes the handling for the special
marker in `PreAllocate` as well.
Follow-up work of #350.
Fixes #333.
=> Don't do iterate & delete-by-key at the same time.

docs/notes/divein.rst, docs/notes/getting-started.rst
Thanks @chaitravi-ce for reporting it on slack channel.
N/A.
=> Fixes the doc: we don't have vineyard.{array,dataframe}.

.github/workflows/build-test.yml, modules/graph/fragment/arrow_fragment_group.h, modules/io/io/local_io_adaptor.cc, python/vineyard/deploy/tests/test_distributed.py, setup.py, src/server/services/etcd_meta_service.cc, src/server/services/etcd_meta_service.h, src/server/services/meta_service.h, test/runner.py
Fixes the expected revision in `EtcdMetaService::requestUpdates()`, and add a concurrent persist+sync test case.
Follow-up work of #313.
=> Fixes the bug in requestUpdates, and add a check for the invariant.

src/server/services/etcd_meta_service.cc, src/server/services/etcd_meta_service.h, src/server/services/meta_service.h
=> Long-live watch handler to avoid any potential use-after-free error.

CMakeLists.txt
=> Enable address sanitizer for vineyardd if DEBUG is enabled.

src/server/services/etcd_meta_service.cc, src/server/services/etcd_meta_service.h
=> Use a priority_queue, as we have catched the assertion failure on CI.

.github/workflows/build-test.yml, .github/workflows/docs.yaml, CMakeLists.txt, python/vineyard/contrib/ml/__init__.py, python/vineyard/contrib/ml/mxnet.py, python/vineyard/contrib/ml/pytorch.py, python/vineyard/contrib/ml/tensorflow.py, setup_ml.py
Cut a seperated release for vineyard contrib ml for machine learning framework integration.
=> Enable a vineyard-ml package for ML frameworks integration.

src/server/util/etcd_launcher.cc
And etcd 3.5 has been release for a while.
=> This option has been deprecated since etcd 3.5.

python/vineyard/cli.py
- Refactored complete code according to the [**google python style guide**](https://google.github.io/styleguide/pyguide.html).
- Added two new arguments, `pattern` and `regex` to the **`list`** command.
=> Refactors cli.py and adds two new arguments to the list command

go/vineyard/.gitignore, go/vineyard/Makefile, go/vineyard/README.md, go/vineyard/go.mod, go/vineyard/go.sum, go/vineyard/hack/boilerplate.go.txt, go/vineyard/pkg/client/client.go, go/vineyard/pkg/client/ds/blob.go, go/vineyard/pkg/client/ds/object_meta.go, go/vineyard/pkg/client/ipc_client.go, go/vineyard/pkg/client/rpc_client.go, go/vineyard/pkg/common/id.go, go/vineyard/pkg/common/id_test.go, go/vineyard/pkg/common/protocol.go, go/vineyard/pkg/common/protocol_test.go, go/vineyard/pkg/common/status.go
Add the project framework for the go sdk.
Related to #228
=> Start the go sdk project.

.gitignore, setup.cfg
As there are many other configs.
=> The generated setup.cfg worth to be checked-in.

python/vineyard/cli.py
- Added `put` option to **put** a python value to the **vineyard server**.
- Added `config` option to **edit** the **vineyard configuration file**.
- Updated **connect to vineyard server function** to connect via `IPC` or `RPC` values from the **vineyard config file** if not provided via command line.
- Added **more options** to the `query` command.
=> Adds new commands and arguments to vineyard-ctl

java/.gitignore, java/core/apache-2.0.txt, java/core/pom.xml, java/core/src/main/java/io/v6d/core/Blob.java, java/core/src/main/java/io/v6d/core/ObjectMeta.java, java/core/src/main/java/io/v6d/core/client/Client.java, java/core/src/main/java/io/v6d/core/client/IPCClient.java, java/core/src/main/java/io/v6d/core/client/RPCClient.java, java/core/src/main/java/io/v6d/core/client/ds/Object.java, java/core/src/main/java/io/v6d/core/client/ds/ObjectFactory.java, java/core/src/main/java/io/v6d/core/common/util/InstanceID.java, java/core/src/main/java/io/v6d/core/common/util/ObjectID.java, java/core/src/main/java/io/v6d/core/common/util/Protocol.java, java/core/src/main/java/io/v6d/core/common/util/Signature.java, java/core/src/main/java/io/v6d/core/common/util/VineyardException.java, java/core/src/test/java/io/v6d/core/client/IPCClientTest.java, java/core/src/test/java/io/v6d/core/common/util/IdTest.java, java/core/src/test/java/io/v6d/core/common/util/ProtocolTest.java
The framework code of java-client for vineyard, including
+ id, signature, etc.
+ protocol
+ start of base client
+ rpc client
Related to #227.
=> The framework of java-client for vineyard.

java/core/src/main/java/io/v6d/core/client/IPCClient.java
=> Fixes write bytes and formatting of objectmapper.

go/vineyard/go.mod, go/vineyard/pkg/client/client_base.go, go/vineyard/pkg/client/io.go, go/vineyard/pkg/client/io_test.go, go/vineyard/pkg/client/ipc_client.go, go/vineyard/pkg/client/ipc_client_test.go, go/vineyard/pkg/client/rpc_client.go, go/vineyard/pkg/client/rpc_client_test.go, go/vineyard/pkg/common/id.go, go/vineyard/pkg/common/protocol.go, go/vineyard/pkg/common/protocol_test.go, go/vineyard/pkg/common/status.go, go/vineyard/pkg/common/util.go
Implement go sdk ipc and rpc connect and close api with test file.
None
=> Add go sdk rpc/ipc client connect and close api implementation

docs/index.rst, docs/notes/ml.rst
=> Add a doc chapter for ML integration.

.github/workflows/build-test.yml, python/vineyard/contrib/ml/tests/__init__.py, python/vineyard/contrib/ml/xgboost.py, python/vineyard/data/dataframe.py, setup_ml.py
Enable contrib-ml test both for pull request and for main branch.
Installing the required deps (xgboost, tensorflow) as well.
Follow-up fix for #394, related to #280 as well.
=> Enable contrib-ml test, and install xgboost deps.

python/vineyard/__init__.py, python/vineyard/core/__init__.py, python/vineyard/core/builder.py, python/vineyard/core/driver.py, python/vineyard/core/resolver.py, python/vineyard/core/tests/test_context.py
Implemented context as described in #398.
Fixes #398.
=> Contextual resolver/builder/driver for flexible nested dynamic registry.

python/vineyard/contrib/ml/xgboost.py
=> Tidy up contrib/ml/xgboost with new resolver context

docs/notes/ctl.rst
Added **documentation** for `vineyard-ctl`.
=> Adds documentation for vineyard-ctl

python/vineyard/contrib/ml/pytorch.py, python/vineyard/contrib/ml/tensorflow.py
Added resolvers for vineyard::GlobalTensor and vineyard::GlobalDataFrame which will return a list of local objects in form of tf.data.Datasets.
=> Added Global Resolvers for Tensorflow and Local Builders and Resolvers for PyTorch

.github/workflows/build-test.yml, python/vineyard/contrib/airflow/__init__.py, python/vineyard/contrib/airflow/xcom/__init__.py, python/vineyard/contrib/airflow/xcom/backend.py, setup.py, setup_airflow.py
Implements the xcom backend for airflow, with fully integration with the data lifecycle management by insert hooks into routines in XCom backend.
Part of #374, and depends on apache/airflow#17405
=> Vineyard XCom backend for apache-airflow.

python/vineyard/contrib/ml/tensorflow.py, python/vineyard/contrib/ml/tests/test_tensorflow.py
* Added Tests for local objects in Tensorflow
* Refactored code for vineyard::Table resolvers
=> Added Tests for Tensorflow

.github/workflows/build-test.yml, CMakeLists.txt, python/vineyard/contrib/dask/dask.py, python/vineyard/contrib/dask/tests/conftest.py, python/vineyard/contrib/dask/tests/test_dask.py, setup_dask.py, test/runner.py
Add two resolvers for dask: GlobalTensor --> dask.Array, GlobalDataFrame --> dask.dataframe
Part of #412.
=> Add Dask Integration: vineyard as the data source for dask

python/vineyard/contrib/dask/dask.py, python/vineyard/contrib/dask/tests/test_dask.py
Add builders for dask:
- dask.Array --> vineyard::GlobalTensor
- dask.DataFrame --> vineyard::GlobalDataFrame
Part of #412.
=> Add Dask Integration: vineyard as data sink

docs/notes/ctl.rst, python/vineyard/cli.py
Added `migrate` command to **vineyard-ctl**.
Part of #291.
=> Adds migrate command to vineyard-ctl

.github/workflows/build-test.yml, python/vineyard/contrib/dask/__init__.py, python/vineyard/contrib/dask/tests/__init__.py
=> Add missing __init__.py to dask module otherwise it is an empty package.

modules/io/python/drivers/io/stream.py, python/client.cc, python/vineyard/conftest.py, python/vineyard/contrib/dask/dask.py, python/vineyard/contrib/dask/tests/conftest.py, python/vineyard/contrib/dask/tests/test_dask.py, python/vineyard/contrib/ml/xgboost.py, python/vineyard/data/dataframe.py, python/vineyard/data/tensor.py, python/vineyard/deploy/tests/conftest.py, python/vineyard/deploy/utils.py, setup.py, setup_dask.py, test/runner.py
=> Lint: reduce code duplication, remove unused imports, isort, etc.

modules/graph/fragment/arrow_fragment.h, modules/graph/fragment/property_graph_utils.h
fix bug property_graph_util::VertexDataColumn subtraction between shared_ptr and ptrdiff_t
Fixes #427
=> Bug Fix: #427 property_graph_util::VertexDataColumn subtraction between shared_ptr and ptrdiff_t

docs/notes/troubleshooting.rst
It seems a common problem for newcomers.
N/A
=> Add a troubleshooting section about the "permission error".

.github/workflows/rust-ci.yml
=> Fix invalid step

docs/notes/ml.rst, python/vineyard/contrib/ml/tests/test_xgboost.py, python/vineyard/contrib/ml/xgboost.py
Add doc for xgboost and also set up feature_names in dataframe-like resolvers
Part of #280
=> Add doc and quick fix to xgboost

java/core/pom.xml, java/modules/basic/pom.xml, java/modules/pom.xml
Fixes the RPATH issue by add extra link options.
Resolves #449.
=> Fixes the RPATH problem on Mac.

python/vineyard/contrib/ml/tensorflow.py
=> Fix bug in tensorflow resolver

java/core/pom.xml, java/core/src/main/cpp/ffi/object_meta.cc, java/core/src/main/java/io/v6d/core/client/IPCClient.java, java/core/src/main/java/io/v6d/core/client/ds/ObjectFactory.java, java/core/src/main/resources/logback.xml, java/modules/basic/pom.xml, java/modules/basic/src/main/resources/logback.xml, java/pom.xml, modules/graph/fragment/arrow_fragment.h, modules/graph/fragment/property_graph_utils.h, src/client/ds/object_factory.h, src/client/ds/object_meta.cc, src/client/ds/object_meta.h
+ Fixes a bug in read response and native lib output directory.
+ Adapt to vineyard java fragment SDK.
Part of #227 and #406.
=> Fixes a bug in read response and native lib output directory, and adapt to Vineyard Java Fragment.

charts/vineyard/Chart.yaml, java/core/pom.xml, java/core/src/main/cpp/ffi/object_meta.cc, java/core/src/main/java/io/v6d/core/FFI.java, java/modules/basic/pom.xml, java/modules/pom.xml, java/pom.xml, src/client/client.cc, src/client/client.h, src/client/ds/object_meta.cc, src/client/ds/object_meta.h
Resolves the SIGBUS error on Mac, see also #455.
Fixes #455.
=> Feed a hand-written copy-ctor and copy-assignment to ObjectMeta.

src/server/async/socket_server.cc, test/allocator_test.cc, test/array_test.cc, test/arrow_data_structure_test.cc, test/dataframe_test.cc, test/delete_test.cc, test/get_object_test.cc, test/get_wait_test.cc, test/global_object_test.cc, test/hashmap_test.cc, test/id_test.cc, test/invalid_connect_test.cc, test/io_test.cc, test/jemalloc_test.cc, test/json_utils_test.cc, test/large_meta_test.cc, test/list_object_test.cc, test/pair_test.cc, test/persist_test.cc, test/rpc_delete_test.cc, test/rpc_get_object_test.cc, test/rpc_test.cc, test/scalar_test.cc, test/server_status_test.cc, test/shallow_copy_test.cc, test/signature_test.cc, test/stream_test.cc, test/tensor_test.cc, test/tuple_test.cc, test/version_test.cc
Re-format the code of test cases.
N/A
=> Vineyard tests: format & lint.

python/vineyard/contrib/ml/mxnet.py, python/vineyard/contrib/ml/tests/test_mxnet.py, python/vineyard/data/utils.py, setup_ml.py
* Added Local Builders and Resolvers for MxNet
* Added Global Resolvers for MxNet
* Added Tests for Local Object
=> Added MXNet Builders, Resolvers and Tests

modules/migrate/vineyard_migrate.cc, python/client.cc, python/vineyard/cli.py, src/client/client_base.cc, src/client/client_base.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h, test/deep_copy_test.cc, test/runner.py
This pull request is a combination of two commits.
`First commit`:
```
The first commit adds DeepCopy function to vineyard and the Python SDK.
The existing object migration code was used for the implementation.
```
`Second commit`:
```
The second commit updates vineyard-ctl to use the newly added
DeepCopy function when the user selects the --deep option under the copy command.
```
Part of #291.
=> Adds DeepCopy function to vineyard and Python SDK and adds it to vineyard-ctl

src/common/util/protocols.h
To ensure backwards compatibility.
Follow-up work of #467
=> Move the newly added item to the end of the enum.

docs/notes/ctl.rst, python/vineyard/cli.py
Added `debug` command to `vineyard-ctl` and updated the **documentation**.
Part of #291.
=> Adds debug command to vineyard-ctl

src/common/util/typename.h
To make sure vineyard works in graphscope environment.
See also: https://github.com/Manu343726/ctti/issues/19
N/A
=> Typename: compatible with higher version of GCC.

.github/workflows/build-test.yml, .github/workflows/docs.yaml, docs/conf.py, docs/example/dist_learn.ipynb, docs/examples/distributed-learning.ipynb, docs/index.rst, setup.py
This example demonstrates a distributed learning example using dask + horovod + v6d, which extends a real-world keras example with few lines of modifications.
Part of #488.
=> Add a notebook of a distributed learning example

.github/workflows/build-test.yml, docs/.gitignore
e.g., airflow_provider_vineyard.
N/A
=> Upload more wheels to the tagged release.

src/common/util/typename.h
See also: https://github.com/Manu343726/ctti/issues/35
N/A
=> Enable constexpr __PRETTY_FUNCTION__ only for gcc >= 9.1.0.

python/error.cc
Add a `VineyardException` super class.
Resolves #422
=> Add a vineyard exception class in Python.

docs/examples/distributed-learning.ipynb
Previously we provided the distributed learning example, but the notebook is not runnable. We fix this in the PR.
The notebook diff can be reviewed at https://app.reviewnb.com/v6d-io/v6d/pull/495/
Follow-up for #487
=> Make the distributed learning example runnable on a single machine

docs/notes/ctl.rst, python/vineyard/cli.py, setup.py
Adds **autocomplete functionality** to `vineyard-ctl` using the **python library** `argcomplete`.
Part of #291.
=> Adds autocomplete functionality to vineyard-ctl

modules/io/io/local_io_adaptor.cc, modules/io/io/local_io_adaptor.h
=> Trim BOM if found in beginning of file in LocalIOAdaptor

src/server/util/etcd_launcher.cc
Go (etcd internal) and C++ use different logic to resolve the address,
caused local `hostname` on Mac cannot be resolved by etcd, raising errors.
Fixes #527
=> EtcdLauncher: use the ip address to advertise.

modules/graph/fragment/arrow_fragment.h
related issue: https://github.com/alibaba/GraphScope/pull/866
=> Extend arrow_fragment API to support report method of GraphScope

python/vineyard/contrib/ml/dali.py, python/vineyard/contrib/ml/tests/test_dali.py, python/vineyard/contrib/ml/tests/test_pytorch.py, setup_ml.py
* Added Builder and Resolver for Nvidia-Dali
* Added Tests
=> Added Nvidia-Dali Builder and Resolver

docs/notes/ml.rst, python/vineyard/contrib/ml/pytorch.py, python/vineyard/contrib/ml/tests/test_mxnet.py
* Added Documentation for MxNet and Nvidia-DALI
* Improved ML Documentation
* Cleaned up unused imports
=> Added Documentation and Cleaned Up

modules/graph/fragment/arrow_fragment.h, modules/graph/fragment/property_graph_utils.h
=> Check graph is multigraph when `InitEdge` or `AddEdgeLabel`

modules/graph/fragment/arrow_fragment.h
=> Fix empty is_multgraph of meta  when `Project` and `AddVertexColumn`

python/vineyard/deploy/utils.py
=> Fallback to check localhost if meets AccessDenied on MacOS.

python/vineyard/core/codegen.py
Follow-up work for https://github.com/v6d-io/v6d/commit/5e912b1633f86a340db88f7232b305c09bd79fe2
=> Betterize the assertion error message.

java/modules/basic/src/main/java/io/v6d/modules/basic/columnar/ColumnarData.java
The implementation is heavily referred from spark.
Part of #227
=> Implements a columnar array visitor for arrow vectors in Java.

python/client.cc, python/core.cc, src/client/client.cc, src/client/client.h, src/client/ds/object_meta.cc, src/client/ds/object_meta.h, src/client/rpc_client.cc, src/client/rpc_client.h
+ Add a metadata.memory_usage interface
+ Add a client.list_metadata interface.
N/A
=> Enable list_metadata API on clients.

src/server/services/etcd_meta_service.cc
Watch all, and filter out unused key-value pairs.
Fixes #593
=> Ensure the etcd watcher could receive the whole latest updates as soon as possible

CMakeLists.txt, python/vineyard/_vineyard_docs.py, src/common/memory/fling.cc, src/common/util/status.h, src/server/server/vineyard_server.cc, src/server/services/meta_service.h, src/server/util/meta_tree.cc, src/server/util/meta_tree.h, test/custom_vector_test.cc, test/get_wait_test.cc, test/name_test.cc, test/runner.py
Embedding the `__name` properties into the metadata to make it available on the client side.
N/A
=> Enhance the implementation for `put/get/drop` names.

java/core/src/main/java/io/v6d/core/client/Client.java, java/core/src/main/java/io/v6d/core/client/IPCClient.java, java/core/src/main/java/io/v6d/core/common/util/Protocol.java, java/core/src/test/java/io/v6d/core/client/IPCClientTest.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/TableBuilder.java
Implements `client.delete`.
Fixes #227
=> Java: API for delete objects, and fixes a typo in TableBuilder.

java/core/pom.xml, java/modules/foreign-resolver/pom.xml, java/modules/graph/pom.xml
=> Remove the hard-code compiler path and fixes the wrong versions.

java/core/pom.xml, java/core/src/main/java/io/v6d/core/client/IPCClient.java, java/core/src/main/java/io/v6d/core/client/ds/Buffer.java, java/core/src/main/java/io/v6d/core/client/ds/ObjectFactory.java, java/core/src/main/java/io/v6d/core/client/ds/ObjectMeta.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/BooleanArray.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/BufferBuilder.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/DoubleArray.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/NullArray.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/Schema.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/StringArray.java, java/modules/basic/src/test/java/io/v6d/modules/basic/arrow/BufferTest.java, java/modules/foreign-resolver/pom.xml
as titled. Keep the same logic with C++.
Fixes #227
=> Fixes creating empty blobs.

modules/graph/fragment/arrow_fragment.h, modules/graph/fragment/property_graph_utils.h
=> Add transform direction feature for arrow fragment

modules/io/CMakeLists.txt, modules/io/io/io_factory.cc, src/server/services/meta_service.cc, src/server/services/meta_service.h
Load extra io adaptors from environment variable `VINEYARD_OTHER_IO_ADAPTORS`.
n/a.
=> Enable auto dlopen when initialize the io factory.

python/vineyard/_vineyard_docs.py
Add the missing doc.
The API is added in https://github.com/v6d-io/v6d/pull/591.
=> Add doc to `ObjectMeta.memory_usage`.

CMakeLists.txt, modules/graph/CMakeLists.txt, modules/graph/fragment/graph_schema.h, modules/graph/fragment/property_graph_utils.h, modules/graph/utils/error.h, modules/graph/utils/table_shuffler.h, modules/graph/utils/table_shuffler_beta.h
Upgrade to boost-leaf inside boost.
N/A
=> Upgrade boost-leaf to the latest version to adapt to boost itself.

python/client.cc
And release GIL when enter foreign scope to allow it happen in another thread.
N/A
=> Set default value to `{get,put}_name`.

python/client.cc, python/vineyard/_vineyard_docs.py, src/client/client_base.cc, src/client/client_base.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h, src/server/util/meta_tree.cc, src/server/util/meta_tree.h, test/clear_test.cc, test/runner.py
Implements a `clear()` method.
Fixes #538
=> Implements a `client.Clear()` method to drop all objects.

src/server/memory/allocator.cc
Follow up work for #322
Fixes #316
=> vineyardd: warn about --shm-size when running inside docker.

CMakeLists.txt, modules/basic/CMakeLists.txt, modules/basic/ds/dataframe.cc, modules/basic/ds/tensor.cc, modules/basic/stream/parallel_stream.h, modules/migrate/CMakeLists.txt, python/client.cc, src/client/allocator.h, src/client/arena_allocator.h, src/client/client.cc, src/client/client_base.cc, src/client/ds/blob.cc, src/client/ds/i_object.h, src/client/ds/object_factory.cc, src/client/ds/object_factory.h, src/client/ds/object_meta.cc, src/client/io.cc, src/client/rpc_client.cc, src/common/memory/arena.cc, src/common/memory/arena.h, src/common/memory/fling.cc, src/common/memory/jemalloc.cc, src/common/util/env.cc, src/common/util/functions.h, src/common/util/json.h, src/common/util/status.cc, src/common/util/status.h, src/server/async/ipc_server.cc, src/server/async/rpc_server.cc, src/server/memory/memory.cc
To resolve the dependency conflict issues when building the python package.
N/A
=> No glog dependency in vineyard_client.

modules/basic/ds/tuple.h, modules/basic/ds/tuple.vineyard-mod, modules/fuse/fusermount.cc, src/common/util/status.cc, test/arena_test.cc, test/name_test.cc, test/typename_test.cc
Fixes the missing include for `glog` in fuse module.
N/A
=> Fixes build failure on CI.

.github/workflows/build-vineyardd-and-wheels-macos.yaml
=> Re- setup python using "actions/setup-python@v2".

python/vineyard/core/tests/test_client.py, src/common/util/json.h, src/common/util/status.h, src/server/util/meta_tree.cc
See added test case `test_metadata_global `.
And ehance the error status message a bit.
N/A
=> Fixes a bug when adding full "metadata" as member of global objects.

python/vineyard/data/dataframe.py
Related to alibaba/GraphScope#1179
=> Fix the sequence of DataFrame may not correct

.pylintrc, python/vineyard/core/builder.py, python/vineyard/core/codegen.py, python/vineyard/core/tests/test_client.py, python/vineyard/core/tests/test_context.py, python/vineyard/data/__init__.py, python/vineyard/data/arrow.py, python/vineyard/data/base.py, python/vineyard/deploy/kubernetes.py, python/vineyard/launcher/script.py
=> Lint some python source files. 

modules/io/python/drivers/io/adaptors/deserializer.py, modules/io/python/drivers/io/adaptors/read_bytes_collection.py, modules/io/python/drivers/io/adaptors/serializer.py, modules/io/python/drivers/io/adaptors/write_bytes_collection.py, modules/io/python/drivers/io/adaptors/write_vineyard_dataframe.py, modules/io/python/drivers/io/stream.py, python/vineyard/io/stream.py
FIxes missing `persist` ops, and improve the error diagnostics.
N/A
=> Fixes serveral issues for (de)serialization on K8s.

CMakeLists.txt
=> Bump cmake mininum required version to 3.3

modules/graph/fragment/arrow_fragment.h, modules/graph/fragment/graph_schema.cc, modules/graph/fragment/graph_schema.h, modules/graph/loader/basic_ev_fragment_loader.h
=> More intuitive error messages for invalid schema

modules/io/python/drivers/io/adaptors/read_bytes.py, python/vineyard/io/utils.py, setup.cfg, setup.cfg.in, vineyard-config.in.cmake
=> Allow customized chunk size in read_bytes.

modules/graph/fragment/fragment_traits.h, modules/graph/utils/partitioner.h
=> Remove folly denpendency

modules/graph/fragment/property_graph_utils.h, modules/io/python/drivers/io/ossfs.py, modules/io/python/drivers/io/tests/test_ossfs.py, python/vineyard/data/pickle.py, python/vineyard/io/utils.py
Adapt to latest arrow (pyarrow) and black formatter.
N/A
=> Adapt to latest arrow, and upgrade black.

python/vineyard/contrib/ml/tests/test_dali.py
Fixes the ci failure on the main branch.
=> Fixes issue in pytest.mark.skipif.

modules/graph/loader/arrow_fragment_loader.h
as large tables may contains tons of chunks.
=> Drop the noisy logs.

src/client/client.cc, src/client/client.h, src/client/rpc_client.cc, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/server/vineyard_runner.cc, src/server/server/vineyard_runner.h, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h, test/external_test.cc, test/session_test.cc
As described in the title.
Related PR https://github.com/v6d-io/v6d/pull/677
=> [bugfix] Forbid normal client to connect to an external session and vice versa.

modules/graph/utils/context_protocols.h
=> Add a context protocol type to  support dynamic::kNullType and np.void or arrow::null

src/client/client.cc, src/client/client.h, src/client/client_base.h, src/client/ds/blob.h, src/client/ds/i_object.h, src/client/ds/object_meta.h, src/client/rpc_client.cc, src/common/memory/payload.cc, src/common/memory/payload.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/common/util/uuid.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/memory/memory.cc, src/server/memory/memory.h, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h, src/server/services/etcd_meta_service.h, test/plasma_test.cc, test/runner.py, test/session_test.cc
=> [1/2] Support "shallow copy" between sessions (normal only)

.github/workflows/docs.yaml, modules/graph/fragment/arrow_fragment.h, setup.py, src/client/client.cc, src/client/client.h, src/common/memory/payload.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/memory/memory.cc, src/server/memory/memory.h, src/server/server/vineyard_server.h, test/plasma_test.cc, test/session_test.cc
=> [2/2] Support "shallow copy" between sessions (plasma and normal)

src/server/services/etcd_meta_service.cc, src/server/services/etcd_meta_service.h
+ Sync with the bug-fixed version of etcd-cpp-apiv3 to make sure the `reconnect` logic behaves as expected.
+ Move the implementation of `Close()` method to the `.cc` file.
Fixes the CI failures on main branch.
=> Sync with the bug-fixed version of etcd-cpp-apiv3.

modules/basic/ds/dataframe.cc, modules/basic/ds/tensor.cc, modules/io/python/drivers/io/stream.py
Signed-off-by: siyuan0322 <siyuan0322@gmail.com>
=> Fix incorrect value of partition size in `GlobalDataFrame`

CMakeLists.txt, modules/basic/ds/arrow.h, modules/basic/ds/arrow.vineyard-mod, modules/basic/ds/arrow_utils.cc, modules/basic/ds/arrow_utils.h, modules/basic/stream/parallel_stream.h, modules/graph/fragment/arrow_fragment.h, modules/graph/fragment/arrow_fragment.vineyard-mod, modules/graph/fragment/fragment_traits.h, modules/graph/fragment/graph_schema.h, modules/graph/fragment/property_graph_utils.h, src/client/ds/stream.h, src/server/util/etcd_launcher.cc
+ Fixes bugs in arrow fragment mod.
+ Add missing APIs related streams.
+ Enable colorful error/warning messages in CMakeLists.txt
+ Bump up the version of etcd-cpp-apiv3
=> Fixes several bugs and missing APIs about fragment data structure

modules/basic/ds/arrow_utils.cc, modules/basic/ds/arrow_utils.h, modules/basic/stream/parallel_stream.cc, modules/basic/stream/parallel_stream.h, modules/basic/stream/parallel_stream.vineyard-mod, modules/basic/stream/recordbatch_stream.cc, modules/basic/stream/recordbatch_stream.h, modules/migrate/object_migration.cc, src/client/ds/stream.h, test/stream_test.cc
Fixes bugs in parallel stream builder and recordbatch streams.
=> Fixes the interfaces of parallel stream builder 

setup_migrate.py
Makes `twine check` happy.
N/A
=> Makes the readme satisfy the requirements of pypi

.github/workflows/build-archlinux-latest.yml, .github/workflows/build-centos-latest.yaml, docs/notes/install.rst, src/common/memory/arena.cc, src/common/memory/jemalloc.cc, src/common/memory/jemalloc.h, src/common/util/status.h, test/arena_test.cc
Testing arch linux and centos on the CI.
Fixes #742
=> Add CI actions for ArchLinux and CentOS latest

.github/workflows/build-test.yml, CONTRIBUTING.rst, README.rst, docs/notes/install.rst, test/runner.py
Refine the `test/runner.py` script and add a documentation section for how to use it.
Fixes #746, raised from https://github.com/v6d-io/v6d/discussions/741
=> Add a documentation section for how to run test cases

.github/workflows/build-compatibility.yml, docker/Dockerfile.vineyardd
=> Fixes issues in compatibility build

CMakeLists.txt, cmake/BuildEtcdCpp.cmake, modules/graph/CMakeLists.txt
Simplify the dependency management and prepare for packaging for various Linux/Unix platforms.
Related issues
Part of #554 and #578.
=> Build bundled thirdparty dependencies as static libraries

src/server/util/etcd_launcher.cc
Find a free port for peer endpoint when starting etcd in vineyardd.
Fixes issue reported in https://github.com/v6d-io/v6d/discussions/767
=> Etcd peer: find a free port.

src/client/client.cc, src/client/client.h, src/client/rpc_client.cc, src/common/util/lifecycle.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/memory/usage.h, src/server/server/vineyard_runner.cc, src/server/server/vineyard_runner.h, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h
As titled.
https://github.com/v6d-io/v6d/pull/677 (PlasmaBulkStore) https://github.com/v6d-io/v6d/issues/759 (GPUBulkStore)
=> Introduce `StoreType` to support diverse bulk store.

modules/basic/ds/arrow_utils.cc, modules/basic/ds/arrow_utils.h, modules/basic/ds/dataframe.cc, modules/basic/ds/dataframe.h, modules/basic/stream/dataframe_stream.cc, modules/basic/stream/recordbatch_stream.cc, modules/io/python/drivers/io/stream.py, modules/io/python/drivers/io/tests/test_migrate_stream.py, python/vineyard/io/parallel.py, src/client/ds/stream.h, src/common/util/protocols.cc, test/stream_test.cc
Fixes the resolver/builder for dataframe stream and recordbatch stream and make sure their semantic matches between C++ and Python.
N/A
=> Fixes the compatibility issue of stream implementation

README.rst
Signed-off-by: Tao He <sighingnow@gmail.com>
- Add a Table of Contents
- Refine the "Try Vineyard" section to avoid misleading about deploying on kubernetes and deploying locally.
Fixes #771, see also discussion in #767.
=> Refine the documentation about installation and try in README

modules/io/python/drivers/io/adaptors/deserializer.py, modules/io/python/drivers/io/adaptors/read_bytes_collection.py, modules/io/python/drivers/io/adaptors/serializer.py, modules/io/python/drivers/io/adaptors/write_bytes_collection.py, modules/io/python/drivers/io/stream.py, python/vineyard/io/stream.py, setup_io.py
Add a serialization options and support zstd compression by default.
Fixes #784
=> Enable zstd compression (by default) in serialization/deserailization.

python/core.cc
as titled.
Fixes https://github.com/v6d-io/v6d/issues/783
=> ObjectID and ObjectName: from/to URI.

src/client/ds/object_factory.cc
Find the `libvineyard_internal_registry.so` from the directory where `libvineyard_client.so` lives to make sure it find the nearest binary to load with `dlopen`. 
Follow-up work for https://github.com/v6d-io/v6d/pull/796.
=> Search libvineyard_internal_registry.so from current directory.

docs/tutorials/adding-custom-datatypes-cpp.rst
=> Fixes a typo in tutorials

modules/basic/ds/tensor.vineyard-mod
Fixes https://github.com/alibaba/GraphScope/issues/1753
=> Fixes compilation failure of ArrowTensorT<string_view> with template specialization

python/vineyard/contrib/airflow/docker/Dockerfile, python/vineyard/contrib/airflow/docker/docker-compose.yaml, python/vineyard/contrib/airflow/docker/docker-compose.yaml.diff, python/vineyard/contrib/airflow/xcom/backend.py
Makes the airflow-vineyard-provider compatibile with various version of apache-airflow.
Fixes #811.
=> Fixes the backwards compatibility issue of airflow

README.rst
Add a `clear: both;` to the style of the logo image.
Fixes #812
=> Ensure the logo is centerized.

README.rst, requirements.txt
See failure on https://github.com/v6d-io/v6d/runs/7173050035?check_suite_focus=true
=> Hotfix: Upgrade the numpy version to avoid compatiblity issue with pandas.

src/client/io.cc
Instead, we use `setsockopt()` and `write()` for MacOS.
Fixes #822
=> Use SO_NOSIGPIPE for MacOS

MAINTAINERS.md, README.rst
Make sure the anchors are rendered as expected on both Github README and the sphinx index.html.
N/A
=> Refine the TOC of README.rst, and add committers to our maintainers.md.

docs/_static/css/custom.css, docs/_templates/base.html
=> Force light theme, even the browers works under dark mode. 

src/client/client.cc, src/common/util/uuid.h, src/server/memory/memory.cc, test/id_test.cc, test/runner.py
Signed-off-by: ZjuYTW <wangyitao999@outlook.com>
Use random generator for `Generate BlobID`
Fixes #837 #777
=> make all GenerateBlobID use rand generator

docs/conf.py, docs/notes/architecture.rst, docs/notes/data-accessing.rst, docs/notes/getting-started.rst, docs/notes/io-drivers.rst, docs/notes/objects.rst, docs/notes/python-api.rst, docs/notes/roadmap.rst, docs/notes/streams.rst, docs/user-guide.rst, python/core.cc, python/vineyard/_vineyard_docs.py, python/vineyard/io/stream.py, python/vineyard/io/tests/test_stream.py
- Add the docstring for newly added APIs
- Add a `data-accessing` and `streams` pages in the documentation.
- Revisit the ROADMAP.rst in this PR as well.
Partially addresses issue #296.
=> Add documents for data accessing, streams and newly added APIs on clients

.gitmodules, CMakeLists.txt, modules/hosseinmoein-dataframe/CMakeLists.txt, modules/hosseinmoein-dataframe/CmakeLists.txt, modules/hosseinmoein-dataframe/build_hn_df.sh, modules/hosseinmoein-dataframe/hosseinmoein_dataframe.cc, modules/hosseinmoein-dataframe/hosseinmoein_dataframe.h, setup.py, test/hosseinmoein_dataframe_test.cc, test/runner.py
Integration hosseinmoein dataframe to support store it into vineyard as vineyard::dataframe
It supports <int32_t, int64_t, uint32_t, uint64_t, double, float> data type now.
Fixes #830
=> Integration with hosseinmoein dataframe

modules/graph/loader/arrow_fragment_loader.cc
Add stats about chunks in a recordbatch stream / dataframe stream.
N/A
=> Add some debugging logs for reading tables/recordbatches from streams

README.rst
=> Make sure the readme.rst conform the requirements of pypi

python/client.cc
As titled. Format the code as well.
Fixes #856
=> Fixes the wrong target class and missing arguments in the RPCClient.

modules/fuse/CMakeLists.txt, modules/fuse/adaptors/arrow.cc, modules/fuse/adaptors/arrow.h, modules/fuse/adaptors/formats.h, modules/fuse/fused.cc, modules/fuse/fused.h, modules/fuse/fusermount.cc
Add the uncommitted fuse releated code (mainly the arrow support, write support and some refactor). The fuse module is able to run presto as well as pandas on vineyard without deep integration.
Follow up work for #553 and part of #430.
=> Enhance the fuse integration.

docs/notes/getting-started.rst, docs/notes/install.rst
Add doc about [etcd](https://etcd.io/) to make the Installation more friendly to beginners.
=> Add doc about etcd

modules/basic/ds/arrow_utils.h, modules/io/io/io_factory.cc, modules/io/io/local_io_adaptor.cc, modules/io/io/utils.h, modules/migrate/vineyard_migrate.cc, modules/migrate/vineyard_migrate_stream.cc, src/client/client_base.cc, src/client/client_base.h, src/common/util/arrow.h, src/server/memory/usage.h, src/server/util/etcd_launcher.cc, src/server/util/file_io_adaptor.cc, src/server/util/proc.cc, src/server/util/proc.h, src/server/util/spec_resolvers.h, src/server/util/spill_file.cc, src/server/util/spill_file.h
Add checks for the returned status results.
=> Address some compilation warnings about warn-not-used.

benchmark/alloc_test/README.md
=> Fix a small error the doc

src/server/async/socket_server.cc, test/spill_test.cc
As titled, CI throws a fatal error but eventually passes the test in `spill_test`.
```
running test case -*-*-*-*-*-  spill_test  -*-*-*-*-*-*-*-
I0801 14:42:07.700294 32910 allocator.cc:69] shmax: 67108864
I0801 14:42:07.704481 32910 etcd_meta_service.cc:323] start background etcd watch, since 893
I0801 14:42:07.706903 32910 meta_service.h:411] Decide to set rank as 0
I0801 14:42:07.706923 32910 meta_service.h:814] Instance join: 0
I0801 14:42:07.707885 32910 ipc_server.cc:54] Vineyard will listen on "/tmp/vineyard.ci.1659336029.709189.sock" for IPC
I0801 14:42:07.707913 32910 rpc_server.cc:54] Vineyard will listen on 0.0.0.0:2060 for RPC
I0801 14:42:07.707928 32910 meta_service.h:814] Instance join: 0
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0801 14:42:07.708222 …
```
=> [CI] Don't panic if we just run out of memory.

.github/workflows/build-test.yml, .gitmodules, CMakeLists.txt, README.rst, docs/notes/data-accessing.rst, docs/notes/objects.rst, modules/malloc/malloc_wrapper.cc, modules/malloc/mimalloc_allocator.cc, modules/malloc/mimalloc_allocator.h, src/common/memory/mimalloc.cc, src/common/memory/mimalloc.h, src/server/memory/allocator.cc, src/server/memory/allocator.h, src/server/memory/malloc.cc, src/server/memory/malloc.h, src/server/memory/mimalloc.cc, src/server/memory/mimalloc.h, test/allocator_test.cc, test/mimalloc_test.cc
The pr is to add mimalloc for shared memory in vineyard. Once the CI pass, I will add some benchmark results.
Related #671
=> Add mimalloc for shared memory

modules/graph/tools/graph_loader.cc
=> Fixes a argument parsing bug in the vineyard-graph-loader.

modules/graph/test/loaded_arrow_fragment_test.cc
=> Improve the loaded_arrow_fragment_test for better argument parsing and output creation

k8s/main.go, k8s/schedulers/scheduling.go
as titled. Try our best to infer the replicas from the pod's owner references.
Part of #911
=> Infer the job replicas from the pods's ownership references

src/common/util/uuid.h
=> Disable usage of __rdtsc under certain circumstances.

modules/graph/fragment/arrow_fragment_group.cc, src/server/util/kubectl.cc
Fixes the bug along with https://github.com/alibaba/GraphScope/pull/1984.
Related to https://github.com/alibaba/GraphScope/issues/1737
=> Improve the `ConstructFragmentGroup` to accept projected fragments.

src/server/memory/memory.cc, src/server/server/vineyard_server.cc, src/server/util/meta_tree.cc
=> Avoid including the unsealed blobs and the dummy blob into the result of `ListObjects`

src/server/memory/allocator.cc
Try address the failure in CI.
Fixes #943
=> Leave larget space for mimalloc.

src/server/server/vineyard_runner.cc
=> Fixes the compatibility issue with Ubuntu 18.04.

CMakeLists.txt, src/client/client.cc, src/client/client.h, src/common/memory/gpu/unified_memory.cc, src/common/memory/gpu/unified_memory.h, src/common/memory/payload.cc, src/common/memory/payload.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/memory/allocator.h, src/server/memory/gpu/gpuallocator.cc, src/server/memory/gpu/gpuallocator.h, src/server/memory/memory.cc, src/server/memory/memory.h, src/server/server/vineyard_server.h, test/CMakeLists.txt, test/gpumalloc_test.cu, test/runner.py
FEATURE-759, try to enable GPU memory object sharing.  For now,  give a naïve implementation for createGPUBuffer. 
Design Brief
1. Implement GPUBulkStore with the same functionality interface as BulkStore.
2. Implement a GPU memory allocator, for now,  naïve "allocate-on-request" is adopted.
3. Client and Server add gpu-specific session support.
4. Server sends the cudaIpcMemHandle  to client in reply, client open the handle to get access to the shared GPU memory.
New class:
- GPUBulkStore: with the same interface as BulkStore.
- GPUBulkAllocator: with the same interface as BulkAllocator.
- GPUAllocator: GPU memory allocator, it is left for future work.
Main Related class:
- Client: add GPU-specific request …
=> Support GPU `bulkstore` in vineyardd

src/common/memory/gpu/unified_memory.cc, src/common/memory/gpu/unified_memory.h, src/common/memory/memcpy.h, src/common/memory/payload.cc, src/common/memory/payload.h, src/server/async/socket_server.h, src/server/memory/gpu/gpuallocator.cc, src/server/memory/gpu/gpuallocator.h, src/server/util/meta_tree.cc, test/gpumalloc_test.cu
The change was first introduced in https://github.com/v6d-io/v6d/pull/876 and makes the vineyard client not compatible with previous releases.
This pull request revisit some code style issues as well.
N/A
=> Fixes a backwards compatibility issue in payload message.

src/server/util/etcd_launcher.cc
as titled. To avoid potential failure in `getaddrinfo()` inside the etcd-cpp-apiv3 library itself and further throwing misleading error message to users.
N/A
=> Validate the etcd endpoint before feed into the etcd client.

.github/workflows/build-test.yml, src/client/client.cc, src/client/client.h, src/common/memory/payload.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/memory/malloc.cc, src/server/memory/malloc.h, src/server/memory/memory.cc, src/server/memory/memory.h, src/server/server/vineyard_server.cc, test/get_blob_disk_test.cc, test/get_blob_test.cc, test/runner.py
=> Add the interface to create blobs that backed by files on Disk.

.github/workflows/build-compatibility.yml, src/server/util/kubectl.h, src/server/util/proc.h
=> Fixes compatibility build

src/server/memory/usage.h
Fixes CI failure in: https://github.com/sighingnow/v6d/pull/new/ht/fix-dead-lock
Follow-up patch for #971 and addresses issue #970.
Fixes #970
=> Use a recursive mutex to fixes the deadlock failure

.github/workflows/build-test.yml, cmake/BuildHiredis.cmake, cmake/BuildRedisCpp.cmake, modules/basic/ds/arrow.cc, modules/basic/ds/arrow.h, modules/basic/ds/arrow.vineyard-mod, modules/basic/ds/arrow_utils.cc, modules/basic/ds/arrow_utils.h, modules/graph/fragment/arrow_fragment.vineyard-mod, modules/graph/fragment/arrow_fragment_modifier.h, modules/graph/fragment/graph_schema.cc, modules/graph/fragment/graph_schema.h, modules/graph/fragment/property_graph_utils.h, modules/graph/loader/arrow_fragment_loader.h, modules/graph/test/arrow_fragment_from_table_test.cc, modules/graph/test/arrow_fragment_stream_test.cc, modules/graph/test/arrow_fragment_string_test.cc, modules/graph/test/arrow_fragment_test.cc, modules/graph/test/loaded_arrow_fragment_test.cc, modules/graph/test/vertex_map_string_test.cc, modules/graph/test/vertex_map_test.cc, modules/io/io/local_io_adaptor.cc, python/vineyard/core/codegen/cpp.py, src/server/services/meta_service.cc, src/server/services/redis_meta_service.cc, src/server/util/redis_launcher.cc, src/server/util/redis_launcher.h, test/arrow_data_structure_test.cc
as titled. Enable consolidate method on both table and arrow fragment.
N/A
=> Add a consolidate method to merge multiple columns of same type in a table into one

modules/basic/ds/arrow.h, modules/graph/fragment/arrow_fragment_modifier.h, test/arrow_data_structure_test.cc
=> Fixes the typo

thirdparty/wyhash/wyhash.hpp
=> Fixes error under lower version of C++ in wyhash.hpp.

k8s/go.mod, k8s/go.sum
=> Fix dependency of goutils

CMakeLists.txt
`RULE_LAUNCH_COMPILE` won't work when `CMAKE_CXX_COMPILER_LAUNCHER` environment variable is set.
N/A
=> CMake: find and set ccache correctly.

modules/graph/fragment/arrow_fragment.vineyard-mod, modules/graph/fragment/arrow_fragment_base.h
Add `AddEdgeColumns` For ArrowFragment.
Related GraphScope PR [GraphX-Graphscope](https://github.com/alibaba/GraphScope/pull/2004/)
=> Support add edge column for ArrowFragment.

modules/basic/ds/dataframe.cc, modules/basic/ds/tensor.cc, python/vineyard/data/dataframe.py, python/vineyard/data/tensor.py
=> Fixes the construct of global dataframe/tensor to match the semantic of python

thirdparty/wyhash/wyhash.hpp
=> Nested ns declaration is a C++17 extension.

modules/basic/ds/array.vineyard-mod, modules/basic/ds/arrow.vineyard-mod, modules/basic/ds/dataframe.vineyard-mod, modules/basic/ds/hashmap.vineyard-mod, modules/basic/ds/scalar.vineyard-mod, modules/basic/ds/sequence.vineyard-mod, modules/basic/ds/tensor.vineyard-mod, modules/basic/stream/parallel_stream.vineyard-mod, modules/graph/fragment/arrow_fragment.vineyard-mod
=> Syntax highlighting in VIM.

modules/basic/ds/array.vineyard-mod, modules/basic/ds/arrow.vineyard-mod, modules/basic/ds/dataframe.vineyard-mod, modules/basic/ds/hashmap.vineyard-mod, modules/basic/ds/scalar.vineyard-mod, modules/basic/ds/sequence.vineyard-mod, modules/basic/ds/tensor.vineyard-mod, modules/basic/stream/parallel_stream.vineyard-mod, modules/graph/fragment/arrow_fragment.vineyard-mod
=> Fixes the syntax error in comments 

.github/workflows/vineyard-operator.yaml
=> Fix bug in vineyard-operator ci

java/pom.xml, modules/graph/utils/error.h
=> Bump up dependency version to fixes the dependentbot warnings

charts/vineyard-operator/templates/cert.yaml, charts/vineyard-operator/templates/crds.yaml, charts/vineyard-operator/templates/deployment.yaml, charts/vineyard-operator/templates/service.yaml, charts/vineyard-operator/templates/webhooks.yaml, k8s/Makefile, k8s/apis/k8s/v1alpha1/globalobject_types.go, k8s/apis/k8s/v1alpha1/localobject_types.go, k8s/config/certmanager/certificate.yaml, k8s/config/crd/bases/k8s.v6d.io_globalobjects.yaml, k8s/config/crd/bases/k8s.v6d.io_localobjects.yaml, k8s/config/default/kustomization.yaml, k8s/config/manager/manager.yaml, k8s/main.go
The pr is to do the following things:
* Clean the vineyard operator's configuration.
* Add webhook for the vineyard operator helm chart.
* Readjust the limits and required of the controller
=> Clean the vineyard operator's configuration .

python/client.cc, python/vineyard/_vineyard_docs.py, src/client/client_base.cc, src/client/client_base.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h, src/server/util/meta_tree.cc, src/server/util/meta_tree.h, test/name_test.cc
=> Implements "ListNames".

.github/workflows/build-test.yml, src/server/services/etcd_meta_service.cc, src/server/services/etcd_meta_service.h, src/server/services/redis_meta_service.cc, src/server/services/redis_meta_service.h, src/server/util/redis_launcher.cc, src/server/util/redis_launcher.h
Signed-off-by: shihao-thx <shihao@zju.edu.cn>
as titled.
Fixes #715.
=> Share the etcd and redis watcher between sessions

src/server/services/etcd_meta_service.cc, src/server/services/etcd_meta_service.h, src/server/services/redis_meta_service.cc, src/server/services/redis_meta_service.h, src/server/util/redis_launcher.cc, src/server/util/redis_launcher.h
We are on the way for v0.10.0 release and #1007 will be re-applied after that release.
Reverts v6d-io/v6d#1007
=> Revert "Share the etcd and redis watcher between sessions"

charts/vineyard-operator/templates/crds.yaml, charts/vineyard-operator/templates/rbac.yaml, charts/vineyard-operator/templates/webhooks.yaml
- Add new config about new CRD in helm charts.
- Fix the recopy of service.
=> Update helm chart for new CRD

modules/io/python/drivers/io/stream.py, python/vineyard/launcher/script.py
=> Tune the logs when IO driver fails and avoid leak sensitive information in logs

charts/vineyard-operator/templates/crds.yaml
=> Fixes error in vineyard-operator's CRDs

modules/io/python/drivers/io/ssh.sh
=> Source /etc/bash.bashrc as well for Ubuntu 2.04

modules/io/python/drivers/io/adaptors/read_bytes.py, modules/io/python/drivers/io/adaptors/read_orc.py, setup_io.py
=> Fixes the read_bytes.py to adapt to the latest fsspec

.gitleaks.toml, .pre-commit-config.yaml, CONTRIBUTING.rst
Add gitleaks and pre-configured secret patterns.
N/A
=> Add git leaks hooks to this repo

.github/workflows/build-test.yml, CMakeLists.txt, modules/io/python/drivers/io/adaptors/parse_dataframe_to_bytes.py, modules/io/python/drivers/io/adaptors/read_bytes_collection.py, modules/io/python/drivers/io/adaptors/read_orc.py, modules/io/python/drivers/io/adaptors/read_parquet.py, modules/io/python/drivers/io/adaptors/write_bytes.py, modules/io/python/drivers/io/adaptors/write_bytes_collection.py, modules/io/python/drivers/io/adaptors/write_parquet.py, modules/io/python/drivers/io/fsspec_adaptors.py, modules/io/python/drivers/io/stream.py, modules/io/python/drivers/io/tests/test_open.py, python/vineyard/__init__.py, python/vineyard/io/stream.py, python/vineyard/io/utils.py, setup_io.py, test/runner.py
Introduce parquet and orc IO adaptors.
Fixes #1037
=> Enable support for parquet and ORC IO

README.rst, docs/notes/deploy-docker.rst, docs/notes/deploy-kubernetes.rst, docs/notes/vineyard-operator.rst
* Fix the wrong link.
* Adjust Vineyardd Configurtaions Table.
=> Improve vineyard operator doc.

docs/deployment.rst, docs/notes/objects.rst, docs/notes/vineyard-operator.rst
The logic in `vineyard-operator.rst` looks a bit wired. I reorginized the section order and revise some content of "creating a vineyard cluster" to make it more straightforward.
This pull requests fixes some typos as well.
Fixes #1031
=> Revise the vineyard-operator docs: first part.

modules/graph/loader/basic_ev_fragment_loader.h, modules/graph/vertex_map/arrow_local_vertex_map.h, modules/graph/vertex_map/arrow_vertex_map.h
Signed-off-by: siyuan0322 <siyuan0322@gmail.com>
=> Fix local vertex map when adding edges

modules/graph/vertex_map/arrow_local_vertex_map.h
as titled.
N/A, see warning messages in https://github.com/v6d-io/v6d/actions/runs/3467884469/jobs/5793162936
=> Fixes a warning in local vertex map

modules/graph/vertex_map/arrow_local_vertex_map.h
=> Don't continue if error occurs during building the array

modules/io/python/drivers/io/adaptors/read_bytes.py, modules/io/python/drivers/io/adaptors/read_orc.py, modules/io/python/drivers/io/adaptors/read_parquet.py
as titled. The previous implementation is a bit misleading, and cannot support cases where all files has a header row.
N/A
=> Decouple the logic of creating stream and parsing header lines, and strip UTF-8 BOMs.

go.work
To make tools like gopls in vscode easier for developing.
N/A
=> Add a go.work file to incorporate the feature of multi-directory workspace

.github/workflows/build-test.yml, modules/basic/ds/tensor.vineyard-mod, modules/graph/fragment/property_graph_types.h, modules/graph/loader/arrow_fragment_loader.h, modules/malloc/CMakeLists.txt, python/error.cc, python/vineyard/core/builder.py, python/vineyard/data/arrow.py, python/vineyard/data/tests/test_dataframe.py, python/vineyard/data/utils.py, src/client/client.h, src/client/rpc_client.h, src/common/util/status.cc, src/common/util/status.h, test/get_object_test.cc, test/rpc_get_object_test.cc
=> Improve some builders and resolvers.

python/client.cc, python/vineyard/core/resolver.py, python/vineyard/data/tensor.py, src/client/client.cc, src/client/client.h, src/client/client_base.cc, src/common/util/status.h
=> Fixes false-postive when testing if pointer is a "VALID" shared memory pieces

modules/basic/ds/arrow_utils.cc, modules/basic/ds/dataframe.cc, modules/basic/ds/tensor.h, modules/basic/ds/tensor.vineyard-mod, modules/graph/fragment/arrow_fragment.vineyard-mod, python/vineyard/core/codegen/cpp.py, python/vineyard/core/codegen/parsing.py, python/vineyard/data/tensor.py
=> Support string tensors

modules/io/python/drivers/io/stream.py
As titled, now an optional `filetype` argument is used to specify the file type.
Fixes #1103
Part of alibaba/GraphScope#2328
=> Accept a filetype arguments for reading orc/parquet using prefix

.github/workflows/build-test.yml, modules/io/python/drivers/io/stream.py
=> Fixes the dask errors on CI

src/common/util/arrow.h
=> Fixes conditions for adding hash template specialization for string view

modules/basic/ds/arrow.h, modules/basic/ds/arrow_utils.cc, modules/graph/fragment/arrow_fragment_builder_impl.h, modules/graph/fragment/property_graph_types.h, modules/graph/fragment/property_graph_utils.h, modules/graph/fragment/property_graph_utils_impl.h, modules/graph/fragment/property_graph_utils_uint32.cc, modules/graph/fragment/property_graph_utils_uint64.cc, modules/graph/loader/basic_ev_fragment_loader_impl.h, modules/graph/tools/fragment_loader_impl.h, modules/graph/utils/table_pipeline.h, modules/graph/utils/table_shuffler.cc, modules/graph/utils/table_shuffler_impl.h, modules/graph/vertex_map/arrow_local_vertex_map_impl.h, modules/graph/vertex_map/arrow_vertex_map_impl.h
- Fixes some null pointers, empty tables, etc.
- Fixes bugs in CSR neighbor ID generation.
N/A
=> Fixes bugs in fragment loader for corner cases

.gitmodules, README.rst, modules/basic/ds/hashmap.vineyard-mod, modules/graph/CMakeLists.txt, modules/graph/loader/arrow_fragment_loader_impl.h, modules/graph/loader/basic_ev_fragment_loader.h, modules/graph/loader/basic_ev_fragment_loader_impl.h, modules/graph/loader/fragment_loader_utils.cc, modules/graph/loader/fragment_loader_utils.h, modules/graph/utils/table_shuffler.cc, modules/graph/vertex_map/arrow_local_vertex_map.h, modules/graph/vertex_map/arrow_local_vertex_map_impl.h, modules/io/io/local_io_adaptor.cc, requirements-dev.txt, thirdparty/cityhash/cityhash.hpp
- Introduce the libcuckoo as the concurrent hashmap
- Optimize the preprocess steps to build vtable from etable
- Optimize the finalizing process of local vertexmap for acceleration.
=> Optimizing fragment loader for local vertex map

.github/workflows/vineyard-operator.yaml, charts/vineyard-operator/templates/backup-crd.yaml, charts/vineyard-operator/templates/manager-rbac.yaml, charts/vineyard-operator/templates/mutating-webhook-configuration.yaml, charts/vineyard-operator/templates/recover-crd.yaml, charts/vineyard-operator/templates/validating-webhook-configuration.yaml, charts/vineyard-operator/templates/vineyardd-crd.yaml
=> Generate helm chart automatically

modules/io/python/drivers/io/adaptors/parse_bytes_to_dataframe.py, modules/io/python/drivers/io/adaptors/read_orc.py, modules/io/python/drivers/io/adaptors/read_parquet.py, python/vineyard/core/builder.py
=> Make sure chunks are persisted in IO readers

modules/io/python/drivers/io/kube_ssh.sh
=> Add container name as a option to kube_ssh.sh

docs/notes/how-to-use-vineyard-operator.rst
As titled. If the blog is ok, we need to discuss where to put it.
=> Add vineyard operator blog

k8s/pkg/schedulers/common.go
=> Add all globalobjects and localobjects created by one job to the relevant configmap

.github/workflows/build-vineyardd-and-wheels-linux.yaml, docker/pypa/Dockerfile.manylinux1, docker/pypa/Dockerfile.manylinux1-wheel, modules/basic/ds/dataframe.vineyard-mod, python/vineyard/contrib/ml/mxnet.py, python/vineyard/contrib/ml/pytorch.py, python/vineyard/contrib/ml/tensorflow.py, python/vineyard/data/dataframe.py
as titled. Otherwise we would treat all chunks as the `[0, 0]` chunks and causing errors when processing.
Fixes #1155
=> Use -1 to indicates unknown chunk index inside a global dataframes

docs/notes/how-to-use-vineyard-operator.rst
=> Add the missing code block in the vineyard operator doc

k8s/README.md
As titled. It will benefit those who are not familiar with helm.
=> Add commands for remote installation of vineyard operator

.github/workflows/build-compatibility.yml, .github/workflows/build-vineyardd-and-wheels-macos.yaml, modules/io/python/drivers/io/adaptors/dump_dataframe.py, modules/io/python/drivers/io/adaptors/parse_bytes_to_dataframe.py, modules/io/python/drivers/io/adaptors/parse_dataframe_to_bytes.py, modules/io/python/drivers/io/stream.py, python/client.cc, python/vineyard/io/stream.py, setup.cfg, setup.cfg.in, src/client/client_base.cc, src/client/client_base.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/memory/stream_store.cc
- Add a `dropstream` method to vineyardd and client
- Add a finalizer in stream.py when finished consuming.
Fixes #1150
=> Drop the intermediate stream when ensure it has finished 

.github/workflows/build-test.yml, thirdparty/wyhash/wyhash.hpp
<version> header is part of C++20, whereas the include directive checks for C++17
See also https://en.cppreference.com/w/cpp/header/version
N/A
=> <version> is part of c++20

charts/vineyard-operator/templates/vineyardd-crd.yaml, docs/notes/vineyard-operator.rst, k8s/apis/k8s/v1alpha1/vineyardd_types.go, k8s/config/crd/bases/k8s.v6d.io_vineyardds.yaml, k8s/config/manager/kustomization.yaml, k8s/controllers/k8s/operation_controller.go, k8s/pkg/operation/assembly.go, k8s/pkg/operation/repartition.go, k8s/pkg/templates/operation/dask-repartition.yaml, k8s/pkg/templates/operation/distributed-assembly-job.yaml, k8s/pkg/templates/operation/local-assembly-job.yaml, k8s/test/e2e/Makefile, k8s/test/e2e/assembly/distributed-assembly-e2e.yaml, k8s/test/e2e/vineyardd.yaml
* Support configuring the operation image in the vineyardd CR.
* Update the relevant doc.
* Generate the corresponding vineyard operator chart.
=> Support configuring the operatiom image in the vineyardd CR and update relevant doc

.github/workflows/build-archlinux-latest.yml, .github/workflows/build-centos-latest.yaml, .github/workflows/build-compatibility.yml, .github/workflows/build-test.yml, .github/workflows/docs.yaml, python/client.cc, python/vineyard/_vineyard_docs.py, src/client/client.cc, src/client/client.h, src/client/rpc_client.cc, src/client/rpc_client.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/ipc_server.cc, src/server/async/rpc_server.cc, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h, src/server/util/meta_tree.cc, src/server/util/proc.cc, src/server/util/proc.h, src/server/util/spec_resolvers.cc, test/auth_test.cc, test/compressor_test.cc, test/io_test.cc
Description
-----------
A standard `.htpasswd` file can be used to providing the authentication information for vineyardd. The basic usage of `htpasswd` can be found at https://httpd.apache.org/docs/2.4/programs/htpasswd.html
Fixes #1072
=> Enable authentication using htpasswd

k8s/controllers/k8s/sidecar_controller.go, k8s/controllers/k8s/vineyardd_controller.go, k8s/pkg/templates/etcd/etcd.yaml
=> Replace the etcd image with vineyardd image

.github/workflows/docs.yaml
Refer to: https://github.com/alibaba/GraphScope/blob/main/.github/workflows/docs.yml
=> Update the comments after preview the generated docs to netlify

modules/graph/CMakeLists.txt, modules/graph/loader/basic_ev_fragment_loader_impl.h, modules/graph/loader/fragment_loader_utils.cc, python/core.cc, python/vineyard/core/codegen/cpp.py, src/client/client_base.cc, src/client/ds/object_meta.cc, src/client/ds/object_meta.h
- Fixes some warnings about non-checked return
- Fixes the code generation about `AddKeyValue` for `vineyard::String`.
=> Fixes some compilation errors under latest clang

modules/basic/ds/dataframe.cc, modules/basic/ds/dataframe.h, modules/basic/ds/tensor.cc, modules/basic/ds/tensor.h, modules/graph/loader/arrow_fragment_loader.cc, src/client/client.cc, src/client/ds/collection.h, src/server/memory/usage.h, test/global_object_test.cc, test/runner.py
=> Refine collection API and tensor/dataframe APIs

CMakeLists.txt, modules/basic/ds/arrow.cc, modules/basic/ds/arrow.h, modules/basic/ds/arrow.vineyard-mod, modules/basic/ds/arrow_utils.cc, modules/basic/ds/arrow_utils.h, modules/basic/ds/dataframe.cc, modules/basic/ds/dataframe.h, modules/basic/ds/tensor.cc, modules/basic/ds/tensor.h, python/vineyard/core/codegen/cpp.py, src/client/ds/collection.h, src/client/ds/i_object.h, test/arrow_data_structure_test.cc, test/release_test.cc
=> Implements `vineyard::Table` using the Collection API for simplication

k8s/go.mod, k8s/go.sum
As titled. Introduced in #1199.
=> Fix kubernetes ci errors

python/client.cc, python/core.cc, src/client/client_base.cc, src/client/client_base.h, src/client/ds/object_meta.cc, src/client/ds/object_meta.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h, test/object_meta_test.cc
=> Add labels support and APIs on client

.github/workflows/build-test.yml, CMakeLists.txt, modules/malloc/mimalloc_allocator.cc, modules/malloc/mimalloc_allocator.h, python/vineyard/conftest.py, requirements-dev.txt, src/common/memory/mimalloc.h, src/server/memory/dlmalloc.cc, src/server/memory/dlmalloc.h, src/server/memory/mimalloc.cc, src/server/memory/mimalloc.h, src/server/server/vineyard_server.cc, src/server/util/compressor.cc, test/mimalloc_test.cc, test/runner.py, test/vineyard-cmake-example/CMakeLists.txt, vineyard-config.in.cmake
Thanks to the new feature from mimalloc: https://github.com/microsoft/mimalloc/issues/617
- Resolves #1205.
- Resolves #1206 as well.
- Addresses a dependency resolving issue in `vineyard-config.in.cmake` as well, thanks @siyuan0322
=> Simplify mimalloc support to support multiple allocators in the same process

CPPLINT.cfg, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/memory/memory.cc, src/server/memory/usage.h
Unify the tag definitions to avoid possible typos and errors.
=> Unify the request/reply tags in protocol.{h,cc}

k8s/.gitignore, k8s/Makefile, k8s/cmd/commands/flags/global_flags.go, k8s/cmd/commands/flags/vineyardd_flags.go, k8s/cmd/commands/manager/manager.go, k8s/cmd/commands/util/client.go, k8s/cmd/commands/util/parse.go, k8s/cmd/commands/util/usage/json.go, k8s/cmd/commands/util/usage/types.go, k8s/cmd/main.go, k8s/go.mod, k8s/go.sum, k8s/pkg/webhook/operation/operation_webhook.go, k8s/pkg/webhook/scheduling/scheduling-webhook.go, k8s/pkg/webhook/sidecar/sidecar_webhook.go
See:
- `RemoveVersionFlag()`
- `k8s/cmd/commands/util/usage/{types.go,json.go}`
=> Fixes the implicit --version issue and export usage in JSON format

k8s/cmd/commands/util/usage/types.go, python/vineyard/.gitignore, python/vineyard/__init__.py, python/vineyard/ctl.py, python/vineyard/deploy/_cobra.py, python/vineyard/deploy/ctl.py, python/vineyard/deploy/kubernetes.py, python/vineyard/deploy/utils.py, requirements.txt, setup.py
Based on usage exported in https://github.com/v6d-io/v6d/pull/1215
After this pull request, we have:
- a command line util that can be used as
```bash
✗  python3 -m vineyard.ctl --help
vineyardctl is the command-line tool for working with the Vineyard Operator.
It supports creating, deleting and checking status of Vineyard Operator. It also
supports managing the vineyard relevant components such as vineyardd and pluggable
drivers
Usage:
vineyardctl [command]
Available Commands:
create      Create the vineyard jobs on kubernetes
delete      Delete the vineyard components on kubernetes
deploy      Deploy the vineyard components on kubernetes
help        Help about any command
manager     Start the manager of vineyard operator
schedule …
```
=> Generate the python wrapper automatically

CMakeLists.txt, python/vineyard/data/arrow.py, src/common/util/json.h
=> Make sure use bundled nlohmann-json library

charts/vineyard-operator/templates/backup-crd.yaml, charts/vineyard-operator/templates/deployment.yaml, charts/vineyard-operator/templates/globalobject-crd.yaml, charts/vineyard-operator/templates/localobject-crd.yaml, charts/vineyard-operator/templates/operation-crd.yaml, charts/vineyard-operator/templates/recover-crd.yaml, charts/vineyard-operator/templates/sidecar-crd.yaml, charts/vineyard-operator/templates/vineyardd-crd.yaml, k8s/cmd/commands/delete/delete.go, k8s/cmd/commands/deploy/deploy.go, k8s/cmd/commands/schedule/schedule.go, k8s/go.mod, k8s/go.sum
* Generate the helm chart for the updated CRD API.
* Fix the util package importing errors.
* Delete the useless golang package.
=> Generate the helm chart and fix the package importing errors

k8s/go.mod, python/vineyard/deploy/ctl.py
Exclude the `gen_doc` option from Python API.
=> Improve the python wrapper options

k8s/cmd/commands/create/create.go, k8s/cmd/commands/create/create_backup.go, k8s/cmd/commands/create/create_operation.go, k8s/cmd/commands/create/create_recover.go, k8s/cmd/commands/delete/delete_certmanager.go, k8s/cmd/commands/delete/delete_vineyard_cluster.go, k8s/cmd/commands/deploy/deploy.go, k8s/cmd/commands/deploy/deploy_certmanager.go, k8s/cmd/commands/deploy/deploy_operator.go, k8s/cmd/commands/deploy/deploy_vineyard_cluster.go, k8s/cmd/commands/deploy/deploy_vineyard_deployment.go, k8s/cmd/commands/deploy/deploy_vineyardd.go, k8s/cmd/commands/manager/manager.go, k8s/cmd/commands/schedule/schedule.go, k8s/cmd/commands/schedule/schedule_workload.go, k8s/cmd/commands/sidecar/inject.go, k8s/cmd/commands/util/format.go, k8s/cmd/main.go
Fix errors in https://github.com/v6d-io/v6d/pull/1217#issuecomment-1453015584
=> Format the description of command for vineyardctl

k8s/Makefile, k8s/cmd/commands/schedule/schedule_workload.go, k8s/pkg/log/log.go, python/vineyard/deploy/_cobra.py
Fixes issue about argument parsing and subcommand name as well.
=> Allowing capture the output of certain command

k8s/Makefile, k8s/cmd/commands/deploy/deploy_operator.go
As titled. 
Fixes https://github.com/v6d-io/v6d/issues/1240.
=> Ignore the output of checking whether the command exists

k8s/cmd/commands/deploy/deploy_vineyardd.go, k8s/cmd/commands/schedule/schedule.go, k8s/cmd/commands/schedule/schedule_workload.go, k8s/cmd/references.md, k8s/config/manager/kustomization.yaml, k8s/pkg/schedulers/common.go, k8s/pkg/templates/vineyardd/deployment.yaml
=> Update the podAffinity to support injecting workload to different vineyard cluster and improve the command description

.github/workflows/vineyard-operator.yaml, k8s/Makefile, k8s/cmd/commands/deploy/deploy_operator.go
* Add eval in the phony of Makefile to assign the value.
* Add golang lint in the makefile.
=> Fix some errors in the k8s Makefile and add the golint action to speed up linting

modules/io/python/drivers/io/fsspec_adaptors.py
See upstream changes in https://github.com/fsspec/filesystem_spec/commit/45de5b509bacf8a62d99848bb2361cc78733ad09
Fixes https://github.com/alibaba/GraphScope/issues/2507
=> Adapt to recent fsspec changes

docs/notes/developers/faq.rst
=> Fix the link error and wrong typography

modules/io/python/drivers/io/adaptors/read_bytes.py
assign total_size to the last proc
Fixes #1261
=> fix data missing

modules/graph/fragment/graph_schema.cc, modules/graph/fragment/graph_schema.h, modules/graph/tools/graph_loader.cc, modules/graph/tools/graph_loader.h
=> Fixes the property id indexing in schema normalization

.cirrus.yml, .github/workflows/vineyard-operator.yaml, docker/Dockerfile.vineyard-python-dev, k8s/Makefile, misc/release-docker.sh
=> Fixes macos M1 CI conditions and the release-docker script

modules/basic/stream/dataframe_stream.cc, modules/basic/stream/recordbatch_stream.cc, modules/graph/loader/arrow_fragment_loader.cc, modules/graph/loader/arrow_fragment_loader_impl.h, modules/io/python/drivers/io/adaptors/read_bytes.py, modules/io/python/drivers/io/kube_ssh.sh
- Allow parse options from URI directly
- Minor fix to kube_ssh.sh
Fixes N/A
=> Allow pass options from uri and load fragments from streams

docs/tutorials/kubernetes/ml-pipeline-mars-pytorch.rst, docs/tutorials/kubernetes/using-vineyard-operator.rst
As titled.
A supplement for #1280
=> Add some notes about indicating to users the required RBAC roles before creating vineyard resources

k8s/cmd/commands/deploy/deploy_vineyardd.go, k8s/cmd/commands/manager/manager.go, k8s/go.mod, k8s/go.sum, k8s/pkg/schedulers/scheduler_outside_cluster.go, k8s/pkg/webhook/scheduling/scheduling-webhook.go, k8s/test/e2e/Makefile, k8s/test/hack/prepare-e2e.sh
=> Fix deploying vineyard cluster via vineyardctl deploy vineyard-cluster occasionally fail in ci 

k8s/README.md
=> Add the short-term milestones and the long-term milestones for vineyard operator

src/server/server/vineyard_server.cc
for better user experience and fewer exceptions.
=> Ignore non-exists objects when during deletion

.github/workflows/build-test-graph.yml, .github/workflows/build-test.yml, benchmark/alloc_test/bench_allocator.cpp, docker/dev/build_scripts/install-miscs.sh, modules/graph/fragment/arrow_fragment.vineyard-mod, modules/graph/fragment/arrow_fragment_builder_impl.h, modules/graph/fragment/arrow_fragment_impl.h, modules/graph/fragment/gar_fragment_builder_impl.h, modules/graph/fragment/graph_schema.cc, modules/graph/fragment/graph_schema.h, modules/graph/loader/basic_ev_fragment_loader_impl.h, modules/graph/loader/gar_fragment_loader_impl.h, modules/graph/vertex_map/arrow_local_vertex_map_impl.h, modules/graph/vertex_map/arrow_vertex_map_impl.h, modules/graph/writer/arrow_fragment_writer_impl.h, src/common/util/arrow.h, src/common/util/blocking_queue.h
Just code lint fix and small hard-code var's fix
=> Small code improvement of graph

README.rst, charts/vineyard-operator/README.md, charts/vineyard-operator/templates/NOTES.txt, docs/notes/cloud-native/vineyard-operator.rst, docs/tutorials/kubernetes/ml-pipeline-mars-pytorch.rst, docs/tutorials/kubernetes/using-vineyard-operator.rst, k8s/README.md
=> Fix some dead links of vineyard operator doc

python/vineyard/data/arrow.py, python/vineyard/data/tests/test_arrow.py, requirements-extra.txt, setup.py
=> Integration with polars dataframe

docker/Dockerfile.vineyard-python-dev, k8s/Makefile, k8s/controllers/k8s/vineyardd_controller.go, k8s/pkg/templates/vineyardd/deployment.yaml
=> Add --load for building the image of vineyard operator to avoid the inconsistent image.

charts/vineyard-operator/templates/sidecar-crd.yaml, charts/vineyard-operator/templates/vineyardd-crd.yaml
=> Update the helm chart for the latest vineyard operator

docs/notes/cloud-native/vineyard-operator.rst, docs/tutorials/kubernetes/using-vineyard-operator.rst
=> Fix the wrong indents of yaml files.

modules/graph/fragment/arrow_fragment.vineyard-mod, modules/graph/fragment/arrow_fragment_builder_impl.h, modules/graph/fragment/gar_fragment_builder_impl.h
See also: https://github.com/v6d-io/v6d/pull/1314
=> Revert the field name to backwards compatibility.

modules/basic/ds/arrow.cc, modules/basic/ds/arrow_shim/concatenate.cc
See also: 
- https://github.com/Homebrew/homebrew-core/pull/129859
- https://github.com/apache/arrow/pull/33608
- https://github.com/apache/arrow/pull/33641
=> Adapt to arrow-11/12 (VisitTypeInline & Run-End encoded data)

src/common/util/json.h, src/common/util/macros.h, src/server/server/vineyard_server.cc
Include more information in the error message when there are errors in metadata to help debugging.
=> Print more detail logs when there are unexpected errors in metadata

.github/workflows/vineyard-operator.yaml
=> Dump the logs under the namespace which match the wildcard

modules/graph/loader/basic_ev_fragment_loader_impl.h, modules/graph/utils/table_pipeline.h, modules/graph/utils/table_shuffler.cc, modules/graph/utils/table_shuffler.h, modules/graph/utils/table_shuffler_impl.h
- https://github.com/alibaba/GraphScope/issues/2693
=> Report error when edge src/dst not present in vertices

k8s/cmd/commands/deploy/deploy_vineyard_deployment.go
* Wait the vineyard deployment for ready.
* Apply the vineyard deployment at last to reduce the time of waiting for the etcd cluster service ready(the wait-for-it script).
=> Wait the vineyard deployment for ready while using vineyardctl deploy vineyard-deployment

.github/workflows/vineyard-operator.yaml, CMakeLists.txt, python/client.cc, python/vineyard/core/tests/test_rpc_client.py, python/vineyard/data/arrow.py, python/vineyard/data/base.py, python/vineyard/data/default.py, python/vineyard/data/utils.py
=> Improve the error message about misuses of IPC/RPC client

.github/workflows/vineyard-operator.yaml, k8s/cmd/README.md, k8s/cmd/commands/create/create_backup.go, k8s/cmd/commands/create/create_recover.go, k8s/cmd/commands/delete/delete_recover.go, k8s/cmd/commands/delete/delete_vineyard_deployment.go, k8s/cmd/commands/deploy/deploy.go, k8s/cmd/commands/deploy/deploy_backup_job.go, k8s/cmd/commands/deploy/deploy_recover_job.go, k8s/cmd/commands/deploy/deploy_vineyard_deployment.go, k8s/cmd/commands/flags/backup_flags.go, k8s/cmd/commands/flags/recover_flags.go, k8s/cmd/commands/sidecar/inject.go, k8s/cmd/commands/util/client.go, k8s/cmd/commands/util/manifests.go, k8s/cmd/commands/util/template.go, k8s/controllers/k8s/backup_controller.go, k8s/controllers/k8s/recover_controller.go, k8s/pkg/templates/backup/job.yaml, k8s/pkg/templates/backup/role-binding.yaml, k8s/pkg/templates/backup/role.yaml, k8s/pkg/templates/recover/job.yaml, k8s/pkg/templates/recover/role-binding.yaml, k8s/pkg/templates/recover/role.yaml, k8s/test/e2e/Makefile, k8s/test/e2e/deploy-raw-backup-and-recover/e2e.yaml, k8s/test/e2e/failover-demo/backup.py, k8s/test/e2e/failover-demo/recover.py, k8s/test/e2e/failover/e2e.yaml, k8s/test/e2e/verify/distributed-object-values.yaml
* Add the subcommand 'vineyardctl deploy backup-job' for deploying a raw backup job of vineyard cluster.
* Add the subcommand 'vineyardctl deploy recover-job' for deploying a raw recover job of vineyard cluster.
* Add the relevant e2e test and update the doc.
Fixes #1322
=> Support deploying a raw backup and recover job for vineyard cluster via vineyardctl

.github/workflows/vineyard-operator.yaml, .stoat/config.yaml, k8s/test/e2e/deploy-raw-backup-and-recover/e2e.yaml
As titled. Wait for testing here.
=> Upload the e2e test of deploying raw backup and recover logs to stoat dev

.gitmodules, CMakeLists.txt, README.rst, modules/basic/ds/arrow.cc, modules/basic/ds/dataframe.cc, modules/basic/ds/tensor.cc, modules/basic/stream/parallel_stream.cc, src/common/util/typename.h
=> Remove the ctti dependency

modules/graph/fragment/arrow_fragment_builder_impl.h, modules/graph/fragment/gar_fragment_builder_impl.h, modules/graph/loader/fragment_loader_utils.cc, modules/graph/loader/gar_fragment_loader_impl.h, modules/graph/writer/arrow_fragment_writer_impl.h
Signed-off-by: acezen <qiaozi.zwb@alibaba-inc.com>
Committed-by: acezen from Dev container
- add write vertices num to FragmentWriter;
- Some LOG revise
=> Add write vertices num to FragmentWriter to adapt the latest GraphAr format

k8s/pkg/templates/sidecar/injection-template.yaml, k8s/pkg/templates/vineyardd/deployment.yaml
=> Fix the errors of templates when set the volume path of vineyard socket

k8s/cmd/commands/sidecar/inject.go, k8s/pkg/config/labels/labels.go, k8s/pkg/injector/sidecar_injector.go
=> Add the labelselector for injected resources to bind the vineyard rpc service

k8s/cmd/commands/deploy/deploy_backup_job.go, k8s/cmd/commands/deploy/deploy_recover_job.go, k8s/cmd/commands/util/template.go, k8s/controllers/k8s/backup_controller.go, k8s/controllers/k8s/recover_controller.go, k8s/pkg/templates/backup/job.yaml, k8s/pkg/templates/recover/job.yaml, k8s/test/e2e/deploy-raw-backup-and-recover/e2e.yaml
=> Support to deploy the backup and recover job with an existing pvc

python/vineyard/drivers/io/adaptors/deserializer.py, python/vineyard/drivers/io/adaptors/read_bytes_collection.py, python/vineyard/drivers/io/adaptors/serializer.py, python/vineyard/drivers/io/adaptors/write_bytes_collection.py, python/vineyard/drivers/io/stream.py, python/vineyard/io/utils.py
Resolves #1406, to control the peak memory usage during serialization.
=> Add an optional argument to control the parallelism of serailizer/deserializer

java/hive/README.rst, java/hive/pom.xml, java/hive/src/main/java/io/v6d/hadoop/fs/FileSystem.java, java/hive/src/main/java/io/v6d/hadoop/fs/VineyardFileSystem.java, java/hive/src/main/java/io/v6d/hive/ql/io/VineyardInputFormat.java, java/hive/src/main/java/io/v6d/hive/ql/io/VineyardOutputFormat.java, java/hive/src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem, java/hive/src/test/resources/logback.xml, java/pom.xml
Part of #1420, registering vineyard input/output formats and filesystem implementation to hadoop/hive.
=> Add the framework for hive integration

python/vineyard/contrib/kedro/plugins/catalog.py
=> Check in the missing catalog.py file

python/vineyard/core/tests/test_rpc_client.py, src/client/rpc_client.cc, src/server/util/remote.cc
=> Fixes creating remote blobs when there are trailing 0-sized chunks

src/client/rpc_client.cc, src/server/async/socket_server.cc, src/server/async/socket_server.h
=> Fixes remote blob creation error when OOM

.github/workflows/docs.yaml
See also https://github.com/alibaba/GraphScope/pull/2941 and https://github.com/alibaba/GraphScope/pull/2943.
=> Fixes the pull_request_target usage to avoid the secret leak issue.

k8s/go.mod, k8s/test/hack/build-kind-cluster-with-local-registry.sh, python/vineyard/contrib/kedro/benchmark/aws-s3/src/requirements.txt, python/vineyard/contrib/kedro/benchmark/minio-s3/src/requirements.txt, python/vineyard/contrib/kedro/benchmark/vineyard/src/requirements.txt
As titled.
Fixes the security issues:
- https://github.com/v6d-io/v6d/security/dependabot/42
- https://github.com/v6d-io/v6d/security/dependabot/43
- https://github.com/v6d-io/v6d/security/dependabot/44
- https://github.com/v6d-io/v6d/security/dependabot/45
=> Bump up the k8s to v1.25.0 and address the security issues

docs/notes/kedro-integration-performance.rst, python/vineyard/contrib/kedro/benchmark/aws-s3/Dockerfile, python/vineyard/contrib/kedro/benchmark/aws-s3/argo-aws-s3-benchmark.yml, python/vineyard/contrib/kedro/benchmark/aws-s3/conf/base/catalog.yml, python/vineyard/contrib/kedro/benchmark/aws-s3/conf/local/credentials.yml, python/vineyard/contrib/kedro/benchmark/minio-s3/Dockerfile, python/vineyard/contrib/kedro/benchmark/minio-s3/argo-minio-s3-benchmark.yml, python/vineyard/contrib/kedro/benchmark/minio-s3/conf/local/credentials.yml, python/vineyard/contrib/kedro/benchmark/minio-s3/minio-dev.yaml, python/vineyard/contrib/kedro/benchmark/vineyard/argo-vineyard-benchmark.yml
* Install the latest MinIO cluster.
* Update the performance report with the latest vineyard.
=> Update the kedro integration performance report.

docs/_static/css/index.css, docs/_templates/index.html
I noticed some flaky behaviors on the website.
This is a follow-up PR to fix all of them
Relates to #1449
=> Website: Tiny UI Improvements

python/vineyard/data/tests/test_velox.py, python/vineyard/data/velox.py
=> Add velox integration on arrays, dataframes and tables

docs/notes/cloud-native/vineyard-operator.rst, docs/notes/developers/build-from-source.rst
* Add the installation doc of vineyardctl.
* Fix the typos of vineyard operator doc.
Fixes the second task of #1478.
=> Add the installation doc of vineyardctl and fix typos of vineyard operator doc

modules/basic/ds/arrow_utils.cc, modules/basic/ds/arrow_utils.h, modules/graph/loader/arrow_fragment_loader.cc
=> Unify table/batch schemas when reading chunks from vineyard streams

.github/workflows/build-vineyardd-and-wheels-linux.yaml, .github/workflows/build-vineyardd-and-wheels-macos.yaml
As titled. Fix the error while releasing v0.16.2
=> Add the missing extract tag step for release vineyardctl CI

src/common/util/json.h, src/common/util/uuid.h, src/server/server/vineyard_server.cc, src/server/services/meta_service.h, src/server/util/meta_tree.cc
Random number will yields duplicate object ID.
Fixes #1509
=> Fixes object ID generation on arm platform

python/core.cc, python/pybind11_docs.cc, python/pybind11_docs.h, src/client/client.cc, src/client/client.h, src/client/ds/blob.cc, src/client/ds/blob.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/memory/memory.cc, src/server/memory/memory.h, test/get_blob_test.cc
=> Implements a shrink API on blob to allow resize blob builder

.github/workflows/vineyard-operator.yaml, .stoat/config.yaml, k8s/cmd/README.md, k8s/cmd/commands/client/ls_metadatas.go, k8s/cmd/commands/flags/scheduler_workflow_flags.go, k8s/cmd/commands/schedule/schedule.go, k8s/cmd/commands/schedule/schedule_workflow.go, k8s/cmd/commands/schedule/schedule_workload.go, k8s/cmd/commands/sidecar/inject.go, k8s/cmd/commands/util/workload.go, k8s/pkg/injector/sidecar_injector.go, k8s/pkg/schedulers/scheduler_inside_cluster.go, k8s/pkg/schedulers/scheduler_outside_cluster.go, k8s/pkg/schedulers/scheduling_strategy.go, k8s/pkg/webhook/scheduling/scheduling-webhook.go, k8s/test/e2e/Makefile, k8s/test/e2e/schedule-workflow-without-crd-demo/test.yaml, k8s/test/e2e/schedule-workflow-without-crd/e2e.yaml
=> Use the golang sdk for tracking chunks for best-effort scheduling and add the relevant e2e test

src/server/memory/malloc.cc
Fixes comment https://github.com/v6d-io/v6d/issues/141#issuecomment-1675590455
=> Support WSL1 support where memfd_create returns `ENOSYS (function not implemented)`.

modules/graph/fragment/property_graph_utils_impl.h
=> Fixes varint encoding: use a special buffer for first 1k encoding to avoid value overwrite issue

.github/workflows/vineyard-operator.yaml, k8s/config/manager/manager.yaml, k8s/pkg/schedulers/scheduler_inside_cluster.go, k8s/pkg/schedulers/scheduling.go, k8s/pkg/schedulers/scheduling_strategy.go, k8s/test/e2e/vineyardctl/e2e.yaml, k8s/test/e2e/workflow-demo/job1.py, k8s/test/e2e/workflow-demo/job2.py, k8s/test/e2e/workflow-demo/workflow-job1.yaml, k8s/test/e2e/workflow-demo/workflow-job2.yaml, k8s/test/e2e/workflow/e2e.yaml
We found the vineyardctl e2e test always failed when we committed the PR to the main branch, the pr is to debug and fix it
=> Fix the vineyardctl e2e test errors and update the log package of vineyard scheduler

rust/Cargo.toml, rust/README.md, rust/vineyard-datafusion/Cargo.toml, rust/vineyard-datafusion/src/ds/dataframe.rs, rust/vineyard-datafusion/src/ds/dataframe_test.rs, rust/vineyard-datafusion/src/ds/mod.rs, rust/vineyard-datafusion/src/lib.rs, rust/vineyard-polars/src/ds/dataframe.rs, rust/vineyard/Cargo.toml, rust/vineyard/src/ds/dataframe.rs
=> Add rust integration with apache/arrow-datafusion

java/core/CMakeLists.txt, java/core/src/main/cpp/ffi/ffi.cc, java/core/src/main/java/com/google/common/base/StopwatchContext.java, java/core/src/main/java/io/v6d/core/client/Client.java, java/core/src/main/java/io/v6d/core/client/Context.java, java/core/src/main/java/io/v6d/core/client/IPCClient.java, java/core/src/main/java/io/v6d/core/client/ds/ObjectMeta.java, java/core/src/main/java/io/v6d/core/common/util/Protocol.java, java/core/src/main/java/io/v6d/core/common/util/VineyardException.java, java/core/src/test/java/io/v6d/core/client/IPCClientTest.java, java/core/src/test/java/io/v6d/core/client/ds/StringObject.java, java/core/src/test/java/io/v6d/core/client/ds/StringObjectBuilder.java, java/core/src/test/java/io/v6d/core/client/ds/StringObjectResolver.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/Arrow.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/BooleanArrayBuilder.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/BufferBuilder.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/DoubleArrayBuilder.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/FloatArrayBuilder.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/Int32ArrayBuilder.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/Int64ArrayBuilder.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/LargeStringArray.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/LargeStringArrayBuilder.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/NullArrayBuilder.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/RecordBatch.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/RecordBatchBuilder.java, java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/Table.java, java/modules/basic/src/main/java/io/v6d/modules/basic/columnar/ColumnarDataBuilder.java, java/modules/basic/src/main/java/io/v6d/modules/basic/dataframe/DataFrame.java, java/modules/basic/src/test/java/io/v6d/modules/basic/arrow/ArrowTest.java, java/pom.xml
- Use singletons to manage vineyard IPCClient.
- Use google watch tools to monitor performance.
- Fix bug that VineyardBuffer will not seal blob when the seal function is called.
- Support shrink buffer.
- Refactor the implementation of StringObject. And modify the apache-arrow compatibility layer implementation.
=> Enhance java sdk.(Add features and fix bugs).

src/common/util/json.h, src/server/async/socket_server.cc, src/server/memory/malloc.cc, src/server/server/vineyard_server.cc
=> Fixes using names that contains the slash symbol

java/core/src/main/java/io/v6d/core/client/Client.java, java/core/src/main/java/io/v6d/core/client/IPCClient.java, java/core/src/main/java/io/v6d/core/common/util/Protocol.java
=> Add list object name function for java sdk.

java/hive/README.rst, java/hive/conf/hive-site.xml, java/hive/src/main/java/io/v6d/hadoop/fs/FileSystem.java, java/hive/src/main/java/io/v6d/hive/ql/io/VineyardInputFormat.java
Fix jimfs will throw exception when rename a dir.
Fix VineyardInputFormat wil throw exception when select an empty table.
- Set default storage and file format.
- Fix jimfs will throw exception when rename a dir.
- Fix VineyardInputFormat wil throw exception when select an empty table.
- Update readme.
=> Fix bugs of hive module and modify some configurations.

.github/workflows/build-vineyardd-and-wheels-linux.yaml, .github/workflows/build-vineyardd-and-wheels-macos.yaml, k8s/Makefile
=> use upx to prune vineyardctl binary size

modules/graph/fragment/arrow_fragment.vineyard-mod
=> Fixes the GetFragId API: should be vid_t

docs/tutorials/kubernetes/efficient-data-sharing-in-kubeflow-with-vineyard-csi-driver.rst
=> Improve the csi driver tutorial

docs/tutorials/kubernetes/efficient-data-sharing-in-kubeflow-with-vineyard-csi-driver.rst, k8s/cmd/README.md, k8s/cmd/commands/flags/csidriver_flags.go, k8s/pkg/templates/csidriver/daemonset.yaml, k8s/pkg/templates/csidriver/deployment.yaml
* Improve the doc.
* Change the image of Vineyard CSI Driver to `vineyard-operator` by default.
* Fix the csidriver template errors.
=> Improve the doc and fix some errors in the `vineyardctl create csidriver` API

modules/graph/fragment/arrow_fragment_impl.h, modules/graph/loader/arrow_fragment_loader_impl.h, modules/graph/tools/fragment_loader_impl.h, modules/graph/vertex_map/arrow_vertex_map_impl.h
=> Remove build warnings for graph part.

modules/graph/fragment/arrow_fragment_builder_impl.h, modules/graph/vertex_map/arrow_vertex_map_impl.h
Small fixes of graph's incremental update
=> Fix graph's incremental update

.github/workflows/build-test-graph.yml, .github/workflows/build-test.yml, .github/workflows/docs.yaml, modules/graph/loader/gar_fragment_loader_impl.h
Signed-off-by: aceze <qiaozi.zwb@alibaba-inc.com>
Committed-by: aceze from Dev container
as title
=> [GraphAr] Open the graph test CI and fix GraphAr util namespace bug

java/hive/src/main/java/io/v6d/hadoop/fs/FileSystem.java, java/hive/src/main/java/io/v6d/hive/ql/io/VineyardInputFormat.java, java/hive/src/main/java/io/v6d/hive/ql/io/VineyardOutputFormat.java, java/modules/basic/src/main/java/io/v6d/modules/basic/filesystem/VineyardFile.java, java/modules/basic/src/main/java/io/v6d/modules/basic/filesystem/VineyardFileStat.java, java/modules/basic/src/main/java/io/v6d/modules/basic/filesystem/VineyardFileUtils.java
- Remove RawLocalFileSystem code
- Use vineyard to store structure of file system.
=> Refactor vineyard hive filesystem.

CMakeLists.txt, modules/basic/CMakeLists.txt, modules/fuse/CMakeLists.txt, modules/graph/CMakeLists.txt, modules/hosseinmoein-dataframe/CMakeLists.txt, modules/io/CMakeLists.txt, modules/malloc/CMakeLists.txt, modules/msgpack/CMakeLists.txt
=> Binaries should be only installed, not exported

python/client.cc, python/pybind11_docs.cc, python/pybind11_docs.h, python/vineyard/core/tests/test_client.py, src/client/client_base.cc, src/client/client_base.h, src/common/memory/payload.h, src/common/util/env.cc, src/common/util/protocols.cc, src/common/util/protocols.h, src/common/util/uuid.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/memory/allocator.cc, src/server/memory/malloc.cc, src/server/memory/malloc.h, src/server/memory/memory.cc, src/server/memory/memory.h, test/hashmap_mvcc_test.cc
=> Add the API to trim physical memory footprint

src/server/async/socket_server.cc, src/server/async/socket_server.h
=> Remove the socket file when CTRL-C the vineyardd instance

src/server/services/meta_service.cc, src/server/services/meta_service.h
=> Fixes the 'probing stopped service' error in vineyardd, and move implementations to .cc

python/core.cc, python/vineyard/data/utils.py, src/client/ds/remote_blob.cc, src/client/rpc_client.cc
=> Simplify the buffer builder for RPC client

python/vineyard/core/client.py, requirements-dev.txt, requirements.txt
=> Add config parameter to Client with support for YAML configuration file loading.

python/vineyard/data/dataframe.py
Fixes the compatibility issue with Python 3.6 (and pandas 1.1.5, which is the highest version that is available for Python 3.6).
Fixes #1691
=> Fixes compatibility issue with Python 3.6 (with pandas 1.1.5)

src/client/io.cc
=> Allow skipping retry when failed to connect

java/modules/basic/src/main/java/io/v6d/modules/basic/columnar/ArrowFieldVectorAccessor.java, java/modules/basic/src/main/java/io/v6d/modules/basic/columnar/ColumnarData.java, java/modules/basic/src/main/java/io/v6d/modules/basic/columnar/ColumnarDataBuilder.java
As tittled.
- Refactor ColumnarData and ColumnarDataBuilder.
- Remove redundant code.
Fixes #1698
=> Refactor the columnar related code

java/hive/docker/README.rst, java/hive/docker/build.sh, java/hive/docker/dependency/images/Dockerfile, java/hive/docker/dependency/images/bootstrap.sh, java/hive/docker/dependency/images/hadoop-config/log4j.properties, java/hive/docker/dependency/images/hadoop-config/mapred-site.xml, java/hive/docker/dependency/images/hadoop-config/yarn-hosts-include, java/hive/docker/docker-compose.yaml, java/hive/pom.xml, java/hive/src/main/java/com/google/common/base/CharMatcher.java, java/hive/src/main/java/com/google/common/base/Objects.java, java/hive/src/main/java/com/google/common/base/Splitter.java, java/hive/src/main/java/com/google/common/util/concurrent/AbstractCheckedFuture.java, java/hive/src/main/java/com/google/common/util/concurrent/CheckedFuture.java, java/hive/src/main/java/com/google/common/util/concurrent/Futures.java, java/hive/src/main/java/com/google/common/util/concurrent/ListeningScheduledExecutorService.java, java/hive/src/main/java/com/google/common/util/concurrent/MoreExecutors.java
=> Fix dependency conflict between tez and vineyard.

docker/Makefile, docker/vineyard-fluid-mount/Dockerfile, docker/vineyard-fluid-mount/entrypoint.sh
Add the mount vineyard socket dockerfile and we need to push it to our official docker hub when merged.
Fixes part of #1596
=> Add the mount vineyard socket dockerfile for fluid integration

docs/notes/cloud-native/deploy-kubernetes.rst
Fix typo in kubernetes deploy document.
=> fix kubernetes deploy command

src/server/util/etcd_launcher.cc
Prevent vineyardd crashing with some unexpected exceptions.
Fixes #1716
=> Try our best to find etcd binary and raising warnings properly when failed

docs/notes/integration/ml.rst, python/vineyard/contrib/ml/tests/test_torch.py, python/vineyard/contrib/ml/torch.py
- Improve the performance of vineyard.get() for torch tensors.
=> Torch tensor from vineyard (numpy.ndarray): in the zero-copy way

modules/kv-state-cache/ds/kv_state_cache.cc, modules/kv-state-cache/ds/kv_state_cache_block.h, modules/kv-state-cache/radix-tree/radix-tree.h, modules/kv-state-cache/radix-tree/radix.cc, modules/kv-state-cache/radix-tree/radix.h, test/kv_state_cache_test.cc
=> Refactor code of radix split subtree and fix bug of radix split.

modules/kv-state-cache/ds/kv_state_cache.cc, modules/kv-state-cache/ds/kv_state_cache.h, modules/kv-state-cache/radix-tree/radix-tree.cc, modules/kv-state-cache/radix-tree/radix-tree.h, modules/kv-state-cache/radix-tree/radix.cc, modules/kv-state-cache/utils/kv_state_cache_utils.cc, modules/kv-state-cache/utils/kv_state_cache_utils.h, test/kv_state_cache_test.cc, test/kv_state_cache_test_2.cc
- Support merge cache object with radix tree.
- Use cache version to control merge process.
Fixes #1740
=> Support merge cache object with radix tree.

.gitmodules, modules/kv-state-cache/CMakeLists.txt, modules/kv-state-cache/README.rst, modules/kv-state-cache/radix-tree/radix-tree.cc, modules/kv-state-cache/radix-tree/radix-tree.h
=> Replace lz4 with zstd

modules/kv-state-cache/radix-tree/radix.cc
=> Fix the bug in the radix split logic.

.cirrus.yml
=> Fixes golang compiler version on macOS on Arm.

modules/kv-state-cache/ds/kv_state_cache.cc, modules/kv-state-cache/ds/kv_state_cache.h, modules/kv-state-cache/ds/kv_state_cache_block.cc, modules/kv-state-cache/ds/kv_state_cache_block.h, modules/kv-state-cache/utils/kv_state_cache_utils.cc, modules/kv-state-cache/utils/kv_state_cache_utils.h, test/kv_state_cache_test.cc, test/kv_state_cache_test_2.cc
=> Support to store more than 64 entries for kv cache block

modules/kv-state-cache/ds/kv_state_cache.cc, modules/kv-state-cache/radix-tree/radix-tree.cc, modules/kv-state-cache/radix-tree/radix.cc, modules/kv-state-cache/utils/kv_state_cache_utils.cc, test/kv_state_cache_benchmark_test.cc
=> Add a benchmark test for kv state cache

LICENSE, NOTICE.txt, README.rst, modules/kv-state-cache/radix-tree/radix-tree.cc
=> Add the rax linsence and fix a warning

modules/llm-cache/CMakeLists.txt
As titled.
Fixes https://github.com/v6d-io/v6d/issues/1785
=> correct the install directory of llm-cache.

modules/llm-cache/ds/kv_state_cache.cc, modules/llm-cache/ds/kv_state_cache.h, modules/llm-cache/ds/kv_state_cache_block.cc, modules/llm-cache/ds/kv_state_cache_block.h, modules/llm-cache/ds/kv_state_cache_manager.cc, modules/llm-cache/ds/kv_state_cache_manager.h, modules/llm-cache/radix-tree/radix-tree.cc, modules/llm-cache/radix-tree/radix-tree.h, modules/llm-cache/tests/kv_state_cache_benchmark_test.cc, modules/llm-cache/tests/kv_state_cache_multi_test.cc, modules/llm-cache/tests/kv_state_cache_test.cc
=> Change llm api return value to vineyard::Status.

modules/llm-cache/ds/kv_state_cache.cc, modules/llm-cache/ds/kv_state_cache.h, modules/llm-cache/ds/kv_state_cache_block.cc, modules/llm-cache/ds/kv_state_cache_block.h, modules/llm-cache/ds/kv_state_cache_manager.cc
=> Refactor: API of KVStateCacheManager accept Client&.

modules/llm-cache/CMakeLists.txt, modules/llm-cache/ds/kv_state_cache.cc, modules/llm-cache/ds/kv_state_cache_block.cc, modules/llm-cache/ds/kv_state_cache_block.h, modules/llm-cache/radix-tree/radix-tree.cc, modules/llm-cache/radix-tree/radix-tree.h, modules/llm-cache/tests/kv_state_cache_benchmark_test.cc, modules/llm-cache/tests/kv_state_cache_test.cc, src/client/client.h, src/client/rpc_client.h, src/server/async/socket_server.cc, src/server/services/etcd_meta_service.h, src/server/services/local_meta_service.h, src/server/services/redis_meta_service.h, test/hashmap_largefile_test.cc, thirdparty/rax/radix.cc, thirdparty/rax/radix.h
- Remove "using namespace vineyard" sentence.
- Put type definition to vineyard namespace.
- Fix compile errors and warnings on mac os m1 platform.
- Add radix tree to vineyard namespace.
- Fixes #1781
- Fixes #1783
- Fixes #1788
=> Refactor llm cache and fix bug

modules/llm-cache/ds/kv_state_cache.cc, modules/llm-cache/ds/kv_state_cache.h, modules/llm-cache/ds/kv_state_cache_manager.cc, modules/llm-cache/ds/kv_state_cache_manager.h, modules/llm-cache/tests/kv_state_cache_benchmark_test.cc, modules/llm-cache/tests/kv_state_cache_test.cc
- Fix memory leak of llm module.
- Use unique_lock to manager mutex locks in llm module.
Fixes #1813 
Fixes #1814
=> Fix llm memory leak and replace mutex_lock with unique_lock

CMakeLists.txt
Failure: https://cirrus-ci.com/task/5332859091681280
=> Fixes the compliation error under latest MacOS

modules/llm-cache/ds/kv_state_cache.cc, modules/llm-cache/ds/kv_state_cache.h, modules/llm-cache/ds/kv_state_cache_block.cc, modules/llm-cache/ds/kv_state_cache_block.h, modules/llm-cache/ds/kv_state_cache_manager.cc, modules/llm-cache/ds/kv_state_cache_manager.h, modules/llm-cache/ds/refcnt_map.cc, modules/llm-cache/ds/refcnt_map.h, modules/llm-cache/tests/kv_state_cache_test.cc, modules/llm-cache/tests/refcnt_map_test.cc, test/runner.py
=> Remove block objects from cache object meta to reduce the meta size.

modules/llm-cache/ds/kv_state_cache.cc, modules/llm-cache/ds/kv_state_cache.h, modules/llm-cache/ds/kv_state_cache_manager.cc, modules/llm-cache/ds/kv_state_cache_manager.h, modules/llm-cache/tests/kv_state_cache_test.cc, modules/llm-cache/tests/refcnt_map_test.cc
As tittled.
Refer issue.
Fixes #1828
=> Fix bug of refcnt map.

modules/llm-cache/CMakeLists.txt, modules/llm-cache/ds/kv_state_cache_manager.cc, modules/llm-cache/ds/kv_state_cache_manager.h, modules/llm-cache/storage/blob_storage.cc, modules/llm-cache/storage/blob_storage.h, modules/llm-cache/storage/file_storage.h, modules/llm-cache/storage/storage.h, modules/llm-cache/tests/kv_state_cache_test.cc, modules/llm-cache/tests/refcnt_map_test.cc
=> Split the storage of llm cache into blob and file.

modules/llm-cache/ds/config.h, modules/llm-cache/ds/kv_state_cache_manager.cc, modules/llm-cache/hash/hasher.h, modules/llm-cache/storage/file_storage.cc, modules/llm-cache/storage/file_storage.h, modules/llm-cache/storage/local_file_storage.cc, modules/llm-cache/storage/local_file_storage.h, modules/llm-cache/tests/kv_state_cache_on_file_test.cc
As titled.
Fixes part of https://github.com/v6d-io/v6d/issues/1841
=> Implement the update api on fs.

modules/basic/ds/arrow_utils.cc
=> Fixes bug in timestamp parsing

modules/llm-cache/ds/kv_state_cache_manager.cc, modules/llm-cache/ds/kv_state_cache_manager.h, modules/llm-cache/storage/blob_storage.cc, modules/llm-cache/storage/blob_storage.h, modules/llm-cache/storage/file_storage.cc, modules/llm-cache/storage/file_storage.h, modules/llm-cache/storage/local_file_storage.cc, modules/llm-cache/storage/local_file_storage.h, modules/llm-cache/storage/storage.h
- As tittled.
- Add new update api to support refresh a part of kv state.
=> Ensure fs storage process/thread safety

python/vineyard/llm/__init__.py, python/vineyard/llm/config.py, python/vineyard/llm/kv_state_cache.cc, python/vineyard/llm/tests/test_llm.py
As titled.
Fix https://github.com/v6d-io/v6d/issues/1845
=> Add the file storage to the python api of llm kv cache.

python/vineyard/contrib/ml/torch.py
As titled.
Actually, I don't know if simply adding a `value.copy()` is a good way to solve this problem. Could you please take a look at this? @sighingnow 
Fixes https://github.com/v6d-io/v6d/issues/1859
=> Fix the modifications and memory occupation in vineyard torch module.

python/vineyard/core/client.py, src/client/io.cc
=> Refine the vineyard client wrapper to handle the corner case and avoid the block of IO

python/vineyard/llm/config.py, python/vineyard/llm/kv_state_cache.cc
A follow-up of https://github.com/v6d-io/v6d/pull/1862
Related to https://github.com/v6d-io/v6d/issues/1861
=> Add the gc options for fs cache in python api.

.github/workflows/build-vineyardd-and-wheels-linux.yaml
A follow-up of https://github.com/v6d-io/v6d/pull/1869
=> Set up qemu for multi-platform before building vineyard-fuse image.

python/vineyard/contrib/ml/torch.py
As titled
Fixes https://github.com/v6d-io/v6d/issues/1871
=> Support the bfloat16 for pytorch modules.

docs/tutorials/kubernetes/data-sharing-with-vineyard-on-kubernetes.rst, docs/tutorials/kubernetes/efficient-data-sharing-in-kubeflow-with-vineyard-csi-driver.rst, python/vineyard/contrib/airflow/README.md
As titled.
Fixes https://github.com/v6d-io/v6d/discussions/1854
=> Fix the wrong vineyardctl installation address

.github/workflows/build-test.yml, modules/io/io/io_factory.cc, modules/io/io/local_io_adaptor.cc
=> Fixes build error with apache-arrow 16

python/vineyard/contrib/ml/torch.py
- Implement the torch builder and resolver.
- Delete the workaround of cast bfloat16 to float16.
Fixes #1885
=> Implement the torch builder and resolver to support bfloat16

modules/llm-cache/tests/kv_state_cache_benchmark_test.cc
=> Fix the ci error caused by llm benchmark test.

modules/basic/ds/hashmap.vineyard-mod
=> Fix build bug with older arrow version.

src/common/rdma/rdma.cc, src/common/rdma/rdma.h, src/common/rdma/rdma_client.cc, src/common/rdma/rdma_client.h, src/common/rdma/rdma_server.cc, src/common/rdma/rdma_server.h, test/rdma_test.cc
As titled
Fixes https://github.com/v6d-io/v6d/issues/1900
=> Implement the close function to recycle the rdma resources.

src/client/client.cc, src/client/client.h, src/client/rpc_client.cc, src/client/rpc_client.h, src/common/rdma/rdma.cc, src/common/rdma/rdma.h, src/common/rdma/rdma_client.cc, src/common/rdma/rdma_client.h, src/common/rdma/rdma_server.cc, src/common/rdma/rdma_server.h, src/common/rdma/util.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/common/util/uuid.h, src/server/async/rpc_server.cc, src/server/async/rpc_server.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/memory/memory.h, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h, src/server/services/meta_service.cc, src/server/util/remote.cc, src/server/util/remote.h, src/server/util/spec_resolvers.cc, test/fetch_remote_object_test.cc, test/rdma_test.cc
- Refactor code of integration with rdma module.
- Support config rdma endpoing.
- Release resource when client/server exits.
- Alloc multiple buffers for send/recv at server side.
- Use separate threads at the server side to process send/recv messages.
Fixes #1895
=> Refactor rdma related code and supplement the functions of the rdma module.

python/client.cc, python/core.cc, python/pybind11_docs.cc, python/pybind11_docs.h, python/vineyard/core/client.py, python/vineyard/core/resolver.py, src/client/ds/object_meta.cc, src/client/ds/object_meta.h
=> Support to gather all remote blobs concurrently when get an object

src/client/rpc_client.cc, src/client/rpc_client.h, src/common/rdma/rdma.cc, src/common/rdma/rdma.h, src/common/rdma/rdma_client.cc, src/common/rdma/rdma_client.h, src/common/rdma/rdma_server.cc, src/common/rdma/rdma_server.h, src/common/rdma/util.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/server/vineyard_server.cc, src/server/util/remote.cc, src/server/util/remote.h, test/remote_buffer_test.cc, test/rpc_get_object_test.cc, test/rpc_test.cc
=> Reuse rdma domain and support get/create remote buffer by rdma of RPCClient.

docker/vineyard-fluid-fuse/entrypoint.sh
As titled.
Fixes https://github.com/v6d-io/v6d/issues/1907
=> Support to configure the parameters of vineyardd in vineyard fluid fuse.

CMakeLists.txt, python/client.cc, python/vineyard/core/client.py, src/client/rpc_client.cc, src/client/rpc_client.h
=> Add the rdma endpoint for the rpc client in the Python API.

modules/llm-cache/storage/file_storage.cc
Currently, llm cache module fails in garbage collection under prolonged stress testing.
Fixes #1918
=> Fix llm gc bug

.github/workflows/build-test.yml, modules/llm-cache/README.md, modules/llm-cache/tests/k8s-test/worker.py, modules/llm-cache/tests/kv_cache_local_file_test.cc, modules/llm-cache/tests/kv_cache_test.cc, python/vineyard/llm/cache.py, python/vineyard/llm/tests/test_llm.py
As titled.
A follow up of https://github.com/v6d-io/v6d/pull/1913
=> Refine the config and the ci test of llm kv cache.

python/client.cc, python/vineyard/deploy/tests/test_migration.py
As titled.
Fixes https://github.com/v6d-io/v6d/issues/1926
=> Fix the migration ci test and release the gil when get object.

python/vineyard/data/dataframe.py
As titled.
Fixes https://github.com/v6d-io/v6d/issues/1930
=> Fix inconsistent value types in dataframe_resolver.

src/client/io.cc
The select only support 1024 fds, but the epoll doesn't have the hard limitations.
Fixes https://github.com/v6d-io/v6d/issues/1935
=> Replace select with epoll to support more fds.

docs/notes/architecture.rst, docs/notes/developers/faq.rst, docs/notes/key-concepts/data-accessing.rst, docs/notes/references/python-api.rst
There are several parts out of date in the doc, which may confuse the users.
Fixes part of https://github.com/v6d-io/v6d/issues/1936
=> Fix the out of date part in the doc.

src/client/io.cc
As titled.
Fixes the incompatibility on macos introduced by https://github.com/v6d-io/v6d/pull/1937
=> Add the macros for epoll on Macos.

src/client/rpc_client.cc, src/client/rpc_client.h, src/common/rdma/rdma_client.h, test/rdma_blob_perf_test.cc
=> Added GetRemoteBlob interface to support user-specified buffer for data storage.

src/server/services/etcd_meta_service.cc, src/server/services/etcd_meta_service.h, test/runner.py
As titled.
Fixes https://github.com/v6d-io/v6d/issues/1947
=> Retry to connect to the etcd continuously when it's unconnectable.

src/client/rpc_client.cc, src/client/rpc_client.h, src/common/util/protocols.cc, src/common/util/protocols.h, src/server/async/socket_server.cc, src/server/async/socket_server.h, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h
=> Prevents objects from being deleted during transfer.

src/common/rdma/rdma.h, src/common/rdma/rdma_server.cc
=> Fix memory leak when client crashed

src/server/server/vineyard_server.cc, src/server/services/meta_service.cc
As titled.
Fixes https://github.com/v6d-io/v6d/issues/1979
=> Fix the json exception when the rdma_endpoint is null. 

CMakeLists.txt
=> Fix the symbol error when build the vineyard llm module.

modules/llm-cache/ds/vineyard_file.cc, modules/llm-cache/storage/file_storage.cc, src/server/async/rpc_server.cc, src/server/server/vineyard_server.cc, src/server/server/vineyard_server.h, src/server/util/remote.cc
=> Fix compile warnings.

modules/io/io/i_io_adaptor.h
Enable user to process the results of `ReadTable` in a streaming way
=> add callback option to IO interface

charts/vineyard-operator/values.yaml, k8s/config/default/manager_auth_proxy_patch.yaml
=> Update the kube proxy image.

modules/basic/ds/arrow.cc
As titled.
Fixes https://github.com/v6d-io/v6d/issues/2043
=> Add the build compatibility with arrow-20.0.0

modules/basic/ds/arrow_utils.cc, src/common/util/config.h
=> Fix the build compatibility with arrow 20.0.0

modules/basic/ds/arrow_shim/concatenate.cc
Fix v6d when being built under Apache Arrow 21.
DCHECK_EQ was hidden in Arrow 21, see https://github.com/apache/arrow/issues/46011. ARROW_DCHECK_GE should be used instead.
No.
=> Fix build for Apache Arrow 21.0.0
