v6d-io/v6d

- python/client.cc
- python/core.cc
- python/vineyard/_vineyard_docs.py
- src/client/client.h
- src/client/rpc_client.cc
- src/client/rpc_client.h
- src/common/util/status.h
Now the `connect` in Python and `Connect` in C++ can resolve vineyard socket, both for IPC client and RPC client, from the environment variable `VINEYARD_IPC_SOCKET` and `VINEYARD_RPC_ENDPOINT`.
> More flexible paramter combination on `connect`.

- modules/graph/fragment/arrow_fragment.h
- modules/graph/utils/selector_utils.h
* Fix a warning of unused variable.
* Fix a warning of comparison between signed and unsigned integer expressions.
> Fix compile warning.

- modules/basic/ds/pair.h
- modules/basic/ds/tuple.h
- src/server/server/vineyard_server.cc
- src/server/services/meta_service.cc
- src/server/services/meta_service.h
- test/delete_test.cc
- test/rpc_delete_test.cc
When fail to delete some blobs, continue to delete others.
The blobs that cannot be delete are empty blobs: the empty blob doesn't do real memory allocation and has address `0x0`, that, cannot be processed by `dlmalloc`, thus the failure, causing subquential blobs are failed to be deleted as well.
> Fixes a bug in DeleteBlobBatch, also revise `delVal`.

- python/client.cc
- src/server/util/meta_tree.cc
Errors:
```cpp
E1201 11:25:29.439462    55 object_meta.cc:132] Check failed: Assertion failed: child_meta: Failed to get member buffer_ in "::vineyard::Status::AssertionFailed( std::string("child_meta" ": ") + "Failed to get member " + name)"
E1201 11:25:29.441027    56 object_meta.cc:132] Check failed: Assertion failed: child_meta: Failed to get member buffer_ in "::vineyard::Status::AssertionFailed( std::string("child_meta" ": ") + "Failed to get member " + name)"
E1201 11:25:29.441253    55 dispatcher.cc:74] /root/gsa/analytical_engine/core/rpc/dispatcher.cc:58: operator() -> Unmatched std::exception detected: Check failed: Assertion failed: child_meta: Failed to get member buffer_ in "::vineyard::Status::AssertionFailed( std::string("child_meta" ": ") + "Failed to get member " + …
```
> Fixes a bug in get remote object (when its members includes blobs).

- python/vineyard/core/codegen.py
Fixes potential issue on centos systems, with various versions of alicpp installed.
None
> Use `-isystem` for system-wide include directories.

- python/vineyard/data/dataframe.py
- setup.cfg.in
Pandas 1.2.0 drops python 3.6 support, and pandas 1.0.0 drops python 3.5 support. And there's are a breaking change in python 1.2.0 that affects us.
Fixes #112
> Fixes compatiblity bug for pandas 1.2.0.

- python/vineyard/data/__init__.py
- python/vineyard/data/series.py
- python/vineyard/data/tests/test_series.py
support Series structure of pandas
Fixes #117
> add pandas series

- python/vineyard/data/default.py
- python/vineyard/data/tests/test_dataframe.py
- python/vineyard/data/tests/test_tensor.py
support sparse data structure of pandas serialize/deserialize
pyarrow not support serialize/deserialize sparse data, use pickle when the data not support in pyarrow.
> support sparse data structure of pandas serialize/deserialize

- python/vineyard/data/tests/test_dataframe.py
- src/server/services/etcd_meta_service.cc
- src/server/util/etcd_launcher.cc
- test/large_meta_test.cc
- test/runner.py
We don't need such flags for etcd server anymore, by splitting a large update set to many transactions. We compute etcd ops by DFS when persisting object, ensuring the correctness of segmented updates for etcd.
This pull request will remedy #107 as well.
> Conform the max-txn-ops requirement of etcd.

- CMakeLists.txt
- modules/basic/stream/byte_stream.vineyard-mod
- modules/basic/stream/dataframe_stream.vineyard-mod
- modules/basic/stream/stream_utils.h
- modules/graph/loader/arrow_fragment_loader.h
- modules/graph/utils/error.h
- modules/io/adaptors/dump_dataframe.cc
- modules/io/adaptors/parse_bytes_to_dataframe.cc
- modules/io/adaptors/read_kafka_bytes.cc
- modules/io/adaptors/read_local_bytes.cc
- modules/io/adaptors/read_oss_dataframe.cc
- modules/io/adaptors/write_kafka_bytes.cc
- modules/io/adaptors/write_kafka_dataframe.cc
- python/stream.cc
- src/client/client.cc
- src/client/client.h
- src/common/util/protocols.cc
- src/common/util/protocols.h
- src/common/util/status.cc
- src/common/util/status.h
- src/server/async/socket_server.cc
- src/server/memory/stream_store.cc
- src/server/memory/stream_store.h
- test/stream_test.cc
> Markstream to enable 1-producer-1-consumer on server side

- CODE_OF_CONDUCT.md
- GOVERNANCE.md
- MAINTAINERS.md
- OWNERS
- SECURITY.md
> add community related markdowns

- modules/basic/ds/array.vineyard-mod
- modules/basic/ds/arrow.vineyard-mod
- modules/basic/ds/dataframe.vineyard-mod
- modules/basic/ds/hashmap.vineyard-mod
- modules/basic/ds/pair.vineyard-mod
- modules/basic/ds/scalar.vineyard-mod
- modules/basic/ds/tensor.vineyard-mod
- modules/basic/ds/tuple.vineyard-mod
- modules/basic/stream/byte_stream.vineyard-mod
- modules/basic/stream/dataframe_stream.vineyard-mod
The header files generated contains attributes defined by vineyard. When an application includes them, "unknown attribute" warnings are issued during compilation.
Here add pragma to ignore such warnings for gcc. Fix for other compiler remains to-do.
Changes to be committed:
modified:   modules/basic/ds/array.vineyard-mod
modified:   modules/basic/ds/arrow.vineyard-mod
modified:   modules/basic/ds/dataframe.vineyard-mod
modified:   modules/basic/ds/hashmap.vineyard-mod
modified:   modules/basic/ds/pair.vineyard-mod
modified:   modules/basic/ds/scalar.vineyard-mod
modified:   modules/basic/ds/tensor.vineyard-mod
modified:   modules/basic/ds/tuple.vineyard-mod
modified:   modules/basic/stream/byte_stream.vineyard-mod
modified:   modules/basic/stream/dataframe_stream.vineyard-mod
> Fix "unknown attribute" warning when 3rd party application uses vineyard header files. 

- .github/workflows/build-wheel.yml
- docker/pypa/Dockerfile.manylinux1-wheel
- setup.py
We have noticed that the latest pip doesn't support python 3.5 anymore.
> Drop python 3.5 support.

- .dockerignore
- .gitignore
- modules/basic/CMakeLists.txt
- modules/basic/ds/arrow_utils.h
- modules/graph/fragment/property_graph_utils.h
Move the dependency of `libgrape-lite` to `modules/graph`.
Fixes #166.
> Don't requires grapelite in vineyard_basic.

- modules/io/adaptors/read_bytes.py
- modules/io/adaptors/write_bytes.py
- modules/io/python/drivers/io/ssh.sh
- python/vineyard/io/serialization.py
- python/vineyard/io/stream.py
- python/vineyard/launcher/launcher.py
- python/vineyard/launcher/script.py
Pass the messages in process's stderr channel to client's exception message, for easier debug.
Also remove a `-x` flag in shell cause it's doesn't bring much information and add extra noise.
Fixes #170
> Store exception information in drivers

- modules/migrate/vineyard_migrate.cc
- python/vineyard/.gitignore
- python/vineyard/core/tests/__init__.py
- python/vineyard/core/tests/test_client.py
- src/server/server/vineyard_server.cc
- src/server/services/meta_service.h
- src/server/util/meta_tree.cc
Avoid put duplicated keys to etcd.
A test case has been added for that.
N/A
> Fixes persist error when the same object is refered multiple times in different members.

- CMakeLists.txt
- python/client.cc
- python/core.cc
- python/pybind11_utils.h
- python/vineyard/__init__.py
- python/vineyard/_vineyard_docs.py
That is useful, when we use a variable to represent a vineyard object. We don't have the object ID and just have a name, and the `get_name` transformation is not available currently.
We need such a wrapper to differ a ordinary string with a string that is actually a name for vineyard object.
N/A
> Add a ObjectName type to indicate a str is a vineyard object.

- modules/io/setup.py
- modules/migrate/vineyard_migrate_stream.cc
- setup.py
To make sure package `vineyard` and `vineyard-io` are installed to the same directory.
Fixes #111.
> Force vineyard-io as a platlib, but with a universal tag.

- modules/graph/fragment/property_graph_utils.h
`arrow::compute::CanCast` is available since v0.17.
N/A.
> Fixes arrow 0.17 compatiblity.

- docs/notes/python_api.rst
- python/client.cc
- python/core.cc
- python/vineyard/_vineyard_docs.py
- python/vineyard/shared_memory/__init__.py
- python/vineyard/shared_memory/shared_memory.py
- python/vineyard/shared_memory/tests/__init__.py
- python/vineyard/shared_memory/tests/test_shared_memory.py
- src/client/client.cc
- src/client/client.h
- src/client/ds/blob.cc
- src/client/ds/blob.h
- src/common/util/protocols.cc
- src/common/util/protocols.h
- src/server/async/socket_server.cc
- src/server/async/socket_server.h
- test/runner.py
Implemements `shared_memory.{SharedMemory, ShareableList}` interface using the same interface design of `multiprocessing.shared_memory`.
That would bring benefits to python users.
Fixes #195.
This pull request also implements "Abort" semantic for `BlobWriter`, for #100.
> Implements a shared_memory.{SharedMemory, ShareableList} interface on vineyard

- modules/basic/ds/hashmap.h
- modules/graph/fragment/arrow_fragment.h
- modules/graph/fragment/property_graph_utils.h
- modules/graph/loader/arrow_fragment_loader.h
- modules/graph/loader/basic_e_fragment_loader.h
- modules/graph/loader/basic_ev_fragment_loader.h
- modules/graph/utils/partitioner.h
- modules/graph/vertex_map/arrow_vertex_map.h
- src/client/ds/i_object.h
> Add edges to existing graph

- modules/graph/fragment/arrow_fragment.h
- modules/graph/fragment/graph_schema.cc
- modules/graph/fragment/graph_schema.h
- modules/graph/utils/table_shuffler_beta.h
Related alibaba/graphscope#134
> Support general project operator on graph.

- modules/graph/fragment/graph_schema.cc
As the property id is not continuous when used in MaxGraphSchema.
> Hot fix for #239

- modules/graph/utils/partitioner.h
since [this commit](https://github.com/facebook/folly/commit/c391dc14a668aa87df295e1546279f7bca85f0ce#diff-735b6af000822abdde29d4ac622393f651f4c73e6025e48e2c6c1c126da2fde6)  folly support hash of  object/array type folly::dynamic, we should allowing folly::dynamic oid of object/array/double/bool type to be hashed
> allowing folly::dynamic oid of object/array/double/bool type to be hashed

- python/vineyard/deploy/tests/test_distributed.py
- src/server/async/ipc_server.cc
- src/server/async/rpc_server.cc
- src/server/async/socket_server.cc
- src/server/async/socket_server.h
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
- src/server/services/etcd_meta_service.cc
- src/server/services/etcd_meta_service.h
- src/server/services/meta_service.h
- src/server/util/etcd_launcher.cc
- src/server/vineyardd.cc
- test/invalid_connect_test.cc
- test/runner.py
Eliminate the exceptions when killing the server, and it may help the coverage rate as well.
> Makes the ctrl-c safe for every stage during booting. 

- README.rst
The Apache Arrow web link is wrong. Correct it.
> Update the Apache Arrow web link

- modules/io/io/local_io_adaptor.cc
- python/vineyard/data/pickle.py
- python/vineyard/data/tests/test_pickle.py
I think the vineyard backend in mars will needs such tools.
And it will simply the distributed (python) job that works on vineyard and needs job-specific value migration.
> A helper to provide a bytes interface for r/w on Python object.

- charts/vineyard/README.md
- charts/vineyard/templates/NOTES.txt
- charts/vineyard/templates/daemonset.yaml
- charts/vineyard/templates/domain-socket-pvc.yaml
- charts/vineyard/templates/tests/test-rpc.yaml
- charts/vineyard/values.yaml
The unix-domain socket for vineyardd can be placed on a PVC now.
Fixes #274
> Enhance the helm charts implementation.

- .github/workflows/build-test.yml
- python/client.cc
- python/error.cc
- python/vineyard/deploy/tests/test_distributed.py
- src/client/client.cc
- src/client/client.h
- src/client/rpc_client.h
- src/common/util/protocols.cc
- src/server/memory/memory.cc
- src/server/memory/stream_store.cc
- src/server/server/vineyard_server.cc
- src/server/services/meta_service.h
- src/server/util/meta_tree.cc
The later part will helps to reduce the traffic between etcd server, more specifically,
+ fixes a data-race bug in deletion
+ fixes a "pass-by-ref" bug in `RequestToGetData`, which leads to many bugs when contention is high.
+ start hearbeat after the previous round finishes
+ improve the error message for "ObjectNotExistsException" in Python SDK.
Fixes #294.
> Fixes data-race in delete (local) metadata, and start heartbeat when previous round finished.

- modules/graph/fragment/arrow_fragment.h
- modules/graph/fragment/graph_schema.cc
- modules/graph/fragment/graph_schema.h
- modules/graph/loader/basic_ev_fragment_loader.h
1. Maintain orders of labels as user specified.
2. Bugfix of AddEdges, do property reassignment of the offset array.
3. Validate the schema that properties with the same name must have the same type.
4. Add primary keys when necesssary.
Fixes #297.
/hold until the CI in GraphScope turned green.
> Enhancement and bugfix of fragment related stuffs.

- test/runner.py
MacOS doens't have a `/dev/shm`, rather, we place the data dir to `/tmp`.
Fixes #307.
> Test runner: put etcd data dir to /tmp when running on MacOS.

- src/server/server/vineyard_server.cc
- src/server/util/spec_resolvers.cc
Add a command line argument `rpc` to vineyardd, with default value `True`, and can be disabled by `-norpc`, to allow the RPC service been disabled when necessary.
That will help cases where we won't to launch multiple vineyardd instances but we are not willing to specify different RPC port for them.
This pull request bump the etcd-cpp-apiv3 submodule as well.
Resolves #317.
> Add a command-line option to vineyardd for disabling the RPC service.

- python/vineyard/deploy/__init__.py
- python/vineyard/deploy/distributed.py
- python/vineyard/deploy/etcd.py
- python/vineyard/deploy/kubernetes.py
- python/vineyard/deploy/local.py
- python/vineyard/io/core.py
This pull request starts to support deploy multiple vineyardd instances, by specifying a generated unique "--socket" argument, as well as unique data dir for standalone etcd.
The RPC service can be disabled when launching from vineyard (launching multiple worker on the same single host) from python interface as well.
Related to #317 .
> Fixes issues in deploying vineyardd using python interface.

- python/vineyard/__init__.py
- python/vineyard/data/__init__.py
- python/vineyard/data/base.py
- python/vineyard/data/default.py
- python/vineyard/data/pickle.py
- python/vineyard/data/tests/test_base.py
- python/vineyard/data/tests/test_default.py
- python/vineyard/data/tests/test_pickle.py
+ Enhance support for `bytes`, `memoryview` and `numpy.bool_` types.
+ Introduce a `vineyard::PickleBuffer` type to represent things that fall back to default builder, and differ it from raw bytes/memoryviews (which are `vineyard::Blob`).
N/A.
> Enhancement on vineyard resolver/builder for better support for native types.

- python/vineyard/shared_memory/shared_memory.py
Use the library `shared-memory38` as dependency for Python 3.6/3.7.
Fixes #327.
> Adding the shared-memory38 dependency.

- src/server/services/etcd_meta_service.cc
- src/server/services/etcd_meta_service.h
The callback data structures cannot be modified concurrently.
Fixes #330.
> Use a std::mutex to protect registered_callbacks_.

- setup.py
Followup work for #329, and fixes #327.
Fixes #327
> Install shared-memory38 as deps for python<=3.7 as well.

- src/common/util/status.cc
- src/common/util/status.h
Associate a backtrace to erroneous Status.
1. Add a `std::string backtrace_` field into the `class Status`
2. Add a getter `const std::string Status::Backtrace() const {}` to `class Status`
3. In constructor of `Status`, when the status code is not “OK", initialize the `backtrace_` field by calling `vineyard::backtrace_info::backtrace()`.
Fixes #326
> Fixs issues in associate a backtrace to erroneous status.(v6d-io#326)

- src/server/memory/allocator.cc
Added a condition to check the **maximum shared memory size** and raise a **warning** when it is **less** than the value of the `size` parameter.
Fixes #316
> [FEATURE-316] Condition to check maximum shared memory size

- CMakeLists.txt
- python/client.cc
- python/pybind11_utils.h
- python/vineyard/deploy/tests/test_migration.py
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
- src/server/services/etcd_meta_service.cc
- src/server/services/meta_service.cc
- src/server/services/meta_service.h
- src/server/util/etcd_launcher.cc
- src/server/util/meta_tree.cc
- src/server/util/meta_tree.h
- test/runner.py
This PR overhaul the implementation of "signatures". We previously store signatures as
```
/signatures
/sig -> object_id
```
Now we have
```
/signatures
/instance_name
/sig -> object_id
```
Such a change allow us to differ the replica for a object after migration, and do things correctly when deleting the migrated chunk or the original chunk after migration. The global object will be still kept complete and the deleted chunk could be freed as expected.
See also test case `test_migration_and_deletion` and `Note [Deleting global object and members]` for the detail about how we handle the use-ref in such cases.
Fixes #212.
> Enhance the support for migration + deletion.

- .github/workflows/build-compatibility.yml
- .github/workflows/build-test.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docs.yaml
- docker/Dockerfile.ubuntu
- docs/notes/install.rst
The bintray download site has been deprecated and apache-arrow has moved to jfrog. This pull request updates related installation instructions to avoid misleading information to end users.
Fixes #339
> Revise the install instruction for apache-arrow.

- src/server/services/etcd_meta_service.cc
Otherwise when there's no incoming events and we still want to register
a callback on current watcher with HEAD revision (since_rev), the callback
won't be called immediately as expected.
The bug can be reproduced when there's only one instance.
As it is a "daemon watcher", we assume there's only one running backend
watcher.
N/A, but related to #313.
> Initialize the "handled_rev_" with a proper value.

- src/common/util/env.cc
- src/common/util/env.h
- src/server/memory/allocator.cc
The pull request #322 use some platform-specific macros which broke the docker image build process. This pull request fixes that, and overhaul those platform-related stuffs.
None
> Put implementation for platform-specific APIs into a common `env.cc`.

- .github/workflows/build-test.yml
- python/core.cc
- python/vineyard/data/tensor.py
- python/vineyard/data/utils.py
Return a view of subclass of ndarray to support attach `__vineyard_ref` to the ndarray. 
Related to #298.
> Enhance the tensor builder to return a customized subclass.

- CONTRIBUTING.rst
- docs/notes/install.rst
Avoid using `make -j`, as we have recieved a lot complaints about failure in VM or docker with `make -j`.
Fixes #345, see also #291.
> Suggest use `make -j$(nproc)` to users.

- python/core.cc
Copy the content of bytes to blob directly, rather than cast it to `std::string` first, improving the performance a bit.
N/A.
> Resolve a FIXME, avoid redundant copy when building contents to blob.

- CMakeLists.txt
- modules/io/python/drivers/io/stream.py
- modules/io/python/drivers/io/tests/test_migrate_stream.py
- modules/io/python/drivers/io/tests/test_serialize.py
- python/client.cc
- python/core.cc
- python/error.cc
- python/pybind11_utils.cc
- python/pybind11_utils.h
- python/stream.cc
- python/vineyard/_vineyard_docs.py
- python/vineyard/core/builder.py
- python/vineyard/core/tests/test_client.py
- python/vineyard/data/base.py
- python/vineyard/deploy/tests/test_distributed.py
Returns `metadata` rather than `id` in `client.create_metadata` to avoid  a indirect remote sync/update to bump up performance when creating **nested** python objects to vineyard.
Related to #298 and is the subsequential work of #346.
> Improve the implementation of `create_metadata`.

- docs/notes/divein.rst
The get() function returns a memoryview which does not have attributes like size and typename.
Fixes #296
> Fixed Blob description in docs

- modules/basic/stream/object_stream.h
- modules/basic/stream/object_stream.vineyard-mod
- python/stream.cc
- python/vineyard/io/object.py
- src/client/client.cc
- src/client/client.h
- src/common/util/protocols.cc
- src/common/util/protocols.h
- src/server/async/socket_server.cc
- src/server/async/socket_server.h
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
- test/object_stream_test.cc
Add object stream to vineyard in parallel to byte/dataframe streams. The future plan is to replace byte/dataframe streams
with object streams of blob ids and dataframe ids.
This will potentially solve the dataframe copy issue indicated in Issue 220.
Fixes #220.
> Add object stream which transfers object ids between consecutive workloads

- python/vineyard/data/dataframe.py
- python/vineyard/data/series.py
- python/vineyard/data/tensor.py
- python/vineyard/data/tests/test_pickle.py
- python/vineyard/data/utils.py
- setup.py
Adapt to `BlockManager` API of pandas v1.3.0.
Fixes #361.
> Compatible with pandas==1.3.0.

- python/client.cc
- python/core.cc
- python/pybind11_utils.cc
- python/pybind11_utils.h
- src/client/ds/object_meta.cc
+ Enable `py::pickle` for `vineyard::ObjectMeta`
+ Refer tools `{to,from}_json` to support casting between python value and nlohmann::json. Vineyard cannot directly depends on pybind11_json, due to the visibility issue.
Fixes #352.
> Enable pickle support for metadata.

- src/server/async/ipc_server.cc
- src/server/async/rpc_server.cc
- src/server/server/vineyard_server.cc
The `IPCReady()` callback shouldn't be in front of `ipc_service_start`.
Fixes #378
> RPC & IPC service depends on the meta & bulk only.

- python/vineyard/contrib/ml/tensorflow.py
* Added a Builder and Resolver for vineyard::Tensor which will accept data in form of tf.data.Dataset and store as Tensor object, similarly, resolve back to tf.data.Dataset
* Added a builder for vineyard::Dataframe which converts tf.data.Dataset in form of dictionary data and its corresponding labels. The resolver first converts the vineyard Dataframe to Pandas Dataframe and then to tf.data.Dataset object.
Future Work
-------------------------------
* Adding builders and resolvers for Tables and RecordBatches.
* Implementing a single builder and resolver for all datatypes in tensorflow.
Part of #280
> [WIP] Added tensorflow builders and resolvers for datatypes tensor and dataframe

- python/vineyard/cli.py
Adds `stat` **command** to vineyard-ctl. The `stat` **command** helps **print** the **status** of the **connected vineyard server**.
> Adds stat command to vineyard-ctl

- src/server/vineyardd.cc
Now `vineyardd --version` prints
```bash
vineyardd version 0.2.6
```
Fixes #385
> Add a version string to vineyardd by gflags::SetVersionString.

- .github/workflows/build-test.yml
- python/vineyard/contrib/ml/tests/test_xgboost.py
- python/vineyard/contrib/ml/xgboost.py
- test/runner.py
As title, we omit the integration with global objects in this PR since xgboost does not support native distributed training.
Instead, we will try to handle global objects in distributed training frameworks that xgboost leverages (e.g., dask) in the future.
Related to #280.
> Add DMatrix resolvers and tests for better integration with xgboost 

- python/vineyard/contrib/ml/tests/test_xgboost.py
- python/vineyard/core/builder.py
- python/vineyard/core/driver.py
- python/vineyard/core/resolver.py
Use a scoped autouse fixture to run xgboost tests.
Follow-up work for #394 and #399.
> Run xgboost tests use a scoped fixture, rather than populating the global ctx

- src/server/async/ipc_server.cc
On Kubernetes, we still launch the vineyard using `root` user, but allow other users to operate on the socket and estalish the connection.
Fixes #404.
> Allow the IPC socket connectable by other users.

- python/vineyard/core/resolver.py
As an enhancement to ensure the client keep alive when the python value object is alive.
N/A
> Associate the client object to resolved value as well when possible.

- CMakeLists.txt
- python/vineyard/contrib/airflow/xcom/backend.py
- setup.py
- setup_airflow.py
- setup_dask.py
- setup_ml.py
Making airflow's distributed celery worker can run on vineyard xcom backend, includes,
+ enable auto-migration when accessing remote objects
This pull request tidy these setup.py files as well.
Part of #374.
> Airflow: support running among distributed celery workers.

- prometheus/grok_exporter.yml
- prometheus/prometheus.rules.yml
- prometheus/prometheus.yml
- src/common/util/logging.h
- src/server/server/vineyard_server.cc
- add basic metrics to log: data_request_latency and data_requests_total
-  add [grok_exporter](https://github.com/fstab/grok_exporter) setting file to export those metrics from log files, metrics will be displayed on : <http://localhost:9144/metrics>
```bash
./grok_exporter -config v6d/prometheus/grok_exporter.yml -disable-exporter-metrics
```
-  add [prometheus](https://prometheus.io/) setting file to read those metrics
```bash
./prometheus --config.file=v6d/prometheus/prometheus.yml
```
-  add a prometheus recording rule file to calculate average request latency/
Related issue number #275 
> [MRG]🎉 init prometheus setting

- src/common/util/logging.h
- src/server/async/socket_server.cc
- src/server/server/vineyard_server.cc
- src/server/util/metrics.h
- src/server/util/spec_resolvers.cc
- src/server/util/spec_resolvers.h
- src/server/vineyardd.cc
Add a command line flags `--prometheus` and `--metrics` to conditionally print the metric logs.
Follow-up work for #418.
> Add a command line flag to control whether printing the metrics.

- modules/graph/fragment/arrow_fragment.h
Fix the type parameters inconsistency in arrow_fragment::vertex_data_column
Fixes #426
> Fix template type in VertexDataColum

- python/vineyard/contrib/ml/pytorch.py
- python/vineyard/contrib/ml/tensorflow.py
- python/vineyard/contrib/ml/xgboost.py
- python/vineyard/core/builder.py
- python/vineyard/core/driver.py
- python/vineyard/core/resolver.py
- python/vineyard/core/utils.py
This pull request fixes #423, by patching `__vineyard_ref` in the resolver, and add a `__call__` method for builder/resolver/driver context.
This pull request also reduces the code duplication in the ML integration to make the code more concise.
Fixes #423.
> Refine the resolver context implementation, and refactor duplicated code

- .github/workflows/rust-ci.yml
- rust/vineyard/src/client/mod.rs
> Add CI for Rust

- src/server/async/socket_server.cc
The client my given invalid json, which, yeilds the "invalid" error status.
The input from clients could be invalid "json" object as well, which leads
to JSON exception finally and crash the server.
This pull request enhances such check to make sure vineyard not crash.
N/A
> Catch JSON error as well when reading the RPC request from client.

- src/client/client.cc
- src/client/ds/blob.cc
- src/common/util/protocols.cc
- src/common/util/protocols.h
This pull request enhances the implementation detail of `mmap` -> `pointer` -> `buffer`.
N/A
> Ensure `mmap` in the same order with send_fd in server.

- src/client/ds/object_factory.cc
- src/client/ds/object_factory.h
- src/client/ds/object_meta.cc
- src/client/ds/object_meta.h
Makes the `ObjectMeta` decouple from `vineyard::Client`, and make it could be constructed easily from foreign languages.
Part of #227.
> Implements a static constructor to get metadata from unsafe sources.

- docs/notes/dask.rst
Add a description of how to preprocess data with dask and save it to vineyard in transfer learning
> Update Dask Doc

- src/server/async/socket_server.cc
- src/server/async/socket_server.h
After introduce multi-thread socket server there seems a contention, that should be invalid for good clients, but the vineyardd shouldn't crash.
Resolves #463
> Use a lock to protect the mutable write buffer queue.

- python/vineyard/contrib/airflow/xcom/__init__.py
When trying to use the XCom provider Airflow cannot find the VineyardXCom class because it is not defined in the \_\_init\_\_.py file so it needs to be defined.
Fix error when trying to use the XCom backend.
None
> Update __init__.py to import VineyardXCom

- .gitmodules
- CMakeLists.txt
- README.rst
- python/vineyard/data/base.py
- src/common/util/typename.h
- test/runner.py
- test/typename_test.cc
Revisit the `vineyard::type_name` implementation to make it more composable and stable when acrossing platforms. e.g., `std::string` will be always `std::string` no matter on which platform, and `int64_t` will be always "int64", rather than "long", or "long long" on different platforms.
Users can supply their own typename for customized type, e.g.,
```cpp
struct XX {
};
namespace vineyard {
template <>
inline const std::string type_name() {
return "XX-name";
}
}
```
Fixes #457
> Revisit the implementation of typename: more customizable and stable.

- docs/notes/ctl.rst
- python/vineyard/cli.py
- setup.py
Added `tree` option to `query` **command** in `vineyard-ctl`. `tree` lets you print vineyard object lineage in a tree-like style.
Part of #291.
> Adds tree option to query command in vineyard-ctl

- modules/graph/loader/basic_e_fragment_loader.h
The previous code, use `std::string_view` that the original table is already out-of-scope and been released, triggering memory error when loading efiles graph and the OID type is string.
See also alibaba/GraphScope#755.
> Fixes the use-after-free bug for string-view in the oid array.

- src/server/server/vineyard_server.cc
- src/server/vineyardd.cc
Here we need return after reporting errors to clients, rather than continuing.
Fixes #483
> Fixes a crash when adding invalid metadata.

- modules/io/adaptors/parse_dataframe_to_bytes.py
- modules/io/adaptors/read_bytes.py
- modules/io/adaptors/read_orc.py
- modules/io/adaptors/write_bytes.py
- modules/io/adaptors/write_orc.py
- modules/io/adaptors/write_vineyard_dataframe.py
- modules/io/python/drivers/io/stream.py
- modules/io/python/drivers/io/tests/test_migrate_stream.py
- modules/io/python/drivers/io/tests/test_open.py
- modules/io/python/drivers/io/tests/test_serialize.py
- python/vineyard/launcher/script.py
If the writer fails with the `FAILED` status the raise an exception with proper error message to the client.
Fixes #484
> Vineyard IO: raise exceptions when encounter errors in writers (in its `join()`)

- python/core.cc
Adjust the register order of pybind11 types to fixes #485.
Fixes #485
> Support adding metadata with `__setitem__` operator on ObjectMeta.

- python/client.cc
- python/vineyard/_vineyard_docs.py
- src/client/client_base.cc
- src/client/client_base.h
- src/common/util/protocols.cc
- src/common/util/protocols.h
- src/server/async/socket_server.cc
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
- src/server/util/meta_tree.cc
- src/server/util/meta_tree.h
Extends shallow-copy to support more kinds of operations.
N/A
> Support injecting extra metadata in existing objects via a shallow copy.

- docs/notes/ctl.rst
- python/vineyard/cli.py
Added `memory_status` option to `query` **command** in `vineyard-ctl`. `memory_status` lets you print the **memory** used by a **vineyard object**.
Part of #291.
> Adds memory_status option to query command in vineyard-ctl

- python/vineyard/contrib/airflow/README.rst
- python/vineyard/contrib/airflow/tests/__init__.py
- python/vineyard/contrib/airflow/tests/test_base.py
- python/vineyard/contrib/airflow/tests/test_pandas_dag.py
- python/vineyard/contrib/airflow/tests/test_python_dag.py
- python/vineyard/contrib/airflow/xcom/backend.py
- python/vineyard/deploy/__main__.py
- python/vineyard/deploy/local.py
+ Add test suite to run dag with python value
+ Add test suite to run dag with pandas dataframe (which is not possible with the default XCom backend).
+ Add a helper function to deploy vineyardd eaiser.
Part of #374
> Airflow: unitest, and support easier launching of vineyard server.

- docs/notes/ctl.rst
- python/vineyard/cli.py
Adds `start` command to `vineyard-ctl`. `start` allows **starting** `vineyardd` either `locally` or `distributedly`.
Part of #291.
> Adds start command to vineyard-ctl

- docs/examples/distributed-learning.ipynb
- python/vineyard/__init__.py
- python/vineyard/deploy/distributed.py
- python/vineyard/deploy/local.py
- python/vineyard/deploy/tests/test_local.py
In general, the init method handles three scenarios: no vineyardd exists; vineyardd already launched at an IPC socket;
mimic the local cluster mode. While the shutdown method can both close single or all the vineyardds.
Fixes #391
> Add the pair of init() and shutdown() methods to help new users to deploy vineyardd easily

- docs/notes/python_api.rst
- python/vineyard/__init__.py
- python/vineyard/deploy/__main__.py
- python/vineyard/deploy/local.py
- python/vineyard/deploy/tests/test_local.py
Follow-up fixes for #498, and renaming `default` to `current`, as there's no meaningful interpretation of `default`.
Fixes the use of `start_vineyardd` to match with changes in #498 as well.
Resolves #391
> Fixes usage of `start_vineyardd`, formatting, and docs.

- test/hashmap_test.cc
The test case seems failed to compile on Ubuntu with some version of apache arrow. I believe the issue has been fixed in upstream, in later version of apache arrow.
N/A
> Fixes the missing header.

- python/vineyard/data/dataframe.py
- python/vineyard/data/tests/test_dataframe.py
- python/vineyard/data/utils.py
Seems that `df. iteritems()` itself will trigger a shallow-copy on underlying dataframe. This pull request fixes that.
Fixes #503
> Reusing alreay-in-vineyard columns by inspecting blocks of dataframe.

- modules/graph/utils/partitioner.h
Update folly::dynamic hash partitioner: support `(label, id)` and use the id to get hash value
----------------------
https://github.com/alibaba/GraphScope/issues/804
> Update folly::dynamic hash partitioner: support `(label, id)` and use the id to get hash value

- modules/graph/utils/partitioner.h
> Fixes the invalid syntax in HashPartitioner for folly::Dynamic oids

- modules/basic/ds/arrow.h
- modules/basic/ds/arrow_utils.h
- modules/graph/fragment/arrow_fragment.h
- modules/graph/fragment/property_graph_utils.h
- src/client/ds/blob.cc
- src/server/server/vineyard_server.cc
- test/arrow_data_structure_test.cc
The behavior of "Resize + Advance" of FixedSizeBinaryBuilder changed in
arrow 5.0, leads to bugs in vineyard codebase.
It should be a bug in apache arrow, and hopefully being fixed in upstream.
See also: https://github.com/apache/arrow/commit/e990d177b1f1
Resolves #511.
> Workaround for bug from apache-arrow 5.0 in FixedSizeBinaryBuilder.

- .github/workflows/build-test.yml
- README.rst
- charts/vineyard/README.md
- docker/Dockerfile.ubuntu
- docs/notes/airflow.rst
- docs/notes/divein.rst
- docs/notes/getting-started.rst
- docs/notes/install.rst
- docs/notes/troubleshooting.rst
- python/vineyard/__main__.py
- python/vineyard/contrib/airflow/README.rst
- python/vineyard/deploy/distributed.py
- python/vineyard/deploy/etcd.py
- python/vineyard/deploy/local.py
- python/vineyard/deploy/utils.py
- python/vineyard/io/serialization.py
- setup.py
Vineyard now depends a python package called `etcd-distro` to install etcd without explicit `wget`. Now vineyard can be easy launched by
```python
python3 -m vineyard
```
Fixes #520
> Depends on etcd-distro, and make python3 -m vineyard work.

- python/vineyard/contrib/airflow/xcom/backend.py
Avoid using the syntax that are only available after python 3.9.
Fixes #566
> Use metaclass, rather than `property(classmethod(...))` to keep backwards compability.

- .github/workflows/docs.yaml
- python/vineyard/deploy/utils.py
- setup.py
To avoid false-negative result when virtual network interfaces (on ECS) is used.
None
> Check if port in use by listing all listened ports on all interfaces.

- python/vineyard/contrib/airflow/xcom/backend.py
Further addresses issue #566.
Fixes #566
> Drop the usage of metaclass in the XCom backend.

- python/vineyard/data/dataframe.py
- python/vineyard/data/tests/test_dataframe.py
Fixes the corner cases for resolving `pd.DataFrame` that contains `DatetimeArray`s.
Fixes #575
> Fixes resolvers for pd.DataFrame that contains `DatetimeArray`s.

- src/common/util/uuid.h
- src/server/services/meta_service.h
> Avoid using `__rdtsc` on non-x86_64 platforms (e.g., Apple M1).

- python/vineyard/__init__.py
- src/client/ds/object_factory.cc
- src/client/ds/object_factory.h
The `vineyard.envvars` doesn't restore the environemnt variables when exiting from the context, leading to bugs on Mac for learning engine in GraphScope.
See also alibaba/GraphScope#954
N/A
> Fixes `envvars` and make VINEYARD_USE_LOCAL_REGISTRY copying the original ones

- src/client/ds/blob.cc
- src/client/ds/blob.h
- src/client/ds/object_factory.cc
And move `Blob::Blob()` to `.h` file to make sure `vineyard::Blob` being registered on Mac.
> Don't reuse registry to avoid ABI conflicts.

- java/core/src/main/java/io/v6d/core/client/Client.java
- java/core/src/main/java/io/v6d/core/client/IPCClient.java
- java/core/src/main/java/io/v6d/core/client/ds/ObjectMeta.java
- java/core/src/main/java/io/v6d/core/common/util/InstanceID.java
- java/core/src/main/java/io/v6d/core/common/util/ObjectID.java
- java/core/src/main/java/io/v6d/core/common/util/Protocol.java
- java/core/src/test/java/io/v6d/core/client/IPCClientTest.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/Arrow.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/BooleanArray.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/BooleanArrayBuilder.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/BufferBuilder.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/FloatArrayBuilder.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/Int32Array.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/Int32ArrayBuilder.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/Int64ArrayBuilder.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/NullArray.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/NullArrayBuilder.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/RecordBatch.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/RecordBatchBuilder.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/SchemaBuilder.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/StringArray.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/StringArrayBuilder.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/Table.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/TableBuilder.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/columnar/ColumnarData.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/columnar/ColumnarDataBuilder.java
- java/modules/basic/src/test/java/io/v6d/modules/basic/arrow/ArrowTest.java
+ Implments the `client.persist` and `client.{put,get,drop}_name` API
+ Implments more array types and arrow table type.
Fixes #227
> Java SDK: persist, names and tables and more array types.

- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/BufferBuilder.java
- java/modules/basic/src/main/java/io/v6d/modules/basic/arrow/StringArrayBuilder.java
Use the true size, rather than capacity.
Fixes #227
> Fixes the buffer size when building arrow string arrays.

- python/client.cc
- python/vineyard/data/utils.py
To make sure the typename generated by Python is understandable in C++ SDK.
Fixes N/A
> Fixes the type convension between C++ and Python.

- src/common/util/status.h
- src/server/server/vineyard_server.cc
- src/server/util/meta_tree.cc
Return the invalid status, rather than aborting the vineyardd process.
Fixes N/A
> Fixes a fatal check in vineyard server.

- CMakeLists.txt
No need for `-std=c++17` when building tests.
See also https://github.com/nlohmann/json/issues/3203
> Fixes for backwards compatibility on Ubuntu 18.04.

- python/vineyard/core/utils.py
- python/vineyard/io/serialization.py
- python/vineyard/io/stream.py
For given typename in metadata `vineyard::DataFrameStream`, we should try `vineyard::DataFrameStream` first, then `vineyard::DataFrame`, as the resolver works in a prefix- mode.
N/A
> Find the longest match when possible.

- python/vineyard/data/arrow.py
- python/vineyard/data/tests/test_arrow.py
- test/typename_test.cc
+ Fixes the schema processing for `arrow::Schema`
+ Fixes the typename for `StringArray`.
N/A
> Fixes the arrow builder/resolver to exchange data with C++/Python.

- .github/workflows/build-vineyardd-and-wheels-macos.yaml
- docker/Dockerfile.vineyardd
- docker/pypa/Dockerfile.manylinux1-wheel
- src/server/vineyardd.cc
Use `v6d` to serve as the flags filter when showing help message to make sure `vineyardd --help` only shows informations that related to vineyardd binary.
Fixes #616
> Fixes the name matcher for flags when showing help information. 

- docs/notes/getting-started.rst
- modules/io/python/drivers/io/adaptors/dump_dataframe.py
- modules/io/python/drivers/io/adaptors/parse_bytes_to_dataframe.py
- modules/io/python/drivers/io/adaptors/parse_dataframe_to_bytes.py
- modules/io/python/drivers/io/adaptors/read_bytes.py
- modules/io/python/drivers/io/adaptors/read_orc.py
- modules/io/python/drivers/io/adaptors/read_vineyard_dataframe.py
- modules/io/python/drivers/io/adaptors/write_orc.py
- modules/io/python/drivers/io/adaptors/write_vineyard_dataframe.py
- modules/io/python/drivers/io/stream.py
- python/vineyard/io/byte.py
- python/vineyard/io/dataframe.py
- python/vineyard/io/recordbatch.py
- python/vineyard/io/tests/test_stream.py
- python/vineyard/launcher/script.py
- test/stream_test.cc
To keep backwards compatibility of ABIs.
N/A, follow-up work for #628.
> Fixes the typing of `DataframeStream`'s name and the "params_" field name

- .github/workflows/build-compatibility.yml
- charts/vineyard/Chart.yaml
- modules/io/python/drivers/io/adaptors/deserializer.py
- modules/io/python/drivers/io/adaptors/read_bytes_collection.py
- modules/io/python/drivers/io/adaptors/serializer.py
- modules/io/python/drivers/io/adaptors/write_bytes_collection.py
Python 3.8 (on Ubuntu 20.04) doesn't support such syntax.
N/A
> Fixes the typing hint under Python 3.8.

- modules/io/python/drivers/io/stream.py
- python/vineyard/launcher/script.py
Part of alibaba/GraphScope#1281.
The `join()` might be called for more than one times, if error occurs.
> Avoid duplicate `join()`, as `__del__` will call join as well.

- .github/workflows/build-test.yml
- CMakeLists.txt
- modules/io/python/drivers/io/stream.py
- modules/migrate/flags.h
- python/vineyard/io/stream.py
- src/server/async/socket_server.h
Expose the internal process handlers to the caller to make it joinable for inspecting errors.
Fixes alibaba/GraphScope#1281.
> Add an optional `handlers` arguments to allow capturing the underlying I/O errors.

- src/common/util/typename.h
See also: https://stackoverflow.com/questions/38499462/how-to-tell-clang-to-stop-pretending-to-be-other-compilers.
> Fixes the detection of GCC compiler.

- .github/workflows/build-vineyardd-and-wheels-macos.yaml
- modules/graph/fragment/property_graph_utils.h
Timestamp type has two field: unit and timezone.
Fixes https://github.com/v6d-io/v6d/issues/658
> Check if timestamp type using type id, rather than .Equals().

- .github/workflows/build-compatibility.yml
> Drop arrow 0.17.x check.

- src/client/client.cc
- src/client/client.h
- src/client/client_base.cc
- src/client/client_base.h
- src/common/util/protocols.cc
- src/common/util/protocols.h
- src/common/util/uuid.cc
- src/common/util/uuid.h
- src/server/async/ipc_server.cc
- src/server/async/ipc_server.h
- src/server/async/rpc_server.cc
- src/server/async/socket_server.cc
- src/server/async/socket_server.h
- src/server/server/vineyard_runner.cc
- src/server/server/vineyard_runner.h
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
- src/server/services/etcd_meta_service.h
- src/server/services/meta_service.h
- src/server/vineyardd.cc
- test/runner.py
- test/session_test.cc
Provide a new API called `open()`, which will create a separated session. Client in session A can not access the objects in session B. Vineyardd will also create separated socekts.
```
vineyard.sock.S0165a4df7aedb6be  
vineyard.sock.S0165a901b532b7f6
vineyard.sock.S0165a4df7b2a0838  
vineyard.sock.S0165a901b547b944
```
> Support session in Vineyard.

- src/client/client.cc
- src/client/client.h
- src/client/ds/blob.h
- src/client/ds/i_object.h
- src/client/ds/object_meta.h
- src/common/memory/payload.cc
- src/common/memory/payload.h
- src/common/util/base64.cc
- src/common/util/base64.h
- src/common/util/protocols.cc
- src/common/util/protocols.h
- src/common/util/uuid.cc
- src/common/util/uuid.h
- src/server/async/socket_server.cc
- src/server/async/socket_server.h
- src/server/memory/memory.cc
- src/server/memory/memory.h
- src/server/server/vineyard_runner.cc
- src/server/server/vineyard_runner.h
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
- src/server/services/etcd_meta_service.h
- test/external_test.cc
- test/runner.py
- test/session_test.cc
Provide a new ExternalBulkStore to support the plasma client.
- Add `ExternalBulkStore` to store a external object
- Add `ExternalClient` to send external object related request.
- Add `ExternalID`, `ExternalPayload`
- Add base64 encoder/decoder.
- Add protocols to process the ExternalBlob get/create.
**Use case:**
```c++
...
ExternalClient client;
client.Open(ipc_sokect);
client.CreateBlob(ExternalIDFromString("string_object_id"), size, external_size, blob);
...
```
closes #664
> [Compatibility] Add external bulk store for diverse ObjectID type.

- CMakeLists.txt
- src/server/server/vineyard_server.cc
Ensure all components get destructed, and disable rpc service for child service.
> Ensure the components are stopped during stopping the server to avoid memory leaks

- modules/graph/utils/table_shuffler_beta.h
- src/client/client.cc
- src/client/client.h
- src/client/ds/blob.cc
- src/client/io.cc
- src/client/io.h
- src/common/memory/payload.h
- src/common/util/protocols.cc
- src/common/util/protocols.h
- src/common/util/status.h
- src/server/async/socket_server.cc
- src/server/async/socket_server.h
- src/server/memory/memory.cc
- src/server/memory/memory.h
- src/server/memory/stream_store.cc
- test/external_test.cc
Add `is_sealed` flag for each blob. Before users call `client.Seal(object_id)` explicitly, they can not get the blob.
> [bugfix] Control visibility for unsealed blob.

- src/common/util/uuid.h
The original code doesn't work on MacOS with clang 13.
N/A
> Reinterpret cast to `uintptr_t`, rather than static cast to int type.

- modules/graph/utils/table_shuffler_beta.cc
- modules/graph/utils/table_shuffler_beta.h
Split impl away from header to avoid multiple definition when linking.
Fixes #693
> split table_shuffler_beta impl to cc file

- .github/workflows/build-test.yml
- setup_dask.py
Fixes current CI failures of dask cases.
> Restrict the version of click to `<8.1`.

- .github/workflows/build-test.yml
- src/common/util/env.cc
- src/server/memory/allocator.cc
Remount `/dev/shm` when possible if the maximum available shared memory is less than the specified value.
Fixes #699
> Try (sliently) remount when needed and when possible.

- src/server/async/socket_server.cc
- src/server/async/socket_server.h
Only one thread can access the `write_msgs_`, thus we do not need the lock.
> Remove write msg mutex for SocketConnection.

- .gitignore
- src/client/io.cc
- src/server/async/socket_server.cc
Fixes the CI failure in https://github.com/v6d-io/v6d/runs/5888312753?check_suite_focus=true
> Use send() rather than write() to avoid the SIGPIPE signal.

- CMakeLists.txt
Fixes CI failed on [GraphScope](https://github.com/alibaba/GraphScope/runs/6083691703?check_suite_focus=true)
Follow [CMAKE Doc](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html)
> LIBDIR: object code libraries (lib or lib64) 
On Debian, this may be lib/multiarch-tuple when CMAKE_INSTALL_PREFIX is /usr
I'm not sure whether has a better way to fix it. Welcome any comments.
> Correctly find vineyard package on Debian with multiarch support

- .gitignore
- python/vineyard/core/codegen/parsing.py
Fixes CI failure in https://github.com/v6d-io/v6d/actions/runs/2214966517
> Adapt the parsing in code generator to latest libclang.

- modules/graph/fragment/arrow_fragment.h
- modules/graph/fragment/arrow_fragment.vineyard-mod
- modules/graph/test/arrow_fragment_test.cc
The `{ie,oe}_lists` includes edges for outer vertices as well.
This pull revert the changes in #698 and fallback to the costly solution before #698 to make it correct.
I have left a `FIXME` to make sure it be optimized later.
> Fixes the compute of iv/ov num

- .github/workflows/build-vineyardd-and-wheels-linux.yaml
- .github/workflows/build-vineyardd-and-wheels-macos.yaml
Upload different Python versions to different zips otherwise the artifacts is unusable.
N/A
> Update wheels to different paths based on python version

- docs/notes/install.rst
Signed-off-by: waruto210 <wmc314@outlook.com>
add a dependency when compile on macOS
add a dependency when compile on macOS
no issue
> add a dep when compile on macos

- src/client/client.cc
- src/client/client.h
- src/common/util/protocols.cc
- src/common/util/protocols.h
- src/server/async/socket_server.cc
- test/array_two_clients_test.cc
- test/runner.py
This pull request adds a validation pass to verify the consistence of fds between client and server, before issuing the `recv_fd` calls.
This pull request prevents the client being blocked by `recv_fd` when there's actually no fd sent from the server.
Fixes #748
> Validate the fd set between client and server

- python/vineyard/contrib/airflow/README.md
- python/vineyard/contrib/airflow/etcd.yaml
- python/vineyard/contrib/airflow/values.yaml
- setup_airflow.py
- Add a reference `values.yaml` for helm deployment
- Add instructions about how to deploy airlfow on kubernetes with vineyard as the XCom backend.
Fixes #720
> Instructions for deploying airflow on Kubernetes with vineyard as backend

- .github/workflows/build-vineyardd-and-wheels-macos.yaml
> Build vineyard-migrate on MacOS with proper ABI tag

- misc/cpplint.py
- modules/graph/loader/arrow_fragment_loader.h
- src/common/util/status.h
The `__PRETTY_FUNCTION__` (as well as `__func__`, `__FUNCTION__`) cannot be too long otherwise the GCC will raise an internal error (segmentation fault).
Fixes #768
> Enhance the status check macro implementation.

- python/vineyard/core/codegen/cpp.py
- src/client/client.cc
- src/client/client.h
- src/client/client_base.cc
- src/client/client_base.h
- src/client/ds/i_object.cc
- src/common/memory/payload.cc
- src/common/memory/payload.h
- src/common/util/lifecycle.h
- src/common/util/protocols.cc
- src/common/util/protocols.h
- src/server/async/socket_server.cc
- src/server/async/socket_server.h
- src/server/memory/memory.cc
- src/server/memory/memory.h
- src/server/memory/usage.h
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
- src/server/services/meta_service.h
- test/deep_copy_test.cc
- test/delete_test.cc
- test/release_test.cc
- test/runner.py
**Goal：**
- On the server-side, maintain a cold object list. To this end, a reference count is added to the `payload`, and when the reference count is 0, it will be recorded in the `cold_object_list`.
- The assumptions to be satisfied: the blob in the `cold_object_list` are not in-use by anyone, and it is safe to do something on them.
- `cold_object_list` is just a record and does not trigger evict/spill/checkpoint. (provides opportunities for these behaviors)
**Design：**
- Track reference counts on `blob` only.
- An unsealed `blob` cannot be counted as a cold object at any time
- There is a cache on the client-side to cache the previously requested blob and keep the availability of these blobs consistent with the server-side
- For the client-side, a client will cache the reference of a …
> Maintain cold blobs in vineyardd.

- src/common/util/uuid.h
As titled. The memory address becomes invalid after reloading a spilled blob.
> Change `blob_id` from memory address to randomly generated number.

- .github/workflows/build-repo-tarball.yaml
- misc/git-archive-submodules.sh
Add the github action script for building a source tarball with submodules.
See also #757.
> Add the build-repo-tarball CI to github actions

- modules/io/python/drivers/io/adaptors/deserializer.py
- modules/io/python/drivers/io/adaptors/parse_dataframe_to_bytes.py
- modules/io/python/drivers/io/adaptors/read_bytes.py
- modules/io/python/drivers/io/adaptors/read_bytes_collection.py
- modules/io/python/drivers/io/adaptors/serializer.py
- python/pybind11_utils.cc
- python/vineyard/io/byte.py
- python/vineyard/io/dataframe.py
- Fixes the check in `copy_memoryview_to_memoryview`: avoid errors when copying empty blob
- Add severals checks to avoid empty chunks during building a byte stream.
Fixes #781
> Avoid errors when build empty chunks into a byte stream

- CMakeLists.txt
- modules/basic/CMakeLists.txt
- modules/graph/CMakeLists.txt
- modules/io/CMakeLists.txt
Avoid override existing headers for such libraries on system.
Part of the effort to address #642.
> CMake: install submodules to include/vineyard/contrib to avoid conflicts.

- modules/io/python/drivers/io/adaptors/deserializer.py
A compressed blob might be sent to a stream as several chunks.
Follow-up work for #784
> Fixes decompressing un-continuous chunks of a blob. 

- CMakeLists.txt
as titled. The error occurs when building `_C` extension module with `-DCMAKE_BUILD_TYPE=Debug`.
N/A
> Avoid the "error: unsupported load command (cmd=0x80000034" error for llvm<=14

- python/client.cc
- python/vineyard/_vineyard_docs.py
- src/client/client_base.cc
- src/client/client_base.h
It will be used when we need to create a global object with several local parts as place holder.
N/A
> Add a Client::CreateMetaData overloading to allow placing metadata to specified instance

- modules/io/python/drivers/io/adaptors/deserializer.py
- modules/io/python/drivers/io/adaptors/read_bytes_collection.py
- modules/io/python/drivers/io/adaptors/serializer.py
- modules/io/python/drivers/io/adaptors/write_bytes_collection.py
- python/vineyard/io/utils.py
Use `cpu_count()` to leveraging multi-threading serilaization/deserilization.
N/A
> Use cpu_count() as the default parallelism for IO serialization/deserialization

- CMakeLists.txt
See also the trick from https://stackoverflow.com/questions/38983007/remove-messages-from-an-included-cmakelist-txt
N/A
> Erase the misleading tbb warning raised from intel-tbb directory.

- vineyard-config.in.cmake
As titled. to make sure `VINEYARD_INCLUDE_DIRS` behaves as expected.
N/A
> Add the contrib directory to vineyard include dirs.

- CMakeLists.txt
- src/server/memory/usage.h
- test/lru_test.cc
- test/runner.py
In this PR, I will build a LRU for ColdObjectTracker, to keep track of the oldest unused `Obj ID`.
Mainly prepare for later implementation of `spill`.
In detail, I sketched a LRU by a `doubly-linked list` and  `hash table` -- A classic implementation of LRU. Due to the limitation of currently used cpp version (C++14), the synchronize mechanism I firstly choosed was `std::shared_mutex` in C++17, then I changed to `std:: shared_timed_mutex`, but they should have no difference in our scenario.  [see here](https://stackoverflow.com/questions/40207171/why-shared-timed-mutex-is-defined-in-c14-but-shared-mutex-in-c17)
Fixes #724(partially) and https://github.com/v6d-io/v6d/issues/739
TODOs
------- …
> Support lru in `ColdObjectTracker`

- modules/graph/utils/context_protocols.cc
- modules/graph/utils/context_protocols.h
- modules/graph/utils/grape_utils.h
C++14 requires both definition and declaration for static constexpr constant.
N/A
> Fixes the link failure under C++14. 

- LICENSE
- NOTICE.txt
- README.rst
- modules/basic/CMakeLists.txt
- modules/basic/ds/hashmap.h
- modules/basic/ds/hashmap.vineyard-mod
- modules/graph/fragment/arrow_fragment.h
- modules/graph/fragment/arrow_fragment.vineyard-mod
- modules/graph/fragment/property_graph_utils.h
- thirdparty/wyhash/wyhash.hpp
As titled, to reduce the memory overhead of hashmap for certain data distributions.
N/A
> Enable optional wyhash for hashmap.

- src/server/memory/usage.h
The `std::shared_timed_mutex` is not available on lower version of MacOS.
N/A
> Fixes the compatibility issue on MacOS.

- CMakeLists.txt
Add an option `USE_LIBUNWIND` to dedice whether to find libunwind in the build environment.
Fixes #808
> Makes libunwind as an optional dependency.

- modules/graph/fragment/arrow_fragment.h
- modules/graph/fragment/arrow_fragment.vineyard-mod
The issue would be caused by some certain version of AppleClang.
See also https://stackoverflow.com/questions/27109545/macosx-thread-explicitly-marked-deleted
The error message is
```
/usr/local/lib/cmake/vineyard/../../../include/vineyard/graph/fragment/arrow_fragment.vineyard.h:1536:10: note: in instantiation of function template specialization 'vineyard::ThreadGroup::AddTask<(lambda at /usr/local/lib/cmake/vineyard/../../../include/vineyard/graph/fragment/arrow_fragment.vineyard.h:1522:17) &, std::reference_wrapper<vineyard::Client>>' requested here
tg.AddTask(fn, std::ref(client));
^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/type_traits:1916:5: note: '~__nat' has been explicitly marked deleted here
~__nat() = delete;
^
In file included from …
```
> Fix the bug that macosx thread explicitly marked deleted

- src/client/client.cc
- src/client/client.h
- src/client/ds/blob.cc
- test/runner.py
After #839 the objec id for `vineyard::Blob` no longer implies the pointer semantic. To keep track of the shared memory pieces inside the given client, we maintain a blob set and query over the blob set for give raw pointer to resolve the corresponding blob objects.
Follow-up work for #839.
> Revisit the implementation of is_shared_memory testing

- python/vineyard/deploy/utils.py
Add `RuntimeError` to the catch list as well.
Fixes #846.
> On M1 mac the error is a RuntimeError.

- charts/vineyard/values.yaml
- docs/notes/data-accessing.rst
- docs/notes/deploy-docker.rst
- docs/notes/deploy-kubernetes.rst
- docs/notes/python-api.rst
- misc/release-docker.sh
- modules/graph/loader/arrow_fragment_loader.cc
- python/vineyard/contrib/airflow/docker/Dockerfile
- python/vineyard/contrib/airflow/values.yaml
- python/vineyard/deploy/__init__.py
- python/vineyard/deploy/etcd.py
- python/vineyard/deploy/kubernetes.py
- python/vineyard/deploy/local.py
- python/vineyard/deploy/utils.py
- python/vineyard/deploy/vineyard.yaml.tpl
- src/common/util/env.h
- Revisit the vineyard deployment template to fixes the memory unit error
- Create namespace if the namespace not found
- Add docuementation for deploying using the Python API
- Move the vineyard docker registry to `vineyardcloudnative/vineyardd`
Fixes #851 and fixes #852
> Revisit the python API and documentation for Kubernetes deployment

- src/server/memory/allocator.cc
- src/server/memory/malloc.cc
Jemalloc's arean saves internal metadata inside the arena as well.
Fixes #862
> Leave spaces for jemalloc's arena metadata and internal padding

- modules/io/io/local_io_adaptor.cc
set `options.include_header=true`
Fixes #864
> add header row for local_io_adaptor

- src/server/async/socket_server.cc
- src/server/async/socket_server.h
- src/server/memory/memory.h
- src/server/memory/usage.h
- src/server/services/etcd_meta_service.cc
- src/server/services/local_meta_service.cc
- src/server/services/local_meta_service.h
- src/server/services/meta_service.cc
- src/server/services/meta_service.h
The `SocketConnection` do something like `Release` on `Stop()`, which requires the blukstore keep alive other wise there will be a data race contention between the `SocketConnection::Stop()` and `BulkStore::~BulkStore()`.
Fixes #842
> Add a shared_ptr reference of bulkstore in the SocketConnection

- src/server/async/ipc_server.cc
- src/server/async/ipc_server.h
- src/server/async/rpc_server.cc
- src/server/async/rpc_server.h
- src/server/async/socket_server.cc
- src/server/async/socket_server.h
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
By making sure no longer trying to add new socket connection after the `SocketServer` itself bas been stopped/destructed.
Fixes #884.
> Resolves the data race condition in the destruction of SocketServer.

- docs/notes/deploy-locally.rst
- docs/notes/getting-started.rst
- src/common/util/status.h
- src/server/async/ipc_server.cc
- src/server/async/socket_server.cc
- src/server/memory/usage.h
Fixes a bug about using `--socket ./socket` on Linux as well.
Fixes #883
> Use more meaningful message when failed to create the IPC socket

- src/client/client.cc
- src/client/rpc_client.cc
- src/common/util/status.h
as titled. Adding two macros `RETURN_NULL_ON_ERROR` and `RETURN_NULL_ON_ASSERT` as well.
> Return nullptr instead of throw exceptions in getobject.

- .github/workflows/build-compatibility.yml
- docker/vineyardd/Dockerfile.alpine-builder
- modules/basic/ds/arrow_utils.cc
Compiling with apache-arrow 9.0.0.
Fixes #894
> Keeps compatible with apache-arrow 9.0.0.

- src/client/client_base.cc
- src/common/util/json.h
- src/common/util/macros.h
- src/common/util/status.h
- src/server/server/vineyard_server.cc
- src/server/services/meta_service.cc
- refactor the `CATCH_JSON_ERROR` macro to avoid creating a lambda function
- catch the possbile `std::invalid_argument` exception (triggerred by `std:: stoull`) in `putVal` with a json pointer
- prevent crash when the given metadata contains invalid keys.
Fixes #913
> Catch the json exception, especially inserting using json_pointer

- test/runner.py
> Address a missing import error in Python 3.8.

- src/common/memory/mimalloc.h
- src/server/memory/dlmalloc.cc
- src/server/memory/malloc.cc
- src/server/memory/malloc.h
- src/server/memory/mimalloc.cc
as titled.  Move the `mmap` operation to the common place.
N/A
> Unify the implementation of "mmap/munmap" in different allocators to avoid duplication

- CONTRIBUTING.rst
- docker/Dockerfile.vineyard-python
- docker/dev/Dockerfile.dev
- docker/dev/build_scripts/install-arrow.sh
- docker/dev/build_scripts/install-deps.sh
- docker/dev/build_scripts/install-libgrape-lite.sh
- docker/dev/build_scripts/install-miscs.sh
- docker/dev/build_scripts/requirements.txt
- Add docker image: vineyardcloudnative/vineyard-python
- Add docker image: vineyardcloudnative/vineyard-dev
N/A
> Add docker images for vineyard installed and for vineyard developing

- modules/basic/ds/arrow_utils.cc
- modules/graph/fragment/property_graph_utils.h
Cast boolean array to int array, as boolean array is not directly indexable when accessing data from FFI.
Fixes #926
> Cast boolean array to int array.

- CMakeLists.txt
- src/common/util/protocols.cc
- src/server/memory/allocator.cc
- src/server/memory/allocator.h
- src/server/memory/memory.cc
- src/server/memory/memory.h
- src/server/server/vineyard_server.cc
- src/server/util/spec_resolvers.cc
Build against dlmalloc and mimalloc at the same time, and add a runtime flag to select the allocator at startup.
> Enable switch allocator using command line flags.

- src/client/client.cc
- src/common/util/lifecycle.h
- src/common/util/protocols.cc
- src/common/util/status.cc
- src/common/util/status.h
- src/server/memory/usage.h
- Add `+=` operator to `Status`
- Skip unsealed blobs in `MarkAsCold` to avoid possible crash.
Resolves #932
> MarkAsCold: exclude "unsealed" blobs.

- src/common/util/status.h
- src/server/util/meta_tree.cc
as titled. Make sure `client.clear()` must success as well.
Fixes #936
> Ignore invalid metadata entries in `client.ListData()`.

- src/server/services/etcd_meta_service.cc
- src/server/services/etcd_meta_service.h
- src/server/util/etcd_launcher.cc
- src/server/util/etcd_launcher.h
- Generate a temporary directory for launching etcd from vineyard, as destroy the directory when exit.
Fixes #935
> Etcd launcher: use a temporary directory to data for each launching.

- src/client/client.cc
- src/client/client.h
- src/common/util/lifecycle.h
- src/server/async/socket_server.cc
- src/server/memory/memory.h
- src/server/memory/usage.h
- src/server/util/etcd_launcher.cc
- src/server/util/proc.cc
Calling `shared_from_this()` on a _reference_ of child class is not ok. This pull request renames `Self()` to `self()` as well as it is a private method.
Fixes #953
> Fixes a incorrect of shared_from_this in CRTP

- CMakeLists.txt
- LICENSE
- NOTICE.txt
- python/pybind11_utils.cc
- src/client/ds/blob.cc
- src/common/memory/memcpy.h
- test/lru_test.cc
Note that we did't noticed a performance gap, but using a better one from a better project like ClickHouse shouldn't a bad idea.
Related to #721.
> Use the faster memcpy implementation from the ClickHouse project

- src/server/memory/usage.h
The lock is declared, but never lock the mutex......
Fixes #970
> Lock the mutex when declare the lock

- modules/basic/ds/hashmap.h
- modules/basic/ds/hashmap.vineyard-mod
- modules/graph/vertex_map/arrow_vertex_map_builder.h
- test/hashmap_largefile_test.cc
- test/typename_test.cc
LOG the memory usage of vertex map as well.
Fixes #973
> Use wyhash as the hash function when building the hashmap to reduce memory usage

- test/CMakeLists.txt
Avoid building failure if tbb is not found (tbb is only required for building vineyardd).
N/A, credit to @doudoubobo
> Disable the lru_test if tbb is not found

- modules/graph/fragment/graph_schema.cc
Graphscope placed too much assumption on the property name string, especially in the python code and java code. There's no easy to make things better thus I decide to revert the change in https://github.com/v6d-io/v6d/pull/975
N/A
> Restore the changes for the 'name' of property types

- CMakeLists.txt
- modules/basic/CMakeLists.txt
- modules/graph/CMakeLists.txt
- modules/hosseinmoein-dataframe/CMakeLists.txt
- modules/io/CMakeLists.txt
- modules/malloc/CMakeLists.txt
This will help to reduce the binary artifact size, while keep the ability of debugging if error/crash occurs.
Vineyardd size comparison:
- RelWithDebInfo: 131+M
- Release: 11M
- RelWithDebInfo for vineyardd: 78M
N/A
> Add debuginfo only for vineyard components

- .github/workflows/vineyard-operator.yaml
- k8s/Makefile
- k8s/config/manager/kustomization.yaml
- k8s/test/e2e/serialize/e2e.yaml
- k8s/test/e2e/spill/e2e.yaml
- k8s/test/e2e/vineyardd/e2e.yaml
- misc/release-docker.sh
As titled. We have two images now, namely `vineyard-operator` and `vineyard-controller`, which may confuse users. Based on this, we decide to reserve the `vineyard-operator` image and delete the `vineyard-controller` image.
> Delete the vineyard controller image

- .github/workflows/vineyard-operator.yaml
In the pr, we'll release the nightly version of vineyard-operator in every pr and push the release version of vineyard-operator when releasing the vineyardd.
> Release vineyard-operator in ci

- modules/graph/fragment/arrow_fragment.h
- modules/graph/fragment/arrow_fragment_modifier.h
- modules/graph/vertex_map/arrow_vertex_map.h
- modules/graph/vertex_map/arrow_vertex_map_builder.h
Resizing the vectors in builder before setitem to ensure the "resize()" operation won't happen at the same time, to prevent data race in #1004.
Fixes #1004
> Ensure no resize() operation happens at the same time between different worker threads

- src/server/util/spec_resolvers.cc
- src/server/vineyardd.cc
Disable the coredump by default, and can be enabled with `-coredump` or `--coredump=true`.
Fixes #1009
> Disable the coredump by default and add an command line option to enable it

- src/server/async/ipc_server.cc
- src/server/async/socket_server.cc
- src/server/memory/gpu/gpuallocator.cc
- src/server/memory/memory.cc
- src/server/memory/usage.h
- src/server/server/vineyard_runner.cc
- src/server/server/vineyard_server.cc
- src/server/services/meta_service.h
Print user errors, print log only when a high verbosity has been enabled.
Fixes #1008
> Avoid print too much logs

- .dockerignore
- docker/Dockerfile.vineyard-python-dev
- docker/Makefile
The pr is to add a dockerfile for building a minimal python client image for vineyard.
Why we need this?
During development, if we update the code related to the vineyard python client, I think it's better to have an existing dockerfile to build the python-dev image.
> Add Dockerfile for vineyard python-dev

- README.rst
As titled. The docker hub link is important for users, I think.
> Add Docker Hub label in the root readme

- python/client.cc
- src/client/rpc_client.cc
- src/client/rpc_client.h
- src/common/util/protocols.cc
- src/common/util/protocols.h
- src/server/async/ipc_server.cc
- src/server/async/ipc_server.h
- src/server/async/rpc_server.cc
- src/server/async/rpc_server.h
- src/server/async/socket_server.cc
- src/server/async/socket_server.h
- src/server/server/vineyard_server.cc
Resolves the leaving TODO in the RPC part when initializing a new session.
N/A
> RPC server for sessions: share the same port and switch to child session when needed

- modules/basic/ds/tensor.vineyard-mod
- modules/graph/fragment/property_graph_types.h
- modules/graph/test/vertex_map_string_test.cc
- modules/graph/utils/table_shuffler_beta.h
- modules/graph/vertex_map/arrow_vertex_map.h
- modules/graph/vertex_map/arrow_vertex_map_builder.h
Use `std::string_view` instead of `arrow::util::string_view` with Apache Arrow 10.0.0 or later.
Fixes #1029
> [FEATURE-1029] Add support for Apache Arrow 10.0.0

- docker/Dockerfile.vineyard-python-dev
When I run `make -C docker build-python-dev`, get the following error.
```shell
-- Found ZLIB: /usr/local/lib/libz.a (found version "1.2.12") 
CMake Error at /usr/local/lib/cmake/Boost-1.75.0/BoostConfig.cmake:141 (find_package):
Could not find a package configuration file provided by "boost_regex"
(requested version 1.75.0) with any of the following names:
boost_regexConfig.cmake
boost_regex-config.cmake
Add the installation prefix of "boost_regex" to CMAKE_PREFIX_PATH or set
"boost_regex_DIR" to a directory containing one of the above files.  If
"boost_regex" provides a separate development package or SDK, be sure it
has been installed.
Call Stack (most recent call first):
/usr/local/lib/cmake/Boost-1.75.0/BoostConfig.cmake:258 …
```
> Fix the error in Dockerfile.vineyard-python-dev

- .github/workflows/build-compatibility.yml
as titled. The ubuntu 18.04 runner will be removed in the near future.
N/A
> Move to ubuntu 20.04 and give up ubuntu 18.04 support

- modules/io/python/drivers/io/kube_ssh.sh
- modules/io/python/drivers/io/ssh.sh
Use `bash -lc` to load rc files.
N/A
> Source more rf-files and use bash -lc when starting IO drivers

- .github/workflows/vineyard-operator.yaml
- charts/vineyard-operator/templates/webhooks.yaml
- k8s/config/rbac/role.yaml
- k8s/config/webhook/namespace_selector_patch.yaml
- k8s/controllers/k8s/operation_controller.go
- k8s/operator/operation_webhook.go
- k8s/pkg/operation/assembly.go
- k8s/pkg/operation/interface.go
- k8s/pkg/operation/repartition.go
- k8s/schedulers/scheduling.go
- k8s/schedulers/schedulingstate.go
- k8s/templates/operation/dask-repartition.yaml
- k8s/test/e2e/assembly/distributed-assembly-e2e.yaml
- k8s/test/e2e/repartition/dask-repartition-e2e.yaml
- k8s/test/e2e/repartition/dask-repartition-operation/Dockerfile.repartition
- k8s/test/e2e/repartition/dask-repartition-operation/Makefile
- k8s/test/e2e/repartition/dask-repartition-operation/dask-repartition.py
- k8s/test/e2e/repartition/repartition-dask-helm-values.yaml
- k8s/test/e2e/repartition/repartition-demo/Dockerfile.dask-worker-with-vineyard
- k8s/test/e2e/repartition/repartition-demo/Dockerfile.job1
- k8s/test/e2e/repartition/repartition-demo/Dockerfile.job2
- k8s/test/e2e/repartition/repartition-demo/Makefile
- k8s/test/e2e/repartition/repartition-demo/job1.py
- k8s/test/e2e/repartition/repartition-demo/job2.py
- k8s/test/e2e/repartition/repartition-job-config.yaml
- k8s/test/e2e/repartition/repartition-job.yaml
- k8s/test/e2e/verify/partition.yaml
The pr mainly do the following things:
* Add dask repartition operation logic.
* Add End-to-End repartition demo based on dask.
* Update webhook NamespaceSelector from `assembly-injection` to `operation-injection`.
> Add dask repartition operation to pluggable drivers.

- modules/graph/fragment/property_graph_utils.h
Pass value would affect  performance when outer vertex map is large.
> [BugFix] Replace pass value to pass reference

- src/common/util/protocols.cc
Directly accessing `root["type"]` would be an exception if the message is an error message.
N/A
> Use the `CHECK_IPC_ERROR` rather than `RETURN_ON_ASSERT` to avoid crash on failures

- modules/basic/ds/tensor.vineyard-mod
> String tensors requires arrow.vineyard.h to work.

- modules/graph/fragment/arrow_fragment_builder_impl.h
- modules/graph/fragment/property_graph_utils.h
- modules/graph/fragment/property_graph_utils_impl.h
- modules/graph/fragment/property_graph_utils_uint32.cc
- modules/graph/fragment/property_graph_utils_uint64.cc
Avoid keeping both COO, CSR and CSC in memory at the same time.
Further optimization over #1102 and address #974.
> Use a CSR generation implementation with less memory footprint

- modules/basic/ds/arrow_shim/concatenate.cc
- python/vineyard/core/codegen/parsing.py
- python/vineyard/data/arrow.py
Fixes a include error with arrow 6.0 as well.
> Fixes parsing flags when using higher version of apache-arrow

- python/vineyard/core/resolver.py
- python/vineyard/deploy/tests/test_migration.py
- src/client/ds/blob.cc
- src/client/ds/remote_blob.cc
- src/server/memory/usage.h
- src/server/util/compressor.cc
- src/server/util/remote.cc
The change will be included in the next release of Python wheels. As a workround, you could do
```python
obj = client.get(client.migrate(object_id))
```
with current version.
Fixes N/A
> Expose the `fetch` argument to python API

- k8s/test/e2e/assembly-demo/assembly-distributed.py
- k8s/test/e2e/assembly-demo/assembly-job2.py
- k8s/test/e2e/assembly-demo/distributed-job2.py
- k8s/test/e2e/assembly-demo/distributed-job3.py
- k8s/test/e2e/failover-demo/build-distributed-object-step2.py
- k8s/test/e2e/failover-demo/get-distributed-object.py
- k8s/test/e2e/failover-demo/get-local-object.py
- k8s/test/e2e/repartition-demo/dask-repartition.py
- k8s/test/e2e/repartition-demo/job2.py
- k8s/test/e2e/workflow-demo/job2.py
- modules/io/python/drivers/io/adaptors/parse_bytes_to_dataframe.py
- modules/io/python/drivers/io/adaptors/read_orc.py
- modules/io/python/drivers/io/adaptors/read_parquet.py
- modules/io/python/drivers/io/adaptors/read_vineyard_dataframe.py
- modules/io/python/drivers/io/stream.py
- modules/io/python/drivers/io/tests/test_open.py
- python/vineyard/cli.py
- python/vineyard/data/dataframe.py
- python/vineyard/io/stream.py
- python/vineyard/launcher/script.py
Add `accumulate=False/True` option to `vineyard.io.open()` to read CSV/Parquet/ORC directly to global dataframes.
Fixes #1136
> Implements accmulate support for vineyard.io.open()

- modules/io/python/drivers/io/adaptors/parse_bytes_to_dataframe.py
- modules/io/python/drivers/io/adaptors/read_orc.py
- modules/io/python/drivers/io/adaptors/read_parquet.py
Mixing recordbatch into global dataframe would cause some problems in mars integration.
Credited to @dashanji.
> Make sure use dataframe in GlobalDataFrame

- modules/basic/ds/arrow.cc
- modules/basic/ds/arrow.h
- modules/basic/ds/arrow_utils.h
- modules/graph/fragment/arrow_fragment.h
- modules/graph/fragment/arrow_fragment.vineyard-mod
- modules/graph/fragment/arrow_fragment_builder_impl.h
- modules/graph/fragment/arrow_fragment_impl.h
- modules/graph/fragment/property_graph_utils.h
- modules/graph/fragment/property_graph_utils_impl.h
- modules/graph/fragment/property_graph_utils_uint32.cc
- modules/graph/fragment/property_graph_utils_uint64.cc
- modules/graph/loader/arrow_fragment_loader.cc
- modules/graph/loader/arrow_fragment_loader_impl.h
- src/client/client.cc
- src/client/ds/object_meta.cc
- src/client/ds/object_meta.h
- src/common/util/env.cc
as titled, avoid copying the "offset" arrays.
N/A
> Less copy between in-process memory and vineyard during building a fragment

- .github/workflows/vineyard-operator.yaml
- k8s/Makefile
- k8s/test/e2e/vineyardd.yaml
as titled, avoid using stale image to run CI.
Address issue discussed in https://github.com/v6d-io/v6d/pull/1161#issuecomment-1408128311
> Kubernetes CI: build latest vineyardd image from source

- k8s/cmd/commands/flags/global_flags.go
- k8s/cmd/commands/manager/manager.go
- k8s/cmd/commands/sidecar/inject.go
- k8s/cmd/main.go
- Fixes the errors about dump-usage flag parsing
> Fixes the error parsing issues in the vineyardctl command line tool

- modules/graph/fragment/arrow_fragment_impl.h
- modules/graph/fragment/graph_schema.cc
- modules/graph/fragment/graph_schema.h
> Fixes project on fragments that already been projected

- modules/basic/ds/arrow.cc
- modules/basic/ds/dataframe.cc
- modules/basic/ds/dataframe.h
- modules/basic/ds/tensor.cc
- modules/basic/ds/tensor.h
- Add `AddPartitions`, `LocalPartitions` back
- Add backwards compabitility with `SchemaProxy`.
> Collections, tables, and schema: keep backwards compatibility

- python/vineyard/deploy/_cobra.py
While executing the following code, get some errors as follows.
```
vineyard.deploy.vineyardctl.deploy.vineyard_deployment(cre
...: ate_namespace=True,wait=False)
2023-03-12T17:31:50.859+0800    ERROR   Expects no positional arguments   {"error": "unknown command \"false\" for \"vineyardctl deploy vineyard-deployment\""}
github.com/v6d-io/v6d/k8s/pkg/log.Logger.Fatal
/opt/caoye/v6d/k8s/pkg/log/log.go:81
github.com/v6d-io/v6d/k8s/pkg/log.Fatal
/opt/caoye/v6d/k8s/pkg/log/log.go:114
github.com/v6d-io/v6d/k8s/cmd/commands/util.AssertNoArgs
/opt/caoye/v6d/k8s/cmd/commands/util/arg.go:26
github.com/v6d-io/v6d/k8s/cmd/commands/deploy.glob..func4
/opt/caoye/v6d/k8s/cmd/commands/deploy/deploy_vineyard_deployment.go:70 …
```
> Fix the error when parsing and executing bool variables in the python wrapper of vineyarctl

- modules/graph/tools/graph_loader.cc
- setup_bdist.py
When building `bdist_wheel` under arm-based linux, the resulting tag would be
`vineyard_bdist-0.13.3-py3-none-manylinux2010_aarch64.whl`, where as `manylinux2010_aarch64` is not a valid tag, makes it an invalid wheels. 
Here's an description of tags in [pypa/manylinux](https://github.com/pypa/manylinux)
```
PEP 571 defined manylinux2010_x86_64 and manylinux2010_i686 platform tags and the wheels were built on Centos6. Centos6 reached End of Life (EOL) on November 30th, 2020.
PEP 599 defines the following platform tags:
manylinux2014_x86_64
manylinux2014_i686
manylinux2014_aarch64
manylinux2014_armv7l
manylinux2014_ppc64
manylinux2014_ppc64le
manylinux2014_s390x
```
N/A
> Use manylinux 2014 instead of 2010

- modules/io/python/drivers/io/adaptors/README.rst
- modules/io/python/drivers/io/adaptors/read_bytes.py
- modules/io/python/drivers/io/adaptors/read_bytes_collection.py
- modules/io/python/drivers/io/adaptors/read_orc.py
- modules/io/python/drivers/io/adaptors/read_parquet.py
- modules/io/python/drivers/io/stream.py
- modules/io/python/drivers/io/tests/test_open.py
- Enable storage options be passed through parameter `storage_options`, or from the URI directly, e.g. `hdfs://<ip>:<port>/path/to/file`
- Leverage methods from fsspec to handle glob patterns.
> Enable pass storage options from both kw and path

- modules/graph/CMakeLists.txt
add dircetory of string_view to ligrape target_include_directories
Fixes #1288
> Fixes the issue that `string_view` header of submodule libgrape-lite cannot be referenced

- modules/graph/CMakeLists.txt
- modules/graph/loader/gar_fragment_loader.h
- modules/graph/loader/gar_fragment_loader_impl.h
- modules/graph/test/arrow_fragment_gar_test.cc
- modules/graph/writer/arrow_fragment_writer.h
- modules/graph/writer/arrow_fragment_writer_impl.h
- When build the vineyard with GAR, make the GAR library `PRIVATE` that the system that use vineyard(like GraphScope) no need to the gar library
- Replace include gar headers with some forward declararions
> Make GAR library as `PRIVATE` and replace gar header include with forward declarations

- .github/workflows/build-test-graph.yml
- docker/Makefile
- docker/dev/Dockerfile.dev
- docker/dev/build_scripts/install-arrow.sh
- docker/dev/build_scripts/install-deps.sh
- docker/dev/build_scripts/install-miscs.sh
- docker/dev/build_scripts/requirements.txt
- src/server/memory/allocator.cc
- src/server/memory/malloc.cc
- Use `memfd_create()` on Linux, verified both on Docker and on Kubernetes (between pods)
- Fixes the `vineyard-dev` docker image
Fixes #1292
> Use memfd_create(2) for sharable file descriptor allocation

- src/server/server/vineyard_server.cc
- src/server/util/kubectl.cc
- src/server/util/kubectl.h
- src/server/util/meta_tree.cc
The CRDs should be dropped from Kubernetes when we deleting the objects from vineyard. 
- Fixes #1174
- See also: https://github.com/v6d-io/v6d/issues/1150#issuecomment-1413187626
> Delete CRDs when deleting objects from vineyard

- python/vineyard/data/arrow.py
- python/vineyard/data/tensor.py
std::string encoding without 'utf-8' cannot resolve with pa.large_string, 
use pa.large_binary to resolve it.
my local test is passed.
Fixes #1312
> Fixes issue1312: resolve std::string with pa.large_binary

- docs/notes/developers/faq.rst
Fix typo in the documentation
No specific issue
> [Docs] Fix typo in docs of PersistentVolume

- go/vineyard/pkg/common/memory/fling.cc
- python/vineyard/_C.pyi
- python/vineyard/conftest.py
- python/vineyard/core/builder.py
- python/vineyard/core/resolver.py
- python/vineyard/core/tests/test_client.py
- python/vineyard/deploy/tests/test_distributed.py
- setup.py
- src/client/client.cc
- src/client/client_base.cc
- src/client/client_base.h
- src/client/ds/blob.cc
- Fixes the check about memory-mapped client fd
- Add testcases for concurrent blob creation
- Add necessary locks for thread safe.
Related to #1324
> Mitigate the race condition about send/recv file descriptors

- docs/notes/cloud-native/vineyard-operator.rst
- k8s/apis/k8s/v1alpha1/vineyardd_types.go
- k8s/cmd/README.md
- k8s/cmd/commands/deploy/deploy_vineyard_deployment.go
- k8s/cmd/commands/flags/sidecar_flags.go
- k8s/cmd/commands/sidecar/inject.go
- k8s/cmd/commands/util/template.go
- k8s/config/crd/bases/k8s.v6d.io_sidecars.yaml
- k8s/config/crd/bases/k8s.v6d.io_vineyardds.yaml
- k8s/config/manager/kustomization.yaml
- k8s/controllers/k8s/sidecar_controller.go
- k8s/controllers/k8s/vineyardd_controller.go
- k8s/pkg/config/labels/labels.go
- k8s/pkg/injector/sidecar_injector.go
- k8s/pkg/templates/etcd/etcd.yaml
- k8s/pkg/templates/etcd/service.yaml
- k8s/pkg/templates/sidecar/injection-template.yaml
- k8s/pkg/templates/vineyardd/deployment.yaml
- k8s/pkg/templates/vineyardd/etcd-service.yaml
- k8s/pkg/templates/vineyardd/service.yaml
- k8s/pkg/templates/vineyardd/spill-pv.yaml
- k8s/pkg/templates/vineyardd/spill-pvc.yaml
- k8s/test/e2e/sidecar/e2e.yaml
* Support setting up the memory and cpu of vineyard sidecar container.
* Support applying the resources during injection such as etcd cluster.
* Delete the cmd and prefix of etcd in the sidecar template.
* Use a json string to output all manifests when set up the output as json format.
* Add OwnerReferences for the injected manifests in the vineyardctl inject command.
Fixes #1303
> Improve the vineyardctl inject command for integrating with GraphScope

- charts/vineyard-operator/values.yaml
- k8s/Makefile
As titled. After uninstalling the vineyard operator, the secret for related webhooks will be deleted automatically.
> Add the enable-certificate-owner-ref to the subchart of cert-manager.

- python/vineyard/deploy/utils.py
vineyardctl_path was reference before assignment in  https://github.com/v6d-io/v6d/blob/b55b7393aefc874b3c539b883a7b79f5ebebb456/python/vineyard/deploy/utils.py#L206
> Fixes referenced before assignment error

- modules/basic/ds/arrow_shim/memory_pool.cc
- modules/basic/ds/arrow_shim/memory_pool.h
> Adapt to arrow-12 (arrow::MemoryPool interfaces)

- .cirrus.yml
- .github/workflows/build-vineyardd-and-wheels-macos.yaml
- Github has removed the macos-10.15 runner
- There were some failures during installing boost from source using brew on M1 (cirrus-ci)
> Improve the macos CI to build the wheel packages

- k8s/cmd/commands/schedule/schedule_workload.go
> Add the missing topologyKey in the schedule workload subcommand of vineyardctl 

- modules/graph/fragment/arrow_fragment.vineyard-mod
- modules/graph/fragment/arrow_fragment_impl.h
- modules/graph/loader/arrow_fragment_loader.cc
- modules/graph/vertex_map/arrow_vertex_map.h
- python/vineyard/core/codegen/cpp.py
Optimize the func initDestFidList(),  assuming edge num is n, fragment num is m, the original algo's time complexity is O(nlogm), the optimized is O(n)
> Improve the performance of `initDestFidList()` when there are many fragments

- k8s/cmd/README.md
- k8s/cmd/commands/deploy/deploy_vineyard_deployment.go
- k8s/cmd/commands/flags/global_flags.go
- k8s/cmd/commands/sidecar/inject.go
- k8s/cmd/commands/util/parse.go
* Add OwnerReferences for all resource created during deploying vineyard-deployment
* Support deploying vineyard resources in the default namespace.
> Add OwnerReferences for all resource created during deploying vineyard-deployment and support default namespace

- modules/graph/CMakeLists.txt
Vineyard requires libgrape-lite after version https://github.com/alibaba/libgrape-lite/commit/3d2fe9cc28e126231c1e9ce3fa12d815b0ec28ba
> Specify the required version of libgrape-lite

- .github/workflows/vineyard-operator.yaml
- CMakeLists.txt
- CPPLINT.cfg
- modules/basic/ds/array.vineyard-mod
- modules/basic/ds/arrow.vineyard-mod
- modules/basic/ds/dataframe.vineyard-mod
- modules/basic/ds/hashmap.vineyard-mod
- modules/basic/ds/scalar.vineyard-mod
- modules/basic/ds/sequence.vineyard-mod
- modules/basic/ds/tensor.vineyard-mod
- modules/basic/stream/parallel_stream.vineyard-mod
- modules/graph/fragment/arrow_fragment.vineyard-mod
- modules/graph/tools/graph_loader.cc
- src/server/async/socket_server.cc
Use the same file list for `FILES_TO_FORMAT` and `FILES_TO_LINT` to avoid extra directory traverse during cmake configuration.
> Enable cpplint over vineyard-mod files

- charts/vineyard-operator/templates/backup-crd.yaml
- docs/notes/cloud-native/vineyard-operator.rst
- k8s/apis/k8s/v1alpha1/backup_types.go
- k8s/cmd/README.md
- k8s/cmd/commands/deploy/deploy_backup_job.go
- k8s/cmd/commands/flags/backup_flags.go
- k8s/config/crd/bases/k8s.v6d.io_backups.yaml
- k8s/controllers/k8s/backup_controller.go
- k8s/pkg/templates/backup/job.yaml
- k8s/test/e2e/deploy-raw-backup-and-recover/e2e.yaml
- k8s/test/e2e/failover-demo/backup.py
- k8s/test/e2e/failover-demo/backup.yaml
- k8s/test/e2e/failover/e2e.yaml
As titled. The `objectIDs` is more meaningful for users.
Fixes #1322
> Replace the limits with the objectIDs in the backup and recover of vineyard cluster.

- modules/graph/fragment/arrow_fragment.vineyard-mod
The current implementation of GetInnerVertex() is to query all the fragment, it's not needed as we only need the inner vertex
> Improve GetInnerVertex() by querying local fragment only

- k8s/pkg/schedulers/scheduler_inside_cluster.go
- k8s/pkg/schedulers/scheduler_outside_cluster.go
- k8s/pkg/schedulers/scheduling_strategy.go
As titled.
Fixes some errors during e2e test such as https://github.com/v6d-io/v6d/actions/runs/5118226798/jobs/9202046172
> Fix a bug to avoid the panic 'interger divide by zero' during scheduling

- modules/basic/ds/arrow_utils.cc
When calling ConcatenateTables(), the process will core as the out_tables[0] is not initialized.
> Fix ConcatenateTables()

- modules/io/io/io_factory.cc
When the path does not exist, concatenate the missing path information after the absolute path.
Fixes [#2863](https://github.com/alibaba/GraphScope/issues/2863) (GraphScope)
> Fix bug: Inaccurate error message

- k8s/controllers/k8s/sidecar_controller.go
- k8s/pkg/schedulers/common.go
- k8s/pkg/webhook/sidecar/sidecar_webhook.go
- k8s/test/e2e/sidecar-demo/sidecar-with-default-sidecar.yaml
- k8s/test/e2e/sidecar/e2e.yaml
- k8s/test/hack/prepare-e2e.sh
* Fix the bug the sidecar template is not injected into the workload yaml.
* Fix the bug the workload yaml can't contains the special character like '/' during sidecar injection.
* Add the ownerReferences to the Sidecar CR so that all injected resources will be deleted after deleting the workload.
* Add a test case for testing the vineyard sidecar via kubectl.
* Replace the kind version with v0.19.0 rather than v0.20.0.
Related to #1355
> Fix the sidecar can't work as expected and replace the kind version with v0.19.0

- modules/basic/ds/hashmap_mvcc.h
- modules/graph/vertex_map/arrow_vertex_map_impl.h
- test/hashmap_mvcc_test.cc
- test/runner.py
Background: used in gart for ovgid map (mapping from gid to local outer vertex id)
HashmapMVCC is a semi-persistent hashmap data structure which
- each insert returns a (possible) new HashMap instance (`std::shared_ptr<hashmap_t>`)
- insert is not thread safe
- doesn't support delete
- query on old instance may see the future value (similar to READ UNCOMMITTED)
- RAII style
Each snapshot has its own blob, and can be obtained from another process, and won't be affected by insertion in another thread.
See `test/hashmap_mvcc_test.cc` for the usage.
> Implements a semi-persistent flat hashmap data structure

- docker/Dockerfile.vineyardd
As titled. Worked on my Macos M1.
Fixes #1458
> Bump up the version of etcd in the vineyardd image to v3.5.9

- docs/_static/css/index.css
- docs/tutorials/kubernetes/ml-pipeline-mars-pytorch.rst
- python/vineyard/drivers/io/adaptors/parse_bytes_to_dataframe.py
- python/vineyard/drivers/io/adaptors/parse_dataframe_to_bytes.py
- python/vineyard/drivers/io/adaptors/read_orc.py
- python/vineyard/drivers/io/adaptors/read_parquet.py
- python/vineyard/drivers/io/adaptors/write_orc.py
- python/vineyard/drivers/io/adaptors/write_parquet.py
- python/vineyard/drivers/io/stream.py
- python/vineyard/drivers/io/tests/test_open.py
- python/vineyard/io/stream.py
- setup_io.py
```python
chunk_hook: callable, optional
If the read/write target is a global dataframe (e.g., csv,
orc, parquet, etc.), the hook will be called for each chunk
to be read or write (usually a :code:`pyarrow.RecordBatch`).
The hook should return a :code:`pyarrow.RecordBatch` object
and should be stateless as the invoke order is not guaranteed.
E.g.,
.. code:: python
def exchange_column(batch):
import pyarrow as pa
columns = batch.columns
first = columns[0]
second = columns[1]
columns = [second, first] + columns[2:]
return pa.RecordBatch.from_arrays(columns, schema=batch.schema)
```
Fixes #1321
> Add a chunk_hook support for vineyard.{read/write} in io adaptors

- .github/workflows/build-vineyardd-and-wheels-linux.yaml
- .github/workflows/build-vineyardd-and-wheels-macos.yaml
* Build the vineyardctl for on the arm64 macos.
* Add the vineyardctl-${version}-${linux/darwin}-${amd64/arm64} to the release page.
Fixes the first task of https://github.com/v6d-io/v6d/issues/1478
> Add the vineyardctl of mainstream architecture and os to the release page

- charts/vineyard-operator/README.md
- docs/notes/developers/faq.rst
- docs/tutorials/data-processing/accelerate-data-sharing-in-kedro.rst
* Delete the '--wait' flag during the installation of helm chart.
* Add the relevant note.
Fixes #1490
> Delete the '--wait' flag during the installation of helm chart.

- modules/graph/loader/arrow_fragment_loader.cc
- python/vineyard/drivers/io/adaptors/read_bytes.py
In C++ the parameters is `std::map<std::string, std::string>` so any key and value must be in form of string.
Fixes #1494.
> Fixes the io adaptor parameters: the key should be string

- go/vineyard/pkg/client/client_base.go
- go/vineyard/pkg/client/ipc_client.go
- go/vineyard/pkg/client/rpc_client.go
- go/vineyard/pkg/common/protocol.go
- k8s/cmd/README.md
- k8s/cmd/commands/client/get.go
- k8s/cmd/commands/client/get_cluster_info.go
- k8s/cmd/commands/client/ls.go
- k8s/cmd/commands/client/ls_blobs.go
- k8s/cmd/commands/client/ls_metadatas.go
- k8s/cmd/commands/client/ls_objects.go
- k8s/cmd/commands/util/objects.go
- k8s/cmd/commands/util/output.go
- k8s/cmd/commands/util/portforward.go
- k8s/cmd/main.go
- python/pybind11_docs.cc
* Add the get cluster-info API for the golang sdk.
* Add the get cluster-info subcommand for vineyardctl.
* Generate the relevant doc.
Fixes part of #1503
> Implement cluster-info API of Golang SDK and add the vineyardctl get cluster-info subcommand 

- k8s/cmd/commands/deploy/deploy_backup_job.go
- k8s/cmd/commands/util/template.go
Thanks for @zhuyi1159 reporting the bug. Fix the bug the backup job can't be created when set the `pv-pvc-spec`.
> fix the deploy backup job failed when set the pv-pvc-spec

- modules/graph/utils/grape_utils.h
Set a random seed for random generator.
Previously, if we call `random_string()` multiple times, it would generate identical sequences.
```c++
for (int i = 0; i < 3; ++i) {
std::cout << random_string(8) << std::endl;
}
```
```
>>> ./a.out
5PN2qmWq
BlQ9wQj9
9nsQzldV
>>> ./a.out
5PN2qmWq
BlQ9wQj9
9nsQzldV
>>> ./a.out
5PN2qmWq
BlQ9wQj9
9nsQzldV
```
After this PR, it would be
```
>>> ./a.out
MtqfRb9f
D2k0aoDW
dev7na2Y
>>> ./a.out
jZBd0Tr3
zlueuNCh
R4pewYl5
>>> ./a.out
eBpcBiLE
Fv3L36IS
oA6eo6aY
```
> set seed for random generator

- modules/basic/ds/array.h
- modules/basic/ds/arrow.cc
- modules/basic/ds/arrow.h
- modules/graph/fragment/arrow_fragment_builder_impl.h
- modules/graph/fragment/property_graph_utils.h
- modules/graph/fragment/property_graph_utils_impl.h
- modules/graph/fragment/property_graph_utils_uint32.cc
- modules/graph/fragment/property_graph_utils_uint64.cc
- src/server/memory/memory.cc
This pull request enhances the previous varint encoding implementation by:
- use serialized, batch encoding (not slow than previous implementation, thanks to batching)
- reuse the ie list when encoding, avoid extra memory allocation and copy
- use the shrink API to adjust the size of the encoded blob writer.
After this pull request, compacting edges with varint no longer requires extra memory, and the encoding execution time has been optimized (almost half) as well.
Fixes #1373
> Improve the varint encoding for edges by avoiding copy and extra memory

- .github/workflows/vineyard-operator.yaml
- k8s/test/e2e/Makefile
- k8s/test/e2e/vineyardctl/e2e.yaml
* Fix the e2e test log that can't be exported when releasing.
* Keep the vineyardd image consistent with the previously built one.
> Export the e2e test log when releasing and keep the vineyardd image consistent with the built one

- .dockerignore
- docker/Dockerfile.vineyardd
- docker/Makefile
- src/server/util/kubectl.cc
Add libunwind to the vineyardd as well during docker build.
Fixes #1535
> Fixes vineyardd crash caused by empty environment variable

- .github/workflows/vineyard-operator.yaml
Debug such error https://github.com/v6d-io/v6d/actions/runs/5960338972/job/16167472211
> Bump up k8s logs exporter to v6 for debugging

- docs/notes/cloud-native/deploy-kubernetes.rst
- k8s/pkg/templates/etcd/etcd.yaml
- k8s/test/e2e/Makefile
- k8s/test/e2e/airflow-integration/e2e.yaml
- k8s/test/e2e/deploy-raw-backup-and-recover/e2e.yaml
- k8s/test/e2e/schedule-workflow-without-crd/e2e.yaml
- k8s/test/e2e/schedule-workload/e2e.yaml
- k8s/test/e2e/sidecar-demo/sidecar-with-custom-sidecar.yaml
- k8s/test/e2e/sidecar/e2e.yaml
- k8s/test/e2e/spill-demo/vineyardd-with-spill.yaml
- k8s/test/e2e/vineyardctl/e2e.yaml
- k8s/test/e2e/vineyardd.yaml
As the vineyardd image is defined as `vineyardcloudnative/vineyardd:latest` in our CRD apis and the args of vineyardctl. It's better to only keep one tag `latest` rather than `alpine-latest` and `latest` in the e2e test.
> Unify the vineyardd images in the vineyard operator e2e tests

- java/hive/src/main/java/io/v6d/hadoop/fs/FileSystem.java
- java/hive/src/main/java/io/v6d/hive/ql/io/VineyardFileStorageFormatDescriptor.java
- java/hive/src/main/java/io/v6d/hive/ql/io/VineyardOutputFormat.java
- java/hive/src/main/java/io/v6d/hive/ql/io/VineyardStorageFormatDescriptor.java
- java/hive/src/main/resources/META-INF/services/org.apache.hadoop.hive.ql.io.StorageFormatDescriptor
- Support access to tables created by other users in the vineyard
- Support point out storage as vineyard instead of pointing out io format.
- ...
Fixes #1420
> Enhance the integrated hive module: add vineyard format descriptor and fixes FS.renameInternal

- go/vineyard/pkg/client/ipc_client.go
- k8s/cmd/README.md
- k8s/cmd/commands/client/get.go
- k8s/cmd/commands/client/put.go
- k8s/cmd/commands/flags/client_flags.go
- k8s/cmd/commands/util/objects.go
- k8s/cmd/main.go
> Implement vineyardctl put command

- .github/workflows/build-vineyardd-and-wheels-macos.yaml
- k8s/Makefile
As titled. Failed on the macos (arm64/amd64).
/cc @zhuyi1159
> Delete upx for vineyardctl on the macos machine as test failed.

- charts/vineyard-operator/values.yaml
- k8s/Makefile
> Delete the latest tag so that the helm chart use the Chart.AppVersion as the image tag

- .github/workflows/vineyard-operator.yaml
- k8s/test/e2e/autogenerated-helm-chart/e2e.yaml
* Use the latest tag for the vineyard operator image in the generated helm chart e2e test.
* Fix the sha not exposed in the push event.
> Fix the error in the helm chart e2e test and the sha not exposed in the push event

- .github/workflows/build-test.yml
- modules/graph/fragment/graph_schema.cc
As GIE no longer requires it and it causes some trouble for GAE users.
> Remove the validation about inconsitent property type between different labels

- modules/graph/test/arrow_fragment_label_data_extend.cc
The current implementation of incremental update seems only support "retain_oid=true", however, the test hasn't set the option, and the test will core dump.
> Fix test of incremental update

- modules/graph/fragment/gar_fragment_builder.h
- modules/graph/fragment/gar_fragment_builder_impl.h
- modules/graph/loader/gar_fragment_loader.cc
- modules/graph/loader/gar_fragment_loader.h
- modules/graph/loader/gar_fragment_loader_impl.h
- modules/graph/writer/arrow_fragment_writer.cc
- modules/graph/writer/arrow_fragment_writer.h
- modules/graph/writer/arrow_fragment_writer_impl.h
- modules/graph/writer/arrow_fragment_writer_string.cc
- Align the vertices of fragment to vertex chunk size by append nulls, so the multi-fragment writer out to gar format also correct
- Fix the gar loader shuffle oid array bug: remove the multi-thread implementation since that shuffle already use thread to send/recv, that would make message conflict
- Bump up GraphAr to support build with local installed arrow.
TBF
> [GraphAr] Align the vertices of fragment to vertex chunk size & Fix the shuffle array multi-thread bug & Bump up GraphAr 

- k8s/pkg/schedulers/scheduling_strategy.go
- k8s/test/e2e/kind-with-local-registry.yaml
- k8s/test/e2e/kind.yaml
With it, we can schedule the workloads that only produce the localobjects.
> Support to track the chunks by local objects for kubernetes workflow.

- .github/workflows/build-test-graph.yml
- .github/workflows/build-test.yml
- modules/basic/ds/arrow_utils.cc
- modules/fuse/adaptors/arrow_ipc/serializer_registry.cc
- modules/graph/fragment/property_graph_utils_impl.h
- modules/graph/utils/table_shuffler.cc
> Fixes build failure with apache-arrow 14

- .github/workflows/build-test-graph.yml
- .github/workflows/build-test.yml
- python/vineyard/data/tensor.py
- python/vineyard/data/tests/test_dataframe.py
- rust/vineyard-integration-testing/src/ds/numpy_test.rs
- rust/vineyard-integration-testing/src/ds/pandas_test.rs
The change is backwards-compatible and fixes the issue in Rust SDK.
> Use arrow's string array to place string columns in vineyard

- python/core.cc
- python/vineyard/contrib/ml/tests/test_dali.py
- python/vineyard/contrib/ml/tests/test_mxnet.py
- python/vineyard/contrib/ml/tests/test_tensorflow.py
- python/vineyard/contrib/ml/tests/test_torch.py
- python/vineyard/contrib/ml/tests/test_torcharrow.py
- python/vineyard/contrib/ml/tests/test_xgboost.py
- python/vineyard/core/resolver.py
- python/vineyard/core/tests/test_rpc_client.py
- python/vineyard/data/arrow.py
- python/vineyard/data/base.py
- python/vineyard/data/tests/test_arrow.py
- python/vineyard/data/tests/test_base.py
- python/vineyard/data/tests/test_dataframe.py
- python/vineyard/data/tests/test_default.py
- python/vineyard/data/tests/test_pickle.py
- python/vineyard/data/tests/test_tensor.py
- python/vineyard/data/utils.py
- src/client/client_base.cc
- src/client/ds/blob.cc
- src/client/ds/object_meta.cc
- src/client/ds/object_meta.h
- src/client/ds/remote_blob.cc
- src/client/ds/remote_blob.h
- src/client/rpc_client.cc
- test/runner.py
With it, rpc_client and ipc_client can get/put the value as the same way.
> Support to use RPC to get object and improve the resolver and builder of python

- python/vineyard/contrib/kedro/benchmark/mlops/argo-vineyard-benchmark.yml
As titled. It can fix something wrong like `index out of range[0] with length 0`.
> Add the JOB_NAME Env to the argo-vineyard-benchmark.yaml

- python/vineyard/deploy/ctl.py
> Ignore the exception during loading the vineyardctl APIs

- modules/graph/loader/basic_ev_fragment_loader_impl.h
The bug was first introduced in https://github.com/v6d-io/v6d/commit/1de8226e17b564230e5d535925c0c318ea69458c#diff-f5dfc05a30caf83fbf2edde2db77177a8bf8bb8bb296b0d8259a89f566a833ff and causes https://github.com/alibaba/GraphScope/actions/runs/7044062862/job/19176259486?pr=3392
There's also a workaround i graphscope (https://github.com/alibaba/GraphScope/pull/3421) to fixes the CI failure.
> Fixes a missing assignment in edge id generation

- python/core.cc
- python/pybind11_docs.cc
- python/pybind11_docs.h
- python/pybind11_utils.cc
- python/pybind11_utils.h
- python/vineyard/data/arrow.py
- python/vineyard/data/benchmarks/__init__.py
- python/vineyard/data/benchmarks/test_tensor.py
- python/vineyard/drivers/io/adaptors/deserializer.py
- src/common/memory/memcpy.h
- test/concurrent_memcpy_test.cc
- test/runner.py
Remove the problematic `.buffer` property (as it cannot bind the lifetime of the underlying blob to the memoryview object) and add concurrent support for memcpy for faster object building.
Fixes #1631
> Implement concurrent memcpy for building Python objects into vineyard

- docker/Dockerfile.vineyardd
- docs/notes/cloud-native/vineyard-operator.rst
- k8s/cmd/README.md
- k8s/cmd/commands/deploy/deploy_vineyard_deployment_test.go
- k8s/cmd/commands/inject/inject.go
- k8s/cmd/commands/inject/inject_test.go
- k8s/pkg/templates/sidecar/injection-template.yaml
- k8s/pkg/templates/vineyardd/deployment.yaml
- k8s/test/e2e/sidecar-demo/sidecar-with-custom-sidecar.yaml
- k8s/test/e2e/sidecar-demo/sidecar-with-default-sidecar.yaml
- k8s/test/e2e/sidecar/e2e.yaml
Delete the wait-for-it.sh as the vineyardd already supports the retry logic of connecting the etcd.
> Delete the wait-for-it.sh as the vineyardd already support the retry logic  of connecting the etcd.

- modules/graph/CMakeLists.txt
```
clang: error: unsupported option '-fopenmp'
```
fixes #1652
relates to homebrew/homebrew-core#157199
> fix: remove `-fopenmp` option for macOS builds

- src/server/services/etcd_meta_service.cc
- src/server/util/etcd_launcher.cc
- src/server/util/redis_launcher.cc
> Delete the retry logic while launching metadata service and reset the etcd client while probing

- modules/graph/fragment/arrow_fragment.vineyard-mod
We I want to use Arrow fragment's method GetVertexMap() in GAE apps, there will be a compile error, as the fragment is const, but the method is not const, so, add a new const method for GAE apps.
`void PEval(const fragment_t& frag, context_t& ctx,
message_manager_t& messages) `
> Add a const method for GetVertexMap

- python/vineyard/drivers/io/adaptors/read_bytes.py
- python/vineyard/drivers/io/adaptors/read_bytes_collection.py
- python/vineyard/drivers/io/adaptors/read_orc.py
- python/vineyard/drivers/io/adaptors/read_parquet.py
- python/vineyard/drivers/io/adaptors/write_bytes.py
- python/vineyard/drivers/io/adaptors/write_bytes_collection.py
- python/vineyard/drivers/io/adaptors/write_orc.py
- python/vineyard/drivers/io/adaptors/write_parquet.py
- python/vineyard/drivers/io/fsspec_adaptors.py
To allow users use paths like `oss://a/b/c/` as the folder path to reading multiple files.
> Restore the old behaviour of auto-glob given prefix/folders in io adaptors

- python/core.cc
- python/vineyard/contrib/ml/README.md
- python/vineyard/contrib/ml/tests/test_torch.py
- python/vineyard/contrib/ml/torch.py
- python/vineyard/core/resolver.py
- python/vineyard/data/utils.py
> Enable sharing pytorch modules

- k8s/cmd/README.md
- k8s/cmd/commands/deploy/deploy_vineyard_deployment_test.go
- k8s/cmd/commands/inject/inject.go
- k8s/cmd/commands/inject/inject_test.go
- k8s/config/manager/kustomization.yaml
- k8s/pkg/templates/sidecar/injection-template.yaml
- k8s/pkg/templates/vineyardd/etcd-service.yaml
- k8s/pkg/webhook/sidecar/sidecar_webhook.go
- k8s/test/e2e/sidecar-demo/sidecar-with-custom-sidecar.yaml
- k8s/test/e2e/sidecar-demo/sidecar-with-default-sidecar.yaml
- k8s/test/e2e/sidecar/e2e.yaml
- prometheus/grok_exporter.yml
Fixes the sidecar part of https://github.com/v6d-io/v6d/issues/1679
> Fix the sidecar ci error.

- k8s/cmd/commands/deploy/deploy_vineyard_deployment.go
- k8s/cmd/commands/deploy/deploy_vineyard_deployment_test.go
- k8s/cmd/commands/inject/inject.go
- k8s/cmd/commands/inject/inject_test.go
- k8s/cmd/commands/util/template_test.go
- k8s/controllers/k8s/sidecar_controller.go
- k8s/controllers/k8s/vineyardd_controller.go
- python/vineyard/core/client.py
The e2e repartition is caused by the error as follows.
```
start to get ddf                                                                                                                                                                                       │
│ /usr/local/lib/python3.10/site-packages/vineyard/core/client.py:536: UserWarning: Migrating object ObjectID <"o0024772b04722d27"> from another vineyard instance 18446744073709551615                  │
│   warnings.warn(                                                                                                                                                                                       │
│ Traceback (most recent call last): …
```
> Fix the unit test error and adjust the condition for fetching objects

- modules/basic/ds/arrow.cc
- modules/basic/ds/arrow.h
- modules/basic/ds/arrow.vineyard-mod
- modules/basic/ds/arrow_utils.cc
- modules/basic/ds/arrow_utils.h
- modules/basic/ds/types.cc
- modules/basic/ds/types.h
- modules/graph/fragment/graph_schema.cc
- modules/graph/fragment/property_graph_types.h
- modules/graph/loader/gar_fragment_loader_impl.h
- modules/graph/test/arrow_fragment_extend_test.cc
- modules/graph/utils/table_shuffler.cc
- modules/graph/utils/table_shuffler.h
- modules/graph/writer/arrow_fragment_writer.cc
- modules/graph/writer/arrow_fragment_writer_impl.h
- python/vineyard/core/codegen/cpp.py
- python/vineyard/core/codegen/parsing.py
- src/common/util/macros.h
> Enable date and time types support in vineyard-graph

- src/server/util/etcd_launcher.cc
- src/server/util/spec_resolvers.cc
Add the command line flag `--etcd_data_dir`.
Fixes #1722
> Add a command line flag `--etcd_data_dir` for etcd's data dir

- modules/basic/ds/arrow.cc
- modules/basic/ds/arrow_shim/concatenate.cc
> Adapt to apache-arrow 15

- python/vineyard/core/client.py
- python/vineyard/deploy/kubernetes.py
- python/vineyard/shared_memory/shared_memory.py
- requirements-dev.txt
When using something like `client = vineyard.connect(config=./vineyard.yaml)`, we need to check whether the IPC socket file exists.
> Check whether the ipc socket exist When parsing the config YAML.

- python/vineyard/__init__.py
- python/vineyard/core/client.py
* Add the environment  to connect the vineyard server via client config file.
* Wrap `vineyard.connect` and `client.put` as `vineyard.put` to allow users to connect using environment variables.
* Wrap `vineyard.connect` and `client.get` as `vineyard.get` to allow users to connect using environment variables.
> Implement vineyard.put and vineyard.get to simplify the client configurations

- modules/kv-state-cache/ds/kv_state_cache.cc
- modules/kv-state-cache/ds/kv_state_cache.h
- modules/kv-state-cache/ds/kv_state_cache_block.cc
- modules/kv-state-cache/ds/kv_state_cache_block.h
- modules/kv-state-cache/radix-tree/radix-tree.cc
- modules/kv-state-cache/radix-tree/radix-tree.h
- modules/kv-state-cache/radix-tree/radix.cc
- modules/kv-state-cache/radix-tree/radix.h
- modules/kv-state-cache/strategy/LRU_strategy.cc
- modules/kv-state-cache/strategy/LRU_strategy.h
- modules/kv-state-cache/utils/kv_state_cache_utils.cc
- modules/kv-state-cache/utils/kv_state_cache_utils.h
- test/kv_state_cache_object_test.cc
- test/kv_state_cache_test.cc
- test/rax_diff_test.cc
-  Add timestamp for node
- Support merge two radix tree
- Support merge cache object
- Refactor the framework of cache object, cache block object and radix tree
- Fix error of setting sub_tree flag, as well as some derived bugs caused by the error
- Format the code to an unified style
Fixes #1734 #1719 #1718 #1717
> Support merge tree / merge object / bug fix.

- modules/kv-state-cache/ds/kv_state_cache.cc
- modules/kv-state-cache/radix-tree/radix-tree.cc
- modules/kv-state-cache/radix-tree/radix-tree.h
- modules/kv-state-cache/radix-tree/radix.cc
- modules/kv-state-cache/radix-tree/radix.h
- test/kv_state_cache_test.cc
- test/rax_diff_test.cc
> Recycle resources of kv state cache object.

- python/vineyard/contrib/pyspark/pyspark.py
- python/vineyard/contrib/pyspark/tests/test_pyspark.py
Previously(#1529), putting a pyspark.dataframe into vineyard defaulted to the `vineyard::Table` type, getting it back to pyspark.dataframe required very ad-hoc operations. These changes add wrappers to make the `put/get` pyspark.dataframe to vineyard more intuitive. An example:
```python3
id = vineyard_client.put(dataframe, spark_conf=conf, socket=vineyard_socket)
your_df = vineyard_client.get(id, spark_conf=conf, socket=vineyard_socket)
```
> Fixes roundtrip put/get pyspark.dataframe into/from vineyard.

- python/vineyard/core/client.py
Add a default value `/vineyard/config.yaml` for the vineyard configuration while connecting.
Fixes #1750
> Add a default value for the VINEYARD_CONFIG while connecting.

- docker/vineyard-fluid-fuse/entrypoint.sh
- python/vineyard/__init__.py
- python/vineyard/core/client.py
- Create a hard link of vineyard socket rather than mount its parent directory in `vineyard-fluid-fuse`.
- Change the vineyard configuration from `vineyard.yaml` to `config.yaml`.
Related to https://github.com/fluid-cloudnative/fluid/pull/3713
> Create a hard link of vineyard socket rather than mount its parent directory.

- modules/kv-state-cache/ds/kv_state_cache.cc
- modules/kv-state-cache/ds/kv_state_cache.h
- modules/kv-state-cache/ds/kv_state_cache_block.cc
- modules/kv-state-cache/ds/kv_state_cache_block.h
- modules/kv-state-cache/utils/kv_state_cache_utils.cc
- modules/kv-state-cache/utils/kv_state_cache_utils.h
- test/kv_state_cache_radix_tree_test.cc
- test/kv_state_cache_test.cc
- test/kv_state_cache_test_2.cc
> Support layer for kv state cache

- k8s/examples/vineyard-on-fluid/linear-regression-with-vineyard.py
- k8s/examples/vineyard-on-fluid/prepare-dataset.py
> Add the example code of how to accelerate the data sharing with vineyard on fluid platform.

- python/vineyard/__init__.py
- python/vineyard/core/client.py
- Add the vineyard directory for searching vineyard config file. E,g, `client = vineyard.connect(config='/var/run')`, the client will search the config file `/var/run/vineyard-config.yaml` and `/var/run/vineyard/vineyard-config.yaml`.
- Support to parse endpoints like `127.0.0.1:9600,127.0.0.2:9600`.
> Add the vineyard directory for searching vineyard config file and support multiple rpc endpoints.

- modules/basic/ds/dataframe.cc
- modules/llm-cache/ds/kv_state_cache.cc
- modules/llm-cache/ds/kv_state_cache.h
- modules/llm-cache/ds/kv_state_cache_block.cc
- modules/llm-cache/ds/kv_state_cache_block.h
- modules/llm-cache/ds/kv_state_cache_manager.cc
- modules/llm-cache/ds/kv_state_cache_manager.h
- modules/llm-cache/radix-tree/radix-tree.cc
- modules/llm-cache/radix-tree/radix-tree.h
- modules/llm-cache/tests/kv_state_cache_benchmark_test.cc
- modules/llm-cache/tests/kv_state_cache_multi_test.cc
- modules/llm-cache/tests/kv_state_cache_radix_tree_test.cc
- modules/llm-cache/tests/kv_state_cache_test.cc
- thirdparty/rax/radix.cc
- thirdparty/rax/radix.h
- Improve the `query` API, users only input a token list and will get the kv_cache with the longest prefix.
- Use vector<uint8_t> as payload object.
- Replace the alias of KV_STATE_WITH_LAYER with std::map<int, std::pair<K_STATE, V_STATE>>.
- Rename the `Dimension` with `TensorBytes`.
- Use the references of `std::vector<T>` to avoid copying.
- Print the rax tree to a string for debugging.
- Fixes #1786
- Fixes #1792
- Fixes #1795
> Improve the query API of llm cache and use vector<uint8_t> as payload object.

- CMakeLists.txt
- LICENSE
- modules/llm-cache/CMakeLists.txt
- modules/llm-cache/ds/kv_state_cache.cc
- modules/llm-cache/radix-tree/radix-tree.h
- modules/llm-cache/tests/kv_state_cache_radix_tree_test.cc
- modules/llm-cache/tests/kv_state_cache_test.cc
Currently, the rax headers will not be installed as it's under the [exclude pattern](https://github.com/v6d-io/v6d/blob/main/CMakeLists.txt#L613), and the pr is to add the script for installing rax headers.
A follow up of https://github.com/v6d-io/v6d/pull/1787 and fix https://github.com/v6d-io/v6d/issues/1785
> Install the rax headers under the thirdparty directory.

- python/vineyard/core/client.py
- python/vineyard/deploy/tests/test_distributed.py
- python/vineyard/deploy/tests/test_migration.py
> Support to put the data to the vineyardd instance with the most available memory

- modules/graph/CMakeLists.txt
- modules/graph/loader/gar_fragment_loader.h
- modules/graph/loader/gar_fragment_loader_impl.h
- modules/graph/test/arrow_fragment_gar_test.cc
- modules/graph/writer/arrow_fragment_writer.cc
- modules/graph/writer/arrow_fragment_writer.h
- modules/graph/writer/arrow_fragment_writer_impl.h
- modules/graph/writer/util.cc
- modules/graph/writer/util.h
- Bump up GraphAr to v0.11.3 to support `Date` and `Timestamp` type, make the whole ldbc dataset dumps work
- Refine the `ArrowFragmentWriter` to support write graph with selected vertices/edges and propertices
Fixes #1812
> GraphAr: Support load and write subgraph to graphar with selected vertices/edges and properties

- modules/llm-cache/CMakeLists.txt
- modules/llm-cache/ds/kv_state_cache_blob.h
- modules/llm-cache/ds/kv_state_cache_block.cc
- modules/llm-cache/ds/kv_state_cache_block.h
- modules/llm-cache/ds/kv_tensor.h
Before:
```
$ ldd libvineyard_llm_cache.so | grep arrow
libarrow.so.1500 => /lib/x86_64-linux-gnu/libarrow.so.1500 (0x00007f5da9879000)
```
Now:
```
$ ldd libvineyard_llm_cache.so | grep arrow
```
Fixes https://github.com/v6d-io/v6d/issues/1818
> Replace Tensor and TensorBuilder with the KVTensor and KVTensorBuilder to delete the arrow deps.

- modules/llm-cache/CMakeLists.txt
In macos, fix the such following error.
> Add the glog libraries when build the vineyard llm cache module.

- k8s/controllers/k8s/backup_controller.go
- k8s/controllers/k8s/csidriver_controller.go
- k8s/controllers/k8s/operation_controller.go
- k8s/controllers/k8s/recover_controller.go
- k8s/controllers/k8s/sidecar_controller.go
- k8s/controllers/k8s/vineyardd_controller.go
Removes unnecessary `time.ParseDuration("1m")` from `Reconcile` functions in controllers package and replaces it by using standard constant `time.Minute` from `time` package.
> [k8s]: Remove unnecessary time parsing in reconcile functions

- LICENSE
- README.rst
- modules/llm-cache/CMakeLists.txt
- modules/llm-cache/hash/hash_algorithm.h
- modules/llm-cache/hash/hasher.h
- modules/llm-cache/tests/kv_state_cache_hash_test.cc
- test/runner.py
- thirdparty/MurmurHash3/MurmurHash3.cc
- thirdparty/MurmurHash3/MurmurHash3.h
I have tested the hash functions `MurmurHash3` and `CityHash` with 100000 different seqs(each seq contains 10 tokens) for multiple times, and the result is as follows.
```
MurmurHash3Algorithm conflict count is 7 / 1600000
CityHashAlgorithm conflict count is 4 / 1600000
```
or
```
MurmurHash3Algorithm conflict count is 1 / 1600000
CityHashAlgorithm conflict count is 3 / 1600000
```
Basically, the conflict rate of the two hash functions is same.
Part of https://github.com/v6d-io/v6d/issues/1832
> Add the hash function for batched tokens in llm kv cache.

- modules/llm-cache/ds/config.h
- modules/llm-cache/ds/kv_state_cache_manager.cc
- modules/llm-cache/ds/kv_state_cache_manager.h
- modules/llm-cache/storage/blob_storage.cc
- modules/llm-cache/storage/blob_storage.h
- modules/llm-cache/storage/file_storage.cc
- modules/llm-cache/storage/file_storage.h
- modules/llm-cache/storage/local_file_storage.cc
- modules/llm-cache/storage/local_file_storage.h
- modules/llm-cache/storage/storage.h
- modules/llm-cache/tests/kv_state_cache_benchmark_test.cc
- modules/llm-cache/tests/kv_state_cache_local_file_test.cc
- modules/llm-cache/tests/kv_state_cache_test.cc
- modules/llm-cache/tests/refcnt_map_test.cc
- python/vineyard/llm/kv_state_cache.cc
- Add  file storage framework of llm module
- Disable vineyard memory usage checks of llm test provisionally. (Fix in the future #1838 )
The current update/query function needs to be refined, which will be done in a future  pr( @dashanji ). This is just to add a framework.
Fixes part of #1833
> Add fs storage framework for llm

- modules/basic/ds/arrow_utils.cc
- modules/graph/fragment/arrow_fragment.vineyard-mod
- modules/graph/fragment/arrow_fragment_impl.h
> Fixes value getters for date/time/timestamp arrays

- modules/llm-cache/storage/file_storage.cc
- modules/llm-cache/storage/local_file_storage.cc
fix the macos build failure, error logs are below:
```
/tmp/vineyard-20240419-52947-c35b1q/v6d-0.22.0/modules/llm-cache/storage/file_storage.cc:667:7: error: no matching conversion for functional-style cast from 'std::chrono::duration<int64_t, std::nano>' (aka 'duration<long long, ratio<1LL, 1000000000LL>>') to 'std::chrono::time_point<std::chrono::system_clock>'
std::chrono::time_point<std::chrono::system_clock>(time);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
/tmp/vineyard-20240419-52947-c35b1q/v6d-0.22.0/modules/llm-cache/storage/local_file_storage.cc:196:15: error: no member named 'st_atim' in 'stat'
statbuf.st_atim.tv_sec * SECOND_TO_NANOSECOND + statbuf.st_atim.tv_nsec);
~~~~~~~ ^ …
```
> build: add macos build patch

- requirements-dev.txt
Fix ci errors:
https://github.com/v6d-io/v6d/actions/runs/9094070695/job/24994345286
https://github.com/v6d-io/v6d/actions/runs/9057457282/job/24882535493
> Fix the incompatible google-re2

- python/client.cc
- python/vineyard/contrib/ml/README.md
- python/vineyard/contrib/ml/torch.py
- python/vineyard/core/client.py
* Support to put a torch module dispersedly into all vineyard instances.
* Improve the torch module doc.
Fixes https://github.com/v6d-io/v6d/issues/1884
> Support to put a torch module into all vineyard instances dispersedly

- src/client/io.cc
- src/server/async/socket_server.cc
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
- src/server/util/remote.cc
- src/server/util/remote.h
./bin/vineyardd --compression=false --reserve_memory=true --size=20Gi --etcd_endpoint=192.168.0.239:2379
./bin/vineyardd --compression=false --reserve_memory=true --size=20Gi --etcd_endpoint=192.168.0.239:2379
The code is:
```python
import safetensors
import safetensors.torch
import torch
import vineyard
from concurrent.futures import ThreadPoolExecutor, as_completed
import time
from vineyard.contrib.ml.torch import torch_context
state_file = "./stable-diffusion-v1-5-pruned-emaonly.safetensors"
with open(state_file, 'rb') as f:
state_dict = safetensors.torch.load(f.read())
client = vineyard.connect("/var/run/vineyard.sock")
with torch_context(client):
obj = client.put(state_dict, persist=True, name="state_dict")
client2 = …
```
> Improve the implementation of migrating an object with lots of blobs

- .github/workflows/build-test.yml
- modules/llm-cache/storage/blob_storage.cc
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
- src/server/util/remote.cc
- test/runner.py
- Fix bug that migrate object fail if the object size is zero.
- Fix but that vineyardd will stuck when request the same remote object twice in a short period of time.
- Delete objectID from migrations map when client delete it.
- Temporarily disable the kv_cache_local_file_test (This test has some problem. It will be fixed in another pr.)
- Fix the wrong return value of Query function in blob storage.
Fixes #1919
> Fix migrate buffer bug.

- python/client.cc
- python/vineyard/deploy/tests/test_migration.py
- src/server/async/socket_server.cc
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
A follow-up of https://github.com/v6d-io/v6d/pull/1920
Fixes https://github.com/v6d-io/v6d/issues/1924
> Defer object migration to avoid blocking the I/O thread.

- .github/workflows/vineyard-operator.yaml
- .stoat/config.yaml
- docker/Dockerfile.vineyardd
- k8s/test/e2e/Makefile
- k8s/test/e2e/etcd-failover/consumer.yaml
- k8s/test/e2e/etcd-failover/five-etcd-nodes-failover-e2e.yaml
- k8s/test/e2e/etcd-failover/producer.yaml
- k8s/test/e2e/etcd-failover/three-etcd-nodes-failover-e2e.yaml
- k8s/test/e2e/etcd-failover/vineyardd.yaml
- k8s/test/e2e/verify/object-id.yaml
- python/vineyard/deploy/tests/test_vineyardd_failure.py
- src/server/server/vineyard_runner.cc
- src/server/server/vineyard_server.cc
- src/server/server/vineyard_server.h
- src/server/services/etcd_meta_service.cc
- src/server/services/etcd_meta_service.h
- src/server/services/meta_service.cc
- src/server/services/meta_service.h
- src/server/util/etcd_launcher.cc
- src/server/util/etcd_launcher.h
- src/server/util/etcdctl.cc
- src/server/util/etcdctl.h
- src/server/util/spec_resolvers.cc
- test/etcd_member_test.cc
- test/runner.py
* Add the etcdctl cmd flag.
* Launch an etcd instance when start a vineyardd instance.
* Remove the related etcd member when a vineyardd instance exit.
Fixes https://github.com/v6d-io/v6d/issues/1922
> Implement etcd lifecycle management for vineyardd

- src/server/async/rpc_server.cc
- src/server/async/rpc_server.h
- src/server/async/socket_server.h
Currently vineyard server and RPCServer save each other's shared pointers. This will cause the code in the destructor to not be called when vineyardd exits. The resource release operation is therefore moved to the Stop function.
> Fix destructor function bug of RPCServer

- CMakeLists.txt
> Remove libfabric.a from VINEYARD_INSTALL_LIBS

- python/vineyard/drivers/io/adaptors/read_bytes.py
Fix a tricky bug in `read_bytes.py`, may cause data loss in certain scenario.
> Fix a bug in read_bytes.py

- modules/graph/utils/error.h
- python/vineyard/drivers/io/adaptors/read_bytes.py
So that every file should shift 1 byte left to begin. Previously it would only do that for the first file for the `if index == 0` condition.
And make the error message conform to the error return proposal.
> Fix cases where every file has a header

- python/client.cc
- python/vineyard/core/client.py
- src/client/client_base.cc
- src/client/client_base.h
- src/client/io.cc
- src/client/io.h
- src/client/rpc_client.cc
Usage
```
client.timeout_seconds = 10
client.get_meta()
client.get()
```
Fixes https://github.com/v6d-io/v6d/issues/1973
> Add the timeout options for vineyard client.

- src/common/rdma/rdma.cc
- src/common/rdma/rdma_server.cc
- src/server/async/rpc_server.cc
> Fix bug that rdma server rx complete queue will be blocked if client crashed.

- CMakeLists.txt
- docker/Dockerfile.vineyard-python-dev
- docker/Dockerfile.vineyardd
- docker/Makefile
- docker/pypa/Dockerfile.manylinux1
- docker/vineyardd/Dockerfile.alpine-builder
I have successfully built all build/wheel-builder/vineyardd/ images with x86_64/aarch64 locally and pushed the builder images to the github registry. We can check whether it can work in CI.
Fixes https://github.com/v6d-io/v6d/issues/1971
> Refactor Dockerfile: update the mirror to Aliyun and adapt to the RDMA configurations.

- modules/llm-cache/ds/kv_cache_manager.cc
- modules/llm-cache/ds/kv_cache_manager.h
- modules/llm-cache/ds/vineyard_file.cc
- modules/llm-cache/ds/vineyard_file.h
- modules/llm-cache/storage/file_storage.cc
- modules/llm-cache/storage/file_storage.h
- modules/llm-cache/storage/local_file_storage.cc
- modules/llm-cache/storage/storage.h
- modules/llm-cache/storage/vineyard_file_storage.cc
- modules/llm-cache/storage/vineyard_file_storage.h
- python/vineyard/llm/cache.cc
- python/vineyard/llm/cache.py
- python/vineyard/llm/tests/test_llm.py
- src/client/client.cc
- src/client/client.h
- src/client/ds/object_meta.cc
- src/client/ds/object_meta.h
- src/client/rpc_client.cc
- src/client/rpc_client.h
> Integration RDMA module with llm cache.

- src/client/rpc_client.cc
- src/server/async/rpc_server.cc
- src/server/async/socket_server.cc
- src/server/async/socket_server.h
> Clear all migrating locked object when client crashed.

- CMakeLists.txt
When running `make vineyard_client_python` on macos, get the following error:
```
ld: unknown option: --version-script=
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
> Fix make vineyard_client_python on macos.

- .github/workflows/vineyard-operator.yaml
- k8s/cmd/commands/util/usage/types.go
- k8s/cmd/main.go
- k8s/test/e2e/Makefile
- k8s/test/e2e/etcd-failover/three-etcd-nodes-failover-e2e.yaml
- k8s/test/e2e/vineyardctl-python-api/e2e.yaml
As titled.
Fixes https://github.com/v6d-io/v6d/issues/1990
> Fix the error of vineyardctl and add the related test.

- python/client.cc
- python/pybind11_docs.cc
- python/pybind11_docs.h
- python/vineyard/core/client.py
- src/client/ds/blob.cc
- src/client/ds/i_object.cc
- src/server/async/socket_server.cc
- src/server/memory/usage.h
- src/server/util/spill_file.cc
- src/server/util/spill_file.h
- test/concurrent_lru_spill_test.cc
- test/lru_spill_test.cc
- test/lru_test.cc
- test/release_test.cc
- test/runner.py
- test/spill_test.cc
As titled.
Fixes https://github.com/v6d-io/v6d/issues/1972
> Support to spill objects with LRU strategy by vineyardd itself.

- benchmark/blob_test/blob_test.cc
> Add the bandwidth result and disable compression by default in the blob benchmark
